### PR TITLE
Updating csharp scenario

### LINKED ISSUE #402: Update aspnet core
Hi @petersonfs @glennc @Eilon,

**ASP** implementation is here in `1.1`.

Do you mind helping us porting to `2.1` ?

Regards,

### PR DESCRIPTION
**Pull request by sebastienros**
Fixes #402

### CODE REVIEW

**Comment by sebastienros** [comment]
/cc @rynowak

We are not using `.Map` directly because one of the routes is using templating

**Comment by waghanza** [comment]
@sebastienros Which `docker` **version** are you using ?

I am on `Docker version 1.13.1, build 584d391/1.13.1` and the keyword `AS` is not recognized

**Comment by waghanza** [comment]
It's working with `Docker version 18.03.1-ce, build 9ee9f40`

**Comment by rynowak** [comment]
This seems fine. We should update again for 2.2 when it's available

**Comment by waghanza** [comment]
It will be a pleaser :heart:

**Pull request merged**
