### PR TITLE
[PHP] Update imi

### PR DESCRIPTION
**Pull request by Yurunsoft**
* Use CoServer Mode by imi v1.0.13
* Update swoole version to 4.4.7

### CODE REVIEW

**Comment by waghanza** [comment]
@Yurunsoft :tada: 

Can you also use the same version in `php/swoft/Dockerfile` ?

**Comment by Yurunsoft** [comment]
@waghanza The small version of swoole has little impact on performance, but each version will fix some bugs. I suggest using the latest version.

**Comment by waghanza** [comment]
@Yurunsoft indeed, I prefer also to use the latest version. however I can not just use `pecl install swoole` (I can not in this case specify the version in use).

In https://github.com/the-benchmarker/web-frameworks/pull/1578, I will have only one `Dockerfile` for all `php` **frameworks**, so it will be easier to update version

Regards,

**Comment by waghanza** [comment]
@Yurunsoft failing @https://travis-ci.com/the-benchmarker/web-frameworks/jobs/239707982

this is due to our tooling (`neph`), could you **rebase** ?

**Comment by Yurunsoft** [comment]
Why failed, what can I do?

**Comment by waghanza** [comment]
@Yurunsoft I don't know

when I use `php vendor/bin/imi server/start` (as **CMD** in `Dockerfile`) I have **App Inited**, but I do not have this message when I use  `php vendor/bin/imi server/start -name main`

**Comment by Yurunsoft** [comment]
You must run `composer update` to update the imi first

**Comment by waghanza** [comment]
@Yurunsoft I'm running on blank containers, why have I to `update` ? `install` is not enough ?

**Comment by Yurunsoft** [comment]
`php vendor/bin/imi server/start -name main` is the new mode. To use this mode, the system must support reuse port

**Comment by waghanza** [comment]
@Yurunsoft The system tested has this capability

**Comment by Yurunsoft** [comment]
I tested Swoole 4.4.1 and it seems that there are some bugs. The new mode of imi can't run in this version.

**Comment by waghanza** [comment]
I have made a **working `PR` https://github.com/Yurunsoft/web-frameworks/pull/1, please accept @Yurunsoft

**Pull request merged**
