### PR TITLE
Introduce prism

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` introduce `prism, following #184

@vladfaust I've taken inspiration from https://github.com/vladfaust/crystalworld/blob/master/src/bin/server.cr

Some results 

| Language (Runtime)        | Framework (Middleware)    |         Average |  50% percentile |  90% percentile |  99% percentile | 99.9% percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| crystal                   | spider-gazelle            | 6.98 ms | 5.98 ms | 12.26 ms | 20.77 ms | 48.21 ms | 4105.67 | 
| crystal                   | raze                      | 31.05 ms | 28.13 ms | 39.75 ms | 48.96 ms | 397.41 ms | 12629.00 | 
| crystal                   | prism                     | 32.67 ms | 30.29 ms | 44.19 ms | 53.70 ms | 448.97 ms | 16318.33 | 
| crystal                   | router.cr                 | 31.50 ms | 30.34 ms | 41.45 ms | 51.63 ms | 231.58 ms | 8655.33 | 
| crystal                   | amber                     | 35.06 ms | 31.27 ms | 48.80 ms | 57.24 ms | 216.02 ms | 10331.67 | 
| crystal                   | lucky                     | 35.78 ms | 36.07 ms | 42.52 ms | 52.85 ms | 260.01 ms | 9210.33 | 
| crystal                   | kemal                     | 41.41 ms | 40.96 ms | 51.34 ms | 86.50 ms | 576.08 ms | 24917.00 | 

Regards,

### CODE REVIEW

**Comment by vladfaust** [comment]
Nice! Thanks! However, I don't think that requiring master is a good idea. Could you please update version to `0.4.0-beta.3` for now? I'll send a PR when `0.4.0` is released!

**Comment by vladfaust** [comment]
I'm also amazed by the speed of @spider-gazelle. Is that because of clustering, @stakach?

**Comment by waghanza** [comment]
I can use beta version in `shard.yml`

**Comment by waghanza** [comment]
| Language (Runtime)        | Framework (Middleware)    |         Average |  50% percentile |  90% percentile |  99% percentile | 99.9% percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| crystal                   | spider-gazelle            | 7.10 ms | 6.28 ms | 11.74 ms | 19.84 ms | 41.01 ms | 3636.00 | 
| crystal                   | raze                      | 19.68 ms | 17.94 ms | 23.98 ms | 24.61 ms | 114.84 ms | 3594.33 | 
| crystal                   | router.cr                 | 20.01 ms | 19.44 ms | 24.12 ms | 24.94 ms | 236.71 ms | 6872.33 | 
| crystal                   | prism                     | 21.13 ms | 19.71 ms | 27.29 ms | 30.16 ms | 37.39 ms | 4219.33 | 
| crystal                   | kemal                     | 23.18 ms | 20.80 ms | 29.23 ms | 30.05 ms | 98.57 ms | 4669.33 | 
| crystal                   | lucky                     | 24.00 ms | 24.16 ms | 26.82 ms | 27.31 ms | 95.98 ms | 3348.67 | 
| crystal                   | amber                     | 24.44 ms | 25.47 ms | 29.01 ms | 29.61 ms | 165.05 ms | 4533.67 |

**Comment by waghanza** [comment]
@vladfaust yes, @stakach increased `spider-gazelle` performance amazingly, mainly with using all cores (I have a ratio of ~x3.5 for a quad-core)

**Pull request merged**
