### PR TITLE
Release for 6 of May 2024

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` updates results

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@trikko I updated to the last release, ` 0.7.5`, and I have 30Krps

**Comment by trikko** [comment]
Something is still not working properly, but...

**Comment by waghanza** [comment]
What is not working properly @trikko ?

**Comment by trikko** [comment]
Still too slow compared with my own benchmark across machines 🙂

**Comment by trikko** [comment]
I mean: relative speed vs others d frameworks speed

**Comment by waghanza** [comment]
Maybe then we should start investigating then, I mean create a separated PR if it is a matter of performance

**Pull request merged**
