### PR TITLE
New release for 15th of April 2024

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ serverino

@trikko @whiplash There is a compilation issue for last version
```d
16.35 /root/.dub/packages/serverino-0.7.0/serverino/source/serverino/daemon.d(491,61): Error: no property `release` for type `std.socket.Socket`
16.36 /root/.dub/packages/serverino-0.7.0/serverino/source/serverino/main.d(187,59): Error: template instance `serverino.daemon.Daemon.wake!(app)` error instantiating
16.36 /root/.dub/packages/serverino-0.7.0/serverino/source/serverino/main.d(158,14):        instantiated from here: `wakeServerino!(app)`
```
+ laravel-s-laravel
+ laravel-s-lumen
+ antidot
+ comet

### CODE REVIEW

**Comment by trikko** [comment]
Are you using a old version of d compiler, aren't you?

**Comment by trikko** [comment]
Pretty old. Probably you want to download an archive from there:

https://github.com/ldc-developers/ldc/releases/tag/v1.37.0

**Comment by waghanza** [comment]
could you create a PR @whiplash ?

**Comment by trikko** [comment]
Not updated, I guess.

But that archive just need to be unzipped somewhere.

You can also use your current dub version, I guess like this:

`dub --compiler=/path/to/bin/ldc --build=release ... etc...`

**Comment by waghanza** [comment]
ok. we need to update all d based frameworks then

**Pull request merged**
