### PR TITLE
New release - 04112024

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ act
+ chubbyts-uwebsockets
+ low-http-server
+ oak-bun
+ oak-deno
+ spliffy
+ turbo

@donywan for bun, I have
```
bun run root@4264daf7dd61:/usr/src/app# bun app.ts
error: Cannot find module '@oak/oak' from '/usr/src/app/app.ts'

Bun v1.1.34 (Linux arm64)
```

for deno
```
root@e03514a217e3:/usr/src/app# deno run app.ts
error: Could not resolve "@oak/oak", but found it in a package.json. Deno expects the node_modules/ directory to be up to date. Did you forget to run `deno install`?
    at file:///usr/src/app/app.ts:1:37
root@e03514a217e3:/usr/src/app# deno install
error: npm package '@jsr/oak__oak' does not exist.
root@e03514a217e3:/usr/src/app#
```

### CODE REVIEW

**Comment by donywan** [comment]
I used jsr. https://jsr.io/@oak/oak

**Comment by waghanza** [comment]
Yes, seems to work locally, but not inside the container @donywan 

When login onto the container, and trying `deno run app.ts`, I have
```
error: Could not resolve "@oak/oak", but found it in a package.json. Deno expects the node_modules/ directory to be up to date. Did you forget to run `deno install`?
    at file:///usr/src/app/app.ts:1:37
```
and `deno install` leads to 
```
error: npm package '@jsr/oak__oak' does not exist.
```

**Comment by donywan** [comment]
> Yes, seems to work locally, but not inside the container @donywan
> 
> When login onto the container, and trying `deno run app.ts`, I have
> 
> ```
> error: Could not resolve "@oak/oak", but found it in a package.json. Deno expects the node_modules/ directory to be up to date. Did you forget to run `deno install`?
>     at file:///usr/src/app/app.ts:1:37
> ```
> 
> and `deno install` leads to
> 
> ```
> error: npm package '@jsr/oak__oak' does not exist.
> ```

Try deleting the `oak` dependency in `package.json`.

**Comment by donywan** [comment]
@waghanza  `deno.json`
```
{
  "imports": {
    "@oak/oak": "jsr:@oak/oak@^17.1.3"
  }
}
```

**Comment by waghanza** [comment]
Needs a package.json and a deno.json ?

**Comment by donywan** [comment]
> Needs a package.json and a deno.json ?

Needs `deno.json`.
The latest version of `oak` in the current npm repository is 14.1.0. https://www.npmjs.com/package/@oakserver/oak.So you need to use jsr to install dependencies.

**Pull request merged**
