### PR TITLE
[Java] Disable logging

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` disable logging on all `java` frameworks.

Logging is disabled for :

+ [x] act
+ [x] blade
+ [x] javalin
+ [x] jooby
+ [x] micronaut
+ [x] rapidoid
+ [x] spring-boot
+ [x] spring-framework
+ [x] struts2

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@greenlaw110 @whiplash @biezhi @tipsy @jknack @graemerocher @ilopmar @JasonTypesCodes @nmihajlovski @wilkinsona @sbrannen @lukaszlenart How can we disable  logging feature ?

**Comment by lukaszlenart** [comment]
@waghanza see #3056

**Comment by waghanza** [comment]
@tipsy How can I disable logging for `javalin` ?

-----------

@sbrannen @snicoll @bclozel How can I disable logging for `spring-framework` ?

-----------

@nmihajlovski How can I disable logging for `rapidoid` ?

**Comment by snicoll** [comment]
@waghanza please stop mentioning us please. That was indicated to [you previously by Brian](https://github.com/the-benchmarker/web-frameworks/issues/3088#issuecomment-656097279).

**Comment by waghanza** [comment]
Sorry @snicoll, I though the above comment was unclear, so hard to understand why you were pinged. I did not notice, I can not ask for help.

**Review by lukaszlenart — APPROVED** [review]
LGTM 👍

**Pull request merged**
