### PR TITLE
chubbyphp-workerman

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by waghanza** [comment]
Failing at https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/369999957. I suspect there is a multiprocessing involved. Need to investigate, `docker` does not like that (same thing when using **prefork** in `go`)

**Comment by dominikzogg** [comment]
@waghanza i used the wrong port (8080 instead of 3000), sorry for that

**Comment by waghanza** [comment]
Ah ok, it is not the problem I thought 😛 

------

Note that the results will **NOT** be updated this month

**Comment by dominikzogg** [comment]
thx

**Pull request merged**
