### PR TITLE
Use monospaced font for easier result comparison

### PR DESCRIPTION
**Pull request by vfonic**
You could consider adding this to all the other results as well. :)

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks @vfonic. This is a good idea. However, your change is not at the right place.

Results in the README are overwritten by our custom tool.

I'll modify you're code to add emphasis / bold / backtics were it could help

:tada:

**Comment by vfonic** [comment]
That's even better! :)

Didn't know the Readme was being generated. 

Thanks for this project!
/I'm gonna close this, as it's not going to be merged for obvious reasons. :)

**Comment by waghanza** [comment]
no, I'll update your `PR`

acting like that (modifying you `PR`), will help me when releasing,  I'll add you in the changelog

**Comment by waghanza** [comment]
@vfonic I've update this `PR`, the source file (`tools/src/benchmarker.cr`) overwitte result

**Comment by vfonic** [comment]
Thanks!

Looks good to me. :)

I want to avoid going through the whole process of installing crystal for this, so feel free to go ahead and merge this whenever you feel like.

**Pull request merged**
