### PR TITLE
New release - 11112024

### LINKED ISSUE #7881: recommendations for D2
https://github.com/the-benchmarker/web-frameworks/blob/5106b0f35af4a66a7f2c7dc603739d99300c98aa/perl/dancer2/cpanfile#L5-L12

See https://metacpan.org/dist/Dancer2/view/lib/Dancer2/Manual/Deployment.pod#Performance-Improvements

### PR DESCRIPTION
**Pull request by waghanza**
Closes #7881

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks @SysPete for the tips

**Comment by waghanza** [comment]
@donywan I've fixed oak for bun, bun not sure if this implementation use multicore like pm2 for node

**Comment by waghanza** [comment]
I can't use oaf for deno
`deno add @oak/oak` leads to
```
error: @oak/oak is missing a prefix. Did you mean `deno add jsr:@oak/oak`?
```

and `deno add jsr:@oak/oak`

leads to 
```
error: npm package '@jsr/oak__oak' does not exist.
```

**Comment by waghanza** [comment]
@jkyberneees @schamberg97 `low-http-server` is not complinat with latest LTS of nodejs. do you plan to update ?

**Comment by jkyberneees** [comment]
Thanks @waghanza for reporting. New version is now released with the latest version of uWebSocket.js. 

Regards

**Pull request merged**
