### PR TITLE
[Scala] Disable logging

### PR DESCRIPTION
**Pull request by whiplash**
Not sure why It also added changes I did not make. But anyways, I've added `logback.xml` to Play file and set it to shut off logging

### CODE REVIEW

**Comment by waghanza** [comment]
> Not sure why It also added changes I did not make

Since this `PR` target **master**, not the branch you create this `PR` from 😛

**Review by waghanza — COMMENTED** [review]
Thanks @whiplash. 

However, I can see only `play` here. Are `http4s` and `akkahttp` already silent ?

**Comment by whiplash** [comment]
My bad. Yeah, this is only Play

**Comment by waghanza** [comment]
Please ping me when ready @whiplash

**Pull request closed without merging**
