### PR TITLE
update act to 1.8.11

### PR DESCRIPTION
**Pull request by greenlaw110**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [x] Please check configuration files
   + [x] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [x] `FRAMEWORKS.yml`, for **frameworks** list
   + [x] `travis.yml`, for CI
+ [x] A `Dockerfile` exists ?
+ [x] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~

### CODE REVIEW

**Comment by waghanza** [comment]
@greenlaw110 with which `jdk` version `act` is compatible (it seems not to work with `jdk` `12`) ?

**Comment by greenlaw110** [comment]
@waghanza act supports jdk7 and jdk8 only

**Comment by waghanza** [comment]
@greenlaw110 any port to **jdk** `12` ?

**Comment by greenlaw110** [comment]
@waghanza not at the moment. Act relies on ASM 5, there will be quite a lot of work to port it to high version of JDK. I will probably start the work somewhere next year. However JDK 12 is unlikely the target, instead my target is JDK 11 LTS

**Comment by waghanza** [comment]
@greenlaw110 ok, not aware that the was `LTS` in `jdk` now :stuck_out_tongue:

**Pull request merged**
