### PR TITLE
Update swoole config

### PR DESCRIPTION
**Pull request by sy-records**
#### Tasks

+ Set worker number to `swoole_cpu_num() * 2`
+ Disable coroutine
+ Disable logs

#### Frameworks

+ [x] chubbyphp-swoole
+ [x] hyperf
+ [x] imi
+ [x] one
+ [x] siler-swoole
+ [x] simps
+ [x] slim-swoole
+ [x] sw-fw-less
+ [x] swoft
+ [x] yii-swoole

### CODE REVIEW

**Comment by sy-records** [comment]
simps in #3783

**Review by dominikzogg — DISMISSED** [review]

**Review by leocavalcante — APPROVED** [review]

**Comment by waghanza** [comment]
I can see that `yii` use **SWOOLE_PROCESS** and the others **SWOOLE_BASE**. I think we should use **SWOOLE_BASE** everywhere

**Comment by sy-records** [comment]
yes




------------------ Original ------------------

**Comment by waghanza** [comment]
@Yurunsoft May I notify you on each update that can affect `imi` ?
@lizhichao May I notify you on each update that can affect `one` ?
@luoxiaojun1992  May I notify you on each update that can affect  `sw-fw-less` ?
@samdark @cebe @qiangxue May I notify you on each update that can affect  `yii` ?

**Comment by waghanza** [comment]
I see that `yii` use ** SWOOLE_SOCK_TCP**, what does this option mean for `swoole` ?

**Comment by sy-records** [comment]
sock_type https://www.swoole.co.uk/docs/modules/swoole-server-construct

**Comment by waghanza** [comment]
Is this not "unfair" to have it only for `yii` ?

**Comment by sy-records** [comment]
There's nothing wrong with this.

**Comment by waghanza** [comment]
This line seems weird https://github.com/the-benchmarker/web-frameworks/pull/3786/checks?check_run_id=1713645781#step:6:1440

**Comment by luoxiaojun1992** [comment]
> @luoxiaojun1992 May I notify you on each update that can affect `sw-fw-less` ?

Yes.

**Comment by leocavalcante** [comment]
@waghanza @sy-records what do you think about a pure Swoole implementation serving as a reference for both the performance benchmark (how much Swoole based frameworks overheads the pure Swoole) as also as configuration reference (new Swoole-based frameworks should be PRed following the explicit configs of the pure implementation).

**Comment by cebe** [comment]
> @cebe May I notify you on each update that can affect `yii` ?

@waghanza yes

**Pull request merged**
