### PR TITLE
Add OSX support

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` adds `OSX` support

:warning: If you are not using a **linux** `distro`, you **MUST** :
+ have `docker-machine` (:information_source: available via `brew` for `OSX`)
+ use `bin/make config --driver docker-machine`
+ create a docker machine `docker-machine create the-benchmarker`
+ has a `DOCKER_HOST` defined `eval $(docker-machine env default)`

This is not the main `development workflow`, then any help maintaining `OSX` is :heart: 

------------------
Closes #2587

### CODE REVIEW

**Comment by waghanza** [comment]
@whiplash Tested on `catalina`

**Comment by whiplash** [comment]
Little note: what you call OSX is actually called `macOS`.

**Comment by whiplash** [comment]
Ok. What should I be doing exactly to run a framework?

**Comment by waghanza** [comment]
+ Add an implementation
+ Create a `config.yaml`
+ Create a `Dockerfile` (:warning: for **new** languages)
+ Add in `.travis.yml`
+ Add in `.dependabot/config.yml` (in accurate)

Could you create any `PR` from a **non-master** branch ? I can modify them (if you min) :heart:

**Comment by whiplash** [comment]
Ok.
I'll try and run both Scala things before creating new implementations.

**Comment by whiplash** [comment]
I might be missing something. Still doesn't work: https://gist.github.com/whiplash/e0f7c944463c01dee23b839946035181

**Pull request merged**
