### PR TITLE
Added uWebSocketjs server in routejs

### PR DESCRIPTION
**Pull request by rajkumardusad**
Added uWebSocketjs server in routejs

### CODE REVIEW

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
Results are updated https://web-frameworks-benchmark.netlify.app/result?l=javascript

**Comment by rajkumardusad** [comment]
> Results are updated https://web-frameworks-benchmark.netlify.app/result?l=javascript

Thank you, now routejs is the second fastest framework for javascript

**Comment by waghanza** [comment]
with the caveat (or not) that will decrease when the time will be to have a _full stack_ implementation :-)

**Comment by rajkumardusad** [comment]
> with the caveat (or not) that will decrease when the time will be to have a _full stack_ implementation :-)

Yes and im working on it :-)

**Pull request merged**
