### PR TITLE
Introduce scotty

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` introduce [scotty](https://github.com/scotty-web/scotty).

@chessai @RyanGlScott do you consent to include `scotty` here ?

Regards,

### CODE REVIEW

**Comment by chessai** [comment]
What is the purpose of this PR? And what is all this styling?

**Comment by waghanza** [comment]
Hi @chessai,

The purpose of this `PR` is to introduce `scotty` here, at least if you are not opposed.

The styling `PR` was  try, since I want to keep code style uniform here. For **Haskell**,  `ormolu` is used.

Regards,

**Comment by chessai** [comment]
Sure, I consent to scotty being included here. Thanks for asking.

Do note that while I think it's a good idea for completeness; scotty is probably pretty slow, since its a library intended for ease of use/learning, and not really for high-scale production.

**Comment by waghanza** [comment]
@chessai Sure, the main indicator is performance, but as their is plenty of implementations here, users could appreciate the learning curve also ;-)

**Comment by chessai** [comment]
Awesome! Well, thanks for making me aware of this cool project!

**Pull request merged**
