### PR TITLE
[Release] 17.04.2023

### PR DESCRIPTION
**Pull request by waghanza**
#### Failing frameworks

+ archttp
+ nawa
+ masonite

### CODE REVIEW

**Comment by waghanza** [comment]
@dominikzogg have you tried the latest `roadrunner`, seems that the latest version does not provider `bin` directory
```php
/usr/src/app # ls vendor/bin
ls: vendor/bin: No such file or directory
```

**Comment by dominikzogg** [comment]
@waghanza I tested the following without any issue on my machine:

```sh
cd ~/Projects/the-benchmarker/web-frameworks/php/chubbyphp-roadrunner
composer install
./vendor/bin/rr get-binary
./rr serve
```

**Comment by waghanza** [comment]
in this branch @dominikzogg ? I've deployed a fix :-) now `roadrunner` binary could be installed via `roadrunner-cli` package

**Comment by waghanza** [comment]
I have an error on `masonite` @josephmancuso 
With the following docker file
```dockerfile
FROM python:3.11-slim

WORKDIR /usr/src/app

RUN apt-get -qq update
RUN apt-get -qy install build-essential

  RUN apt-get  -qy install libffi-dev
  RUN apt-get  -qy install curl
  RUN apt-get  -qy install libssl-dev

COPY . ./



RUN pip install -r requirements.txt

CMD gunicorn  \
  --log-level warning  \
  --bind 0.0.0.0:3000  \
  --reuse-port  \
  --workers $(nproc)  \
  --worker-class gevent \
    wsgi:application
```
I have the following error
```python
root@c60b49aa8745:/usr/src/app# gunicorn wsgi:application
[2023-04-16 21:01:34 +0000] [8] [INFO] Starting gunicorn 20.1.0
[2023-04-16 21:01:34 +0000] [8] [INFO] Listening at: http://127.0.0.1:8000 (8)
[2023-04-16 21:01:34 +0000] [8] [INFO] Using worker: sync
[2023-04-16 21:01:34 +0000] [9] [INFO] Booting worker with pid: 9
[2023-04-16 21:01:34 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/wsgi.py", line 1, in <module>
    from masonite.foundation import Application, Kernel
  File "/usr/local/lib/python3.11/site-packages/masonite/foundation/__init__.py", line 2, in <module>
    from .Kernel import Kernel
  File "/usr/local/lib/python3.11/site-packages/masonite/foundation/Kernel.py", line 35, in <module>
    from ..middleware import MiddlewareCapsule
  File "/usr/local/lib/python3.11/site-packages/masonite/middleware/__init__.py", line 13, in <module>
    from .route.ThrottleRequestsMiddleware import ThrottleRequestsMiddleware
  File "/usr/local/lib/python3.11/site-packages/masonite/middleware/route/ThrottleRequestsMiddleware.py", line 4, in <module>
    from attr import has
ModuleNotFoundError: No module named 'attr'
[2023-04-16 21:01:34 +0000] [9] [INFO] Worker exiting (pid: 9)
[2023-04-16 21:01:34 +0000] [8] [INFO] Shutting down: Master
[2023-04-16 21:01:34 +0000] [8] [INFO] Reason: Worker failed to boot.
```

**Comment by dominikzogg** [comment]
@waghanza its the same within the update branch. All worked as before on my machine.

**Pull request merged**
