### PR TITLE
Update GF from v1.4.7 to v1.5.2

### PR DESCRIPTION
**Pull request by johngcn**
This PR updates golang webframework `GF` from `v1.4.7` to `v1.5.0`.

### CODE REVIEW

**Comment by waghanza** [comment]
@johngcn can you unlock **master** for me, in you fork http://github.com/johngcn/web-frameworks, the code is good but git history will be a mess (due to several merges)

**Comment by johngcn** [comment]
@waghanza OK, but I've no idea how to unlock it. I'll figure it out.

**Comment by waghanza** [comment]
@johngcn it appears I can (I think), could I do some nasty things on your fork (some hard reset) ?

**Comment by johngcn** [comment]
@waghanza Well, just go ahead! 😄

**Comment by waghanza** [comment]
@johngcn I think I have some learning to do :stuck_out_tongue:, I've opened #935 in order to keep a git history clean

**Pull request closed without merging**
