### PR TITLE
Patch meiheld

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

Following https://github.com/bottlepy/bottle/issues/1091, this `PR` patch `meinheld`.

Thanks @agalera :tada: 

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
I use this feature also for `flask`

| Framework (Middleware)    |         Average |  50% percentile |  90% percentile |  99% percentile | 99.9% percentile | Standard deviation |Requests / s |      Throughput |
|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|---------:|
| bottle (unpatched)                   | 22.18 ms | 18.03 ms | 37.88 ms | 75.21 ms | 324.32 ms | 15796.33 |48441.00 | 119.39 MB |
| flask  (unpatched)                   | 52.62 ms | 37.67 ms | 110.96 ms | 158.00 ms | 632.17 ms | 41189.67 | 20414.67 | 50.18 MB |
| bottle (patched)                   | 21.00 ms | 13.69 ms | 41.86 ms | 90.58 ms | 282.19 ms | 18187.67 | 53832.67 | 132.67 MB |
| flask  (patched)                   | 54.46 ms | 38.40 ms | 109.36 ms | 166.15 ms | 394.67 ms | 36173.33 |19572.00 | 48.09 MB |

For `bottle` this patch is :tada: but not sure if `flask` should be **patched**

**Comment by waghanza** [comment]
@agalera @benoitc any idea about the performance diff ? any help will be :heart:

**Comment by agalera** [comment]
in bottle should not be patched for errors in the response.
Bottle is much faster than Flask, this is normal.

If you want to improve the performance by returning answers in json format, you can install ```ujson``` is an optional requirement that makes bottle serialize much faster.

@defnull maybe I can contribute something more

**Comment by defnull** [comment]
Bottle is a lot faster than flask, this is also visible in other benchmarks. And yes, `ujson` is automatically picked up, if present, and used for faster json processing. That's a cheap boost for json-heavy APIs.

I'm not sure if this would be fair in a benchmark, though. Bottle is advertised as a zero-dependency framework, after all. And already faster than most ;)

**Comment by waghanza** [comment]
@defnull Why ? `Flask` and `bottle` are **python** framework and their are running **both** under `gunicorn` and `meinheld`

**Comment by waghanza** [comment]
@agalera In fact, we wan this **benchmark** as _simple_ as possible, as for now we are just using 3 rules, see https://github.com/the-benchmarker/web-frameworks/issues/221#issue-328459520

**Comment by defnull** [comment]
Look at `Bottle._cast` for example: https://github.com/bottlepy/bottle/blob/master/bottle.py#L1028
It's a mess, way too long, complicated and full of hacks, but it's fast.
In Flask/Werkzeug, the same functionality is probably spread across multiple modules, and requires dozens of classes, method calls, wrappers and computed properties. 

Or `cached_property()`: https://github.com/bottlepy/bottle/blob/master/bottle.py#L234
It's a computed property that replaces itself with the value, once computed, so Python can find it in `__dict__` and won't bother executing the property again. It's a small detail, but when you try to process 3k requests per second, not having to parse a header multiple times pays off.

**Comment by waghanza** [comment]
I understand the performance gap, but it's always useful to have some figures.

**Pull request merged**
