### PR TITLE
[Release] Update on 15th of May 2023

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ [ ] archttp
+ [ ] scorper

@bung87 I have a compilation error with `scorper`
```nim
/tmp/nimble_1/githubcom_bung87scorper_1.1_1.2/src/scorper/http/streamserver.nim(395, 26) Error: ambiguous identifier: 'Time' -- use one of the following:
  posix.Time: Time
  times.Time: Time
    Prompt: Build failed for 'scorper@1.1.0', would you like to try installing 'scorper@#head' (latest unstable)? -> [forced yes]
Downloading https://github.com/bung87/scorper using git
       Tip: 715 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_1/githubcom_bung87scorper_#head/scorper.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /tmp/nimble_1/githubcom_bung87scorper_#head/scorper.nimble(61, 1) Error: undeclared identifier: 'taskRequires'
        ... candidates (edit distance, scope distance); see '--spellSuggest':
        ...  (4, 2): 'requires' [proc declared in /nim/lib/system/nimscript.nim(449, 8)]
        ...  (4, 2): 'requires' [proc declared in /tmp/nimblecache-0/nimscriptapi_38591525.nim(46, 6)]
        ... printPkgInfo() failed.
The command '/bin/sh -c nimble install -y' returned a non-zero code: 1
```
Dockerfile is 
```dockerfile
FROM nimlang/nim:1.6.12-alpine

RUN apk update && \
    apk upgrade --no-cache


WORKDIR /usr/src/app

COPY . ./

ENV PATH $PATH:/root/.nimble/bin

RUN nimble install -y

  RUN nim c  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim

FROM alpine

WORKDIR /usr/src/app

RUN apk update && \
    apk upgrade --no-cache

RUN apk --no-cache add openssl-dev pcre-dev

  COPY --from=0 /usr/src/app/server /usr/src/app/server

  CMD /usr/src/app/server
```

### CODE REVIEW

**Comment by bung87** [comment]
my mistake, should verify it locally, seems like need wait for nim new release.

**Comment by waghanza** [comment]
as I understand, this compilation error does not exist on development version, but only stable nim. then we should wait a bit.

I'll revert upgrade @bung87. 

feel free to push a PR for update when nim 1.6.14 will be out

**Comment by waghanza** [comment]
Even with 1.0, I have
```nim
/tmp/nimble_1/githubcom_bung87scorper_1.0_1.1/src/scorper/http/streamserver.nim(397, 26) Error: ambiguous identifier: 'Time' -- use one of the following:
  posix.Time: Time
  times.Time: Time
    Prompt: Build failed for 'scorper@1.0.27', would you like to try installing 'scorper@#head' (latest unstable)? -> [forced yes]
Downloading https://github.com/bung87/scorper using git
       Tip: 715 messages have been suppressed, use --verbose to show them.
     Error: Could not read package info file in /tmp/nimble_1/githubcom_bung87scorper_#head/scorper.nimble;
        ...   Reading as ini file failed with:
        ...     Invalid section: .
        ...   Evaluating as NimScript file failed with:
        ...     /tmp/nimble_1/githubcom_bung87scorper_#head/scorper.nimble(61, 1) Error: undeclared identifier: 'taskRequires'
        ... candidates (edit distance, scope distance); see '--spellSuggest':
        ...  (4, 2): 'requires' [proc declared in /nim/lib/system/nimscript.nim(449, 8)]
        ...  (4, 2): 'requires' [proc declared in /tmp/nimblecache-0/nimscriptapi_38591525.nim(46, 6)]
        ... printPkgInfo() failed.
The command '/bin/sh -c nimble install -y' returned a non-zero code: 1
```


I will publish results for tomorrow, feel free to fix `scorper` next week @bung87

**Comment by bung87** [comment]
I've fixed the issue, now mainly aim for nim stable.

**Comment by waghanza** [comment]
on **alpine**, I have 
```nim
/usr/src/app # nim c  --excessiveStackTrace:off -d:release --opt:speed --passC:-flto --passL:-flto server.nim
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: used config file '/nim/config/config.nims' [Conf]
...........................................................................................................
/root/.nimble/pkgs/chronos-3.1.0/chronos/selectors2.nim(298, 12) Error: undeclared identifier: 'sigprocmask'
candidates (edit distance, scope distance); see '--spellSuggest':
 (6, 6): 'EINPROGRESS' [const declared in /root/.nimble/pkgs/chronos-3.1.0/chronos/oserrno.nim(1274, 5)]
 (6, 6): 'EINPROGRESS' [const declared in /root/.nimble/pkgs/chronos-3.1.0/chronos/oserrno.nim(1274, 5)]
 (6, 6): 'EINPROGRESS' [const declared in /root/.nimble/pkgs/chronos-3.1.0/chronos/oserrno.nim(1274, 5)]
 (6, 6): 'SIG_BLOCK' [const declared in /nim/lib/posix/posix_linux_amd64_consts.nim(403, 7)]
 (6, 6): 'SIG_BLOCK' [const declared in /nim/lib/posix/posix_linux_amd64_consts.nim(403, 7)]
 (6, 6): 'procCall' [proc declared in /nim/lib/system.nim(2965, 6)]
```

and the dockerfile is
```dockerfile

FROM nimlang/nim:1.6.12-alpine

RUN apk update && \
    apk upgrade --no-cache


WORKDIR /usr/src/app

  COPY 'server.nim' 'server.nim'
  COPY 'server.nimble' 'server.nimble'

ENV PATH $PATH:/root/.nimble/bin

  RUN nimble install -y
```
@bung87

**Pull request merged**
