### PR TITLE
[PHP] Optimize one settings

### PR DESCRIPTION
**Pull request by lizhichao**

### CODE REVIEW

**Comment by lizhichao** [comment]
> Can you explain this figures ?

figures ？ 
I am re-forked from the the-benchmarker/web-frameworks
modifying the configuration for one.

**Comment by waghanza** [comment]
I mean, why :

+ 2 workers per cores `worker_num`
+ No delay for TCP `open_tcp_nodelay`
+ Fast open TCP `tcp_fastopen`
+ **100000** for max coroutines `max_coroutine`

Regards,

**Comment by lizhichao** [comment]
One can support fpm run and run based on swoole. The one I submitted is based on swoole running. These several parameters are the parameters of the swoole. 
Https://www.swoole.co.uk/docs/modules/swoole-server-methods#swoole_server-set

**Comment by lizhichao** [comment]
One can support fpm run and run based on swoole. The one I submitted is the same as hyperf imi swoft based on swoole. These several parameters are the parameters of the swoole. 
Configuration instructions ： 
Https://www.swoole.co.uk/docs/modules/swoole-server-methods#swoole_server-set

**Pull request merged**
