### PR TITLE
Update Bocadillo version in README

### PR DESCRIPTION
**Pull request by florimondmanca**
The version went out of sync with what is being tested by the benchmarking suite. :-)

### CODE REVIEW

**Comment by waghanza** [comment]
good catch :tada: 

however, the version is stored in `FRAMEWORKS.yml` :stuck_out_tongue:

**Comment by florimondmanca** [comment]
Duh 😄 Will fit it tomorrow hopefully!

**Comment by waghanza** [comment]
I'm on it

**Comment by florimondmanca** [comment]
All good then! 👍

**Pull request merged**
