### PR TITLE
[Go] Add Goyave

### LINKED ISSUE #2647: Introduce goyave
Hi @System-Glitch,

Would you mind to add (or consent that we add) [goyave](https://github.com/System-Glitch/goyave) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

### PR DESCRIPTION
**Pull request by System-Glitch**
Added [Goyave](https://github.com/System-Glitch/goyave/).

Closes #2647

### CODE REVIEW

**Review by waghanza — CHANGES_REQUESTED** [review]

**Review by waghanza — COMMENTED** [review]
seems that the server is unreachable https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/386491970#L425

**Comment by System-Glitch** [comment]
How does `benchmark_spec.cr` find the URI? I tried to dig in the code but couldn't find what the problem is.

**Comment by waghanza** [comment]
> I think it doesn't work because the Dockerfile doesn't copy the configuration file (config.json)

Seems to, let me check

> How can we make a patch in the dockerfile to fix that?

Not sure. Let me add some commits on your branch. I don't remember any `go` frameworks that requiresd a config file to work, so I do not work in this direction

**Comment by System-Glitch** [comment]
I think I fixed it by adding `files: - config.json`to `config.yaml`. You should be allowed to add commits to my branch.

**Comment by waghanza** [comment]
Ok, this file is need at runtime, and not compile. 🎉

**Pull request merged**
