### PR TITLE
PHP // Sunrise Router // PHP8 support

### PR DESCRIPTION
**Pull request by fenric**

### CODE REVIEW

**Review by waghanza — CHANGES_REQUESTED** [review]
Need also to update `config.yaml`

**Comment by fenric** [comment]
> Need also to update `config.yaml`

ready. I forgot :) thx!

**Comment by waghanza** [comment]
Need also https://github.com/the-benchmarker/web-frameworks/blob/c82fe09f9c163bcabe47d5d19750640485dda7ac/php/sunrise-router-roadrunner/composer.json#L4

**Review by waghanza — APPROVED** [review]

**Comment by fenric** [comment]
> Need also to update

it looks like something went wrong ...

https://github.com/the-benchmarker/web-frameworks/pull/3654/files

I just merged updates from the master branch... can I open a new PR?)))

**Pull request merged**
