### PR TITLE
[PHP] Introduce phalcon

### LINKED ISSUE #1818: Add Phalcon
+ Language : PHP
+ Repo : https://github.com/phalcon/cphalcon
+ Author : Phalcon

### PR DESCRIPTION
**Pull request by waghanza**
Hi @andresgutierrez @niden @sjinks @ruudboon,

This `PR` adds `phalcon` in `here`.

Could you check this codebase, please ?

The purpose is to have the minimum implementation responding to our scenario.

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

----------------------------------
Closes #1818

### CODE REVIEW

**Comment by ruudboon** [comment]
```php
<?php

use Phalcon\Mvc\Micro;

$app = new Micro();

$app->get(
    '/',
    function () use ($app) {
        $response = $app->response;
        $response->setStatusCode(200, "OK");
        $response->setContent("");

        return $response;
    }
);

$app->get(
    '/user/{id}',
    function ($id) use ($app) {
        $response = $app->response;
        $response->setStatusCode(200, "OK");
        $response->setContent($id);

        return $response;
    }
);

$app->post(
    '/user',
    function () use ($app) {
        $response = $app->response;
        $response->setStatusCode(200, "OK");
        $response->setContent("");

        return $response;
    }
);


$app->handle(
    $_SERVER["REQUEST_URI"]
);

```

**Comment by waghanza** [comment]
@ruudboon Thanks for your advice, however the gap seems not to be so huge.

For example, with an `Intel(R) Core(TM) i3-7020U CPU @ 2.30GHz` (**4** CPU / **8** Go) I have


|  | Average | 50th percentile | 90th percentile | Standard deviation | Requests / s | Throughput |
|-------|--------:|------------:|--------:|---------:|-------:|----|
| full stack | **111.99** ms | 20.25 ms | 385.43 ms | 281967.67 | 23858.00 | 7.14 Mb |
| micro | **115.52** ms | 20.23 ms | 375.76 ms | 317749.33 | 24426.00 | 7.30 Mb |

:information_source: OK, my `CPU` is not what you use on **real-world** servers :information_source:

**Comment by ruudboon** [comment]
@waghanza Hmm interesting results. Is there a way to run your Phalcon test standalone? Would love to check if we can improve it even more.

**Comment by waghanza** [comment]
sure, sorry the documentation could be unclear :stuck_out_tongue: 
actually, I've merged this into **master**, so to test `phalcon` their is the way to do so :
1. Install `crystal` => https://crystal-lang.org/install
2. Install https://github.com/wg/wrk :warning: I use the last **tag**
3. Install `docker`
4. Clone this repository
5. Run
~~~sh
shards install
shards build
bin/make
bin/neph phalcon
rm -fr data;db
bin/db init
bin/db to_readme > README.md
~~~
6. Check results in `README.md` (using https://github.com/joeyespo/grip or else)

It's a pleasure to me you check those results, let me know if you have an issue @ruudboon

**Pull request merged**
