### PR TITLE
New release on 29072024

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing

+ [x] act
+ [x] turbo
+ [x] guildenstern
+ [x] coresky
+ [x] bottle
+ [x] happyxpy
+ [x] akkahttp

### CODE REVIEW

**Comment by waghanza** [comment]
solved for `akkahttp` @whiplash with https://doc.akka.io/docs/akka-http/current/introduction.html

but not sure to understand why I can use 2.9.4 of `akka` for an http impl

**Comment by waghanza** [comment]
@olliNiinivaara @dom96 @ire4ever1190 for https://github.com/olliNiinivaara/GuildenStern, I have a compilation error on ARM (ac M1)


```nim
 => ERROR [stage-0 8/8] RUN nim c  -d:release --opt:speed      --assertions:off     --warnings:off     --hints:off     -d:release     --opt:speed     --passC:-flto   0.6s
------ 
 > [stage-0 8/8] RUN nim c  -d:release --opt:speed      --assertions:off     --warnings:off     --hints:off     -d:release     --opt:speed     --passC:-flto     --passL:-flto     server.nim:
0.566 /home/nim/.nimble/pkgs2/guildenstern-7.1.0-5f4b081c4eb9912d5e57ddd21483e42c679642fe/guildenstern/httpresponse.nim(7, 23) Error: cannot evaluate at compile time: MSG_NOSIGNAL
```

any idea ?

**Comment by waghanza** [comment]
@greenlaw110  for `act`, I have
```java
root@17005d22cb8f:/opt/web# /opt/web/run
  _    _         _                    _                  _  ___
 |_)  |_  |\ |  /   |_|  |\/|   /\   |_)  |/  __   /\   /    |
 |_)  |_  | \|  \_  | |  |  |  /--\  | \  |\      /--\  \_   |

                            powered by ActFramework r1.9.2-c4fe6

 version: unknown
scan pkg: benchmark.act
base dir: /opt/web
     pid: 12
 profile: prod
    mode: PROD
      OS: Linux
     jdk: OpenJDK 64-Bit Server VM 11

     zen: 1. Avoid premature distribution.
          2. Avoid premature abstraction.

          Both offer a lure of purity, cleanliness and scalability but add complexity and operational/cognitive overhead.

                                                                                                                   -  Karl Isenberg

Exception in thread "main" java.lang.IllegalArgumentException
        at act.asm.ClassReader.<init>(ClassReader.java:170)
        at act.asm.ClassReader.<init>(ClassReader.java:153)
        at act.app.AppClassLoader.scanByteCode(AppClassLoader.java:314)
        at act.app.AppClassLoader.scan(AppClassLoader.java:266)
        at act.app.App.scanAppCodes(App.java:1868)
        at act.app.App.refresh(App.java:783)
        at act.app.AppManager.load(AppManager.java:77)
        at act.app.AppManager$_F$1.visit(AppManager.java:145)
        at act.app.AppManager$_F$1.visit(AppManager.java:141)
        at org.osgl.Lang$Visitor.apply(Lang.java:2462)
        at org.osgl.Lang$Visitor.apply(Lang.java:2452)
        at act.app.AppScanner.scan(AppScanner.java:91)
        at act.app.AppScanner.scan(AppScanner.java:71)
        at act.app.AppManager.loadSingleApp(AppManager.java:55)
        at act.Act.startup(Act.java:338)
        at act.Act.startup(Act.java:1322)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.osgl.Lang.invokeStatic(Lang.java:8150)
        at act.Act.bootstrap(Act.java:1221)
        at act.Act.start(Act.java:703)
        at benchmark.act.AppEntry.main(AppEntry.java:29)
```

when running on ARM (mac M1)

**Comment by waghanza** [comment]
@energy-coresky On ARM (M1), `main/warmcache.php` returns a 255 error code

**Comment by waghanza** [comment]
@kernelsauce I have an error with `turbo`

```
/usr/src/app # luajit server.lua
luajit: /usr/local/share/lua/5.1/turbo/util.lua:98: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/turbo/util.lua:98: in function </usr/local/share/lua/5.1/turbo/util.lua:97>
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo/web.lua:37: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo.lua:110: in main chunk
        [C]: in function 'require'
        server.lua:1: in main chunk
        [C]: at 0xaaab660c8eb4
```

**Comment by waghanza** [comment]
@defnull which appserver do you recommand for a server side API ?

wsgiref seems not to be tailored for production

**Comment by defnull** [comment]
> @defnull which appserver do you recommand for a server side API ?

Gunicorn is quite common and my go-to WSGI server for most projects, but any WSGI capable (production ready) server will do. [fastwsgi](https://github.com/jamesroberts/fastwsgi) may be worth a try in this benchmarks context, but I have no experience using that in production.  

> wsgiref seems not to be tailored for production

No, it's not. `wsgiref.simple_server.WSGIServer` is a single-threaded blocking implementation only recommended for testing or development. The single-threaded nature is nice if you want to attach a debugger, but horrible for performance.

**Comment by waghanza** [comment]
Thanks for your insights @defnull, I'll use `gunicorn` then 👍🏻 

The idea is to use what could be in **production**, and avoid tweaking because of benchmarking context

**Comment by ire4ever1190** [comment]
> any idea ?

Hi sorry for not following up the first time, made a PR to fix the problem so hopefully its merged soon

**Pull request merged**
