### PR TITLE
Add CodeBehind Framework

### PR DESCRIPTION
**Pull request by elanatframework**

### CODE REVIEW

**Review by waghanza — CHANGES_REQUESTED** [review]
CI is failing.   `/user/:id` should return `:id` as plain text

**Comment by elanatframework** [comment]
The CodeBehind Framework supports two types of configuration:
1- Default configuration
2- Configuring the controller in Route

In the default configuration, the name of the Controller class is specified in the View; requests go to the View first, and the View creates a new instance of the Controller class.

Here we first tried to create the default configuration, but in your test build, the contents of the wwwroot directory were being ignored. We were only able to implement the configuration of the controller in Route.

**Comment by waghanza** [comment]
Thanks for clarification about CodeBehind configuration. It's up to you to choose what suits bests.

The idea is to have a production-ready implementation with the latest **LTS**. I mean the idea is that an app could be bootstraped with this code base, so the code should be flexible, secure ....

Probably a one-file implementation is not the best 😛

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
Results has been updated https://web-frameworks-benchmark.netlify.app/result

**Comment by elanatframework** [comment]
thank you

These tests help us to increase the performance of the CodeBehind framework.
We make changes to the structure of the CodeBehind framework and update the version of the application in your repository.

**Comment by waghanza** [comment]
Sure, feel free. I try my best to  run update each weeks

**Pull request merged**
