### PR TITLE
Update D versions and fix Fomo controller

### PR DESCRIPTION
**Pull request by cyrusmsk**
Fix Fomo's controller (based on documentation)
Update versions for D libs: cgi and handy_httpd

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Idk what is wrong with the Fomo build. Only Controller code was updated, without touching anything else

**Comment by waghanza** [comment]
CI is sometimes wrong. I need some times to figure it out, as a workaround, I test it locally

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
@amirfaramarzi @cyrusmsk this implementation does not work for `fomo`

**Comment by waghanza** [comment]
I restored old version then

**Comment by cyrusmsk** [comment]
I propose to exclude it until it will be fixed

**Comment by cyrusmsk** [comment]
Hardcoded HTTP response is no way "production" solution

**Comment by waghanza** [comment]
> I propose to exclude it until it will be fixed

A little bit rushy for me. We should keep it and exclude it after 1 or 2 rounds, in order to let @amirfaramarzi fix it

**Pull request merged**
