### PR TITLE
[PHP] Update Antidot Framework to version 0.2

### PR DESCRIPTION
**Pull request by kpicaza**
Hi @waghanza, I have already updated Antidot Framework to the 0.2 version. Also, I added some small file declaration fixes.

The major change is that we don't use the index.php file to bootstrap the application in favor of running the DriftPHP server. 

Thanks for your work;-D

### CODE REVIEW

**Comment by waghanza** [comment]
could you merge / rebase ? @kpicaza 

I've updated CI config

**Comment by kpicaza** [comment]
@waghanza I have an issue with the server IP, I'm trying to debug, but I don't see what causes it, I suppose is an error in my implementation but I can't see it, I will continue debugging. Any help will be appreciated;-D
image

**Comment by kpicaza** [comment]
Tried it locally, and the build works
image

**Comment by kpicaza** [comment]
The issue was with the .gitignore file, the "bin" folder is ignored in all the project, what disables committing the antidot framework console tool. Sorry for the noise, and thank you for your great work;-D

**Comment by kpicaza** [comment]
It will fix the error in the actions on the PR https://github.com/the-benchmarker/web-frameworks/pull/3916

**Review by waghanza — APPROVED** [review]

**Pull request merged**
