### PR TITLE
Update nephp to 0.2.6

### PR DESCRIPTION
**Pull request by tbrand**
I've fixed the broken neph configuration.
I just make it works but I'll add few functions after merging this.
For example, specifying multiple jobs.

### CODE REVIEW

**Comment by tbrand** [comment]
@waghanza ping

**Comment by waghanza** [comment]
I still have
~~~crystal
Only one job is supported yet.
~~~
when **building** with
~~~sh
shards update
shards build --release --no-debug
bin/neph sinatra flame
~~~

**Comment by waghanza** [comment]
but I actually have **output** on my `console`  :+1:

**Comment by waghanza** [comment]
seems to `mess-up` the **results**, please :warning: do not merge

**Comment by tbrand** [comment]
@waghanza Yeah that's the problem. I'll fix it but not now.
I would like to merge this if it works fine without the function.

I'll work on fixing neph and send a patch to update it in the future.

**Comment by waghanza** [comment]
@tbrand I think I find a solution #365

**Comment by waghanza** [comment]
@tbrand I notice that **build** time increase comparing to `neph` `0.2.3`

**Pull request merged**
