### PR TITLE
Add swift flying fox

### PR DESCRIPTION
**Pull request by ceopaludetto**
Adding https://github.com/swhitty/FlyingFox

### CODE REVIEW

**Comment by waghanza** [comment]
Could you please notify the author of this tool @ceopaludetto ?

It will be great to have his/her explicit consent

**Comment by ceopaludetto** [comment]
> Could you please notify the author of this tool @ceopaludetto ?
> 
> It will be great to have his/her explicit consent

Waiting author response https://github.com/swhitty/FlyingFox/issues/124

**Comment by waghanza** [comment]
Thanks @ceopaludetto

**Comment by waghanza** [comment]
is included https://web-frameworks-benchmark.netlify.app/result?l=swift

**Pull request merged**
