### PR TITLE
Update

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ [x] silent
+ [ ] beetlex
+ [x] swoole-coroutine
+ [ ] driftphp
+ [x] swoole
+ [x] akkahttp
+ [x] archttpd

### CODE REVIEW

**Comment by waghanza** [comment]
Found 
```scala
#17 2.818 [info] Updated file /usr/src/app/project/build.properties: set sbt.version to 1.9.0
#17 2.852 [info] welcome to sbt 1.9.0 (Eclipse Adoptium Java 11.0.17)
#17 6.734 [info] loading settings for project app-build from assembly.sbt,plugins.sbt ...
#17 7.857 [info] loading project definition from /usr/src/app/project
#17 14.61 [info] loading settings for project app from build.sbt ...
#17 14.88 [info] set current project to server (in build file:/usr/src/app/)
#17 15.15 [warn] sbt 0.13 shell syntax is deprecated; use slash syntax instead: Universal / packageZipTarball
#17 15.43 [info] Wrote /usr/src/app/target/scala-3.2.2/server_3-0.1.0-SNAPSHOT.pom
#17 18.37 [info] compiling 1 Scala source to /usr/src/app/target/scala-3.2.2/classes ...
#17 20.64 [error] error while loading package$,
#17 20.64 [error] class file akka/http/scaladsl/server/package.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
#17 20.64 [error] TASTy signature has wrong version.
#17 20.64 [error]  expected: {majorVersion: 28, minorVersion: 2}
#17 20.64 [error]  found   : {majorVersion: 28, minorVersion: 3}
#17 20.64 [error] 
#17 20.64 [error] This TASTy file was produced by a more recent, forwards incompatible release.
#17 20.64 [error] To read this TASTy file, please upgrade your tooling.
#17 20.64 [error] The TASTy file was produced by Scala 3.3.1.
#17 20.65 [error] error while loading Directives$,
#17 20.65 [error] class file akka/http/scaladsl/server/Directives.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
#17 20.65 [error] TASTy signature has wrong version.
#17 20.65 [error]  expected: {majorVersion: 28, minorVersion: 2}
#17 20.65 [error]  found   : {majorVersion: 28, minorVersion: 3}
#17 20.65 [error] 
#17 20.65 [error] This TASTy file was produced by a more recent, forwards incompatible release.
#17 20.65 [error] To read this TASTy file, please upgrade your tooling.
#17 20.65 [error] The TASTy file was produced by Scala 3.3.1.
#17 21.00 [error] -- [E006] Not Found Error: /usr/src/app/src/main/scala/Main.scala:10:6 ---------
#17 21.00 [error] 10 |      pathSingleSlash {
#17 21.00 [error]    |      ^^^^^^^^^^^^^^^
#17 21.00 [error]    |      Not found: pathSingleSlash
#17 21.00 [error]    |
#17 21.00 [error]    | longer explanation available when compiling with `-explain`
#17 21.01 [error] -- [E006] Not Found Error: /usr/src/app/src/main/scala/Main.scala:11:8 ---------
#17 21.01 [error] 11 |        complete("")
#17 21.01 [error]    |        ^^^^^^^^
#17 21.01 [error]    |        Not found: complete
#17 21.01 [error]    |
#17 21.01 [error]    | longer explanation available when compiling with `-explain`
#17 21.02 [error] error while loading Http$,
#17 21.02 [error] class file akka/http/scaladsl/Http.class is broken, reading aborted with class dotty.tools.tasty.UnpickleException
#17 21.02 [error] TASTy signature has wrong version.
#17 21.02 [error]  expected: {majorVersion: 28, minorVersion: 2}
#17 21.02 [error]  found   : {majorVersion: 28, minorVersion: 3}
#17 21.02 [error] 
#17 21.02 [error] This TASTy file was produced by a more recent, forwards incompatible release.
#17 21.02 [error] To read this TASTy file, please upgrade your tooling.
#17 21.02 [error] The TASTy file was produced by Scala 3.3.1.
#17 21.22 [error] -- [E050] Type Error: /usr/src/app/src/main/scala/Main.scala:22:4 --------------
#17 21.22 [error] 22 |    Http().bindAndHandle(route, "0.0.0.0", 3000)
#17 21.22 [error]    |    ^^^^
#17 21.23 [error]    |    object Http in package akka.http.scaladsl does not take parameters
#17 21.23 [error]    |
#17 21.23 [error]    | longer explanation available when compiling with `-explain`
#17 21.25 [error] 6 errors found
#17 21.32 [error] (Compile / compileIncremental) Compilation failed
#17 21.34 [error] Total time: 6 s, completed Oct 3, 2023, 12:43:25 PM
#17 ERROR: process "/bin/sh -c sbt universal:packageZipTarball" did not complete successfully: exit code: 1
------
 > [build 8/8] RUN sbt universal:packageZipTarball:
21.02 [error] The TASTy file was produced by Scala 3.3.1.
21.22 [error] -- [E050] Type Error: /usr/src/app/src/main/scala/Main.scala:22:4 --------------
21.22 [error] 22 |    Http().bindAndHandle(route, "0.0.0.0", 3000)
21.22 [error]    |    ^^^^
21.23 [error]    |    object Http in package akka.http.scaladsl does not take parameters
21.23 [error]    |
21.23 [error]    | longer explanation available when compiling with `-explain`
21.25 [error] 6 errors found
21.32 [error] (Compile / compileIncremental) Compilation failed
```
for `akkahttp` @whiplash

**Comment by whiplash** [comment]
I think it's picking up Akka-http 10.6.0-M1
it's a milestone version. I'd "stick" with 10.5.2

**Comment by whiplash** [comment]
maybe @patriknw can help

**Comment by waghanza** [comment]
@beetlex-io @panesofglass I can not contact the server using `beetlex` could you quick look into it ?

**Pull request merged**
