### PR TITLE
New release - 22/04/2024

### PR DESCRIPTION
**Pull request by waghanza**
###### Missing or failing frameworks

ℹ️  New to  re-run some, and rework on the code base

+ laravel-s-laravel
+  laravel-s-lumen
+ antidot
+ comet
+ blaze 
+ turbo
+ serverino
+ basolato

### CODE REVIEW

**Comment by waghanza** [comment]
I have
```javascript
    throw new ERR_INVALID_ARG_VALUE('filename', filename, createRequireError);
    ^

TypeError [ERR_INVALID_ARG_VALUE]: The argument 'filename' must be a file URL object, file URL string, or absolute path string. Received undefined
    at createRequire (node:internal/modules/cjs/loader:1510:11)
    at Object.<anonymous> (/usr/src/app/node_modules/@busy-hour/blaze/dist/cjs/utils/common.js:88:50)
    at Module._compile (node:internal/modules/cjs/loader:1369:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1427:10)
    at Module.load (node:internal/modules/cjs/loader:1206:32)
    at Module._load (node:internal/modules/cjs/loader:1022:12)
    at Module.require (node:internal/modules/cjs/loader:1231:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/usr/src/app/node_modules/@busy-hour/blaze/dist/cjs/utils/setup/service.js:37:21)
    at Module._compile (node:internal/modules/cjs/loader:1369:14) {
  code: 'ERR_INVALID_ARG_VALUE'
}

Node.js v20.12.2
``` 
for `blaze ` @krsbx

**Comment by waghanza** [comment]
@hhxsv5 for `laravel-s` I have
```php
Fatal error: Declaration of Hhxsv5\LaravelS\Console\Portal::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /usr/src/app/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 49
```

PS : I use laravel 11

**Comment by waghanza** [comment]
@kpicaza for `antidot`, I have
```php
Warning: require_once(vendor/autoload_runtime.php): Failed to open stream: No such file or directory in /usr/src/app/public/index.php on line 16

Fatal error: Uncaught Error: Failed opening required 'vendor/autoload_runtime.php' (include_path='.:/usr/local/lib/php') in /usr/src/app/public/index.php:16
Stack trace:
#0 {main}
  thrown in /usr/src/app/public/index.php on line 16
```

**Comment by waghanza** [comment]
@gotzmann for `comet`I have 
```php

Fatal error: Declaration of Comet\Request::getServerParams() must be compatible with Psr\Http\Message\ServerRequestInterface::getServerParams(): array in /usr/src/app/vendor/gotzmann/comet/src/Request.php on line 266
Worker[10] process terminated with ERROR: E_COMPILE_ERROR "Declaration of Comet\Request::getServerParams() must be compatible with Psr\Http\Message\ServerRequestInterface::getServerParams(): array in /usr/src/app/vendor/gotzmann/comet/src/Request.php on line 266"
worker[Comet v2.4.4:10] exit with status 65280
```

**Comment by krsbx** [comment]
@waghanza for blaze, I think you just need to rerun the thing again and it should works fine in the latest patch

**Comment by cyrusmsk** [comment]
Hi @waghanza what was the error for serverino?)

**Comment by waghanza** [comment]
There is no error, just server hang up (timeout), maybe we should create a PR with debug mode and logging enabled @cyrusmsk

**Comment by hhxsv5** [comment]
> @hhxsv5 for `laravel-s` I have
> 
> ```
> Fatal error: Declaration of Hhxsv5\LaravelS\Console\Portal::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output) must be compatible with Symfony\Component\Console\Command\Command::execute(Symfony\Component\Console\Input\InputInterface $input, Symfony\Component\Console\Output\OutputInterface $output): int in /usr/src/app/vendor/hhxsv5/laravel-s/src/Console/Portal.php on line 49
> ```
> 
> PS : I use laravel 11

In order to support PHP8, I have upgraded laravel-s to v3.8.0.
Pls review the PR https://github.com/the-benchmarker/web-frameworks/pull/7410

**Pull request merged**
