### PR TITLE
[R] Update rserve to 1.8

### PR DESCRIPTION
**Pull request by waghanza**
Hi @s-u,

I noticed that a new version of https://github.com/s-u/Rserve exists.

This `PR` update to **1.8**.

May I notify you on each change that can affect https://github.com/s-u/Rserve ?

Regards,

### CODE REVIEW

**Comment by s-u** [comment]
@waghanza Although 1.8 series is the latest version and it's available from http://RFroge.net, the CRAN version is still on 1.7 (for historical reasons), so I wouldn't push up the requirement as it would exclude the CRAN version. Useers can still install the latests version. Performance-wise I don't think there should be a difference.

**Comment by waghanza** [comment]
how can user install the latest version @s-u ?

PS : I have no skill about r` **ecosystem**

**Comment by s-u** [comment]
@waghanza same ay as any other - just use `https://rforge.net` as the repository/mirror, so

```r
install.packages("Rserve",,"https://rforge.net")
```

**Comment by waghanza** [comment]
and could the mirror be specified in `DESCRIPTION` file @s-u ?

**Pull request closed without merging**
