### PR TITLE
[Rust] Add rocket

### PR DESCRIPTION
**Pull request by TotalKrill**

### CODE REVIEW

**Comment by waghanza** [comment]
Hi @TotalKrill,

Thanks your contribution. I prefer however not to include any beta or in-dev tool.

Make sure you're contribution, will be reviewed when `rocket` **0.5** will be released.

Regards,

**Comment by TotalKrill** [comment]
Would projects that use a nightly version of the compiler be ok? because rocket 4.5 is widely used in the rust ecosystem

**Comment by waghanza** [comment]
@TotalKrill I understand that `rocket` is used a lot. However, as I'm the only active maintainer `here`, I can not add projects that use nightly

**Comment by waghanza** [comment]
6

**Pull request closed without merging**
