### PR TITLE
Update

### PR DESCRIPTION
**Pull request by waghanza**

### CODE REVIEW

**Comment by waghanza** [comment]
`naruraljs` is failing with
```javascript
internal/modules/cjs/loader.js:905
  throw err;
  ^

Error: Cannot find module 'natural-framework/lib/router'
Require stack:
- /usr/src/app/app.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/usr/src/app/app.js:1:23)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:76:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [ '/usr/src/app/app.js' ]
}
```

@jesusvilla

**Comment by waghanza** [comment]
@atofg `nawa` appear to have weird results on high concurrency

**Comment by jesusvilla** [comment]
Hi @waghanza , it's as if you didn't run: npm i

**Comment by waghanza** [comment]
I did @jesusvilla, the whole dockerfile is
```dockerfile
FROM node:14.18-alpine

  RUN apk add git

RUN npm -g install pm2

WORKDIR /usr/src/app

  COPY app.js package.json ./

ENV NODE_ENV production

  RUN apk add gcompat


RUN npm install




  CMD pm2-runtime start app.js -i $(nproc)
```

**Comment by jesusvilla** [comment]
Thanks @waghanza  I already have it corrected in new version: 0.1.3

**Pull request merged**
