### PR TITLE
update go framework version.

### PR DESCRIPTION
**Pull request by appleboy**
* echo@v3.3.6
* gin@v1.3.0
* mux@v1.6.2
* iris@v10.7.0

Signed-off-by: Bo-Yi Wu <appleboy.tw@gmail.com>

### CODE REVIEW

**Comment by waghanza** [comment]
@appleboy Thanks for you contribution :heart:

May I ask you why `govendor` ? I mean, is there any **standard** way (in `golang` world) to deal with dependencies (and version of each)

**Comment by appleboy** [comment]
`govendor` is one of the vendor tools in Golang so there is no standard way to deal with dependencies.

**Comment by waghanza** [comment]
@appleboy ok, thanks for the explanation. 
I'll merge this, and I'll be happy if a `PR` opened when `go` has a de-facto standard for this

**Comment by appleboy** [comment]
@waghanza Thank you. 👍

**Comment by waghanza** [comment]
@appleboy  Could not use the same system for `fasthttprouter` ?

**Comment by appleboy** [comment]
@waghanza See https://github.com/the-benchmarker/web-frameworks/pull/378/

**Comment by appleboy** [comment]
@waghanza Yes.

**Comment by waghanza** [comment]
ok, so I prefer use 
~~~sh
govendor fetch github.com/gin-gonic/gin@v1.3
~~~

**Comment by waghanza** [comment]
@appleboy Some people use [go dep](https://github.com/golang/dep) to manage dependencies in `go`
as I've understood this tool will be the official way to handle dependencies in `go` (in `1.11`)
is it accurate for us to change ?

**Comment by waghanza** [comment]
+ http://dependabot.com could help us to keep in since with dependencies (this bot create `PR` when a version is updated)

**Comment by waghanza** [comment]
+ also I've seen that dependencie version could be specified on import
 https://github.com/rarkins/lazygit-example/pull/6/files

**Comment by waghanza** [comment]
@appleboy My mistake, [vgo](https://godoc.org/golang.org/x/vgo) will be the official dependency manager as of `go` `>= 1.11`
https://blog.golang.org/versioning-proposal

**Comment by appleboy** [comment]
@waghanza [Go 1.11 Modules](https://github.com/golang/go/wiki/Modules) is the better solution for Golang in the feature and vgo will not be updated. Once Go 1.12 is out, Go 1.10 will be deprecated, at which point all supported versions of Go will have module support. See the [comment](https://github.com/golang/go/issues/27563#issuecomment-429000191). Maybe I can make another PR to do this.

**Comment by waghanza** [comment]
@appleboy will be very helpful (also for me, I start coding in `go` :tada: )

**Pull request merged**
