### PR TITLE
New release for 08/07/2024

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` is a new release. This release took a little more time than usual, I'm switching from architecture (from `amd64`  to `arm64`).

I run the results on a Mac M1, because it's more power efficient and less noisy 😛  but it requires some adjustments.

I found a simple way to run on ARM chips : https://github.blog/changelog/2024-01-30-github-actions-introducing-the-new-m1-macos-runner-available-to-open-source/

###### Failing frameworks

ℹ️  Those frameworks will behidden

+ vixeny-bun
+ (lua) turbo
+ guildenstern
+ happyx
+ bottle
+ akkahttp
+ pico
+ veb
+ vweb

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@gi0baro With `emett` on 3.12, I have
```python
root@1ec95289bf1b:/usr/src/app#  emmett serve --host 0.0.0.0 --port 3000 --workers $(nproc)
<jemalloc>: Unsupported system page size
<jemalloc>: Unsupported system page size
memory allocation of 8 bytes failed
Aborted (core dumped)
```

**Comment by xuyang2** [comment]
This branch is [1 commit ahead of](https://github.com/the-benchmarker/web-frameworks/compare/master...update), [4 commits behind](https://github.com/the-benchmarker/web-frameworks/compare/update...master) master.

**Comment by waghanza** [comment]
> This branch is [1 commit ahead of](https://github.com/the-benchmarker/web-frameworks/compare/master...update), [4 commits behind](https://github.com/the-benchmarker/web-frameworks/compare/update...master) master.

Correct, results will be regenerated for next monday

**Comment by gi0baro** [comment]
> @gi0baro With `emett` on 3.12, I have
> 
> ```python
> root@1ec95289bf1b:/usr/src/app#  emmett serve --host 0.0.0.0 --port 3000 --workers $(nproc)
> <jemalloc>: Unsupported system page size
> <jemalloc>: Unsupported system page size
> memory allocation of 8 bytes failed
> Aborted (core dumped)
> ```

Can you please open up an issue on [granian repo](https://github.com/emmett-framework/granian)?

**Comment by xuyang2** [comment]
> > @gi0baro With `emett` on 3.12, I have
> > ```python
> > root@1ec95289bf1b:/usr/src/app#  emmett serve --host 0.0.0.0 --port 3000 --workers $(nproc)
> > <jemalloc>: Unsupported system page size
> > <jemalloc>: Unsupported system page size
> > memory allocation of 8 bytes failed
> > Aborted (core dumped)
> > ```
> 
> Can you please open up an issue on [granian repo](https://github.com/emmett-framework/granian)?

This looks similar to 
https://github.com/redis/docker-library-redis/issues/208
https://github.com/docker-library/cassandra/issues/192#issuecomment-540995578

**Comment by waghanza** [comment]
it the same as https://github.com/the-benchmarker/web-frameworks/pull/7581 @gi0baro

**Comment by waghanza** [comment]
on `arm` , I have
```
Traceback (most recent call last):
  File "/usr/src/app/server.py", line 1, in <module>
    from happyx import Server
  File "/usr/local/lib/python3.12/site-packages/happyx/__init__.py", line 4, in <module>
    from .server import Server, happyx
  File "/usr/local/lib/python3.12/site-packages/happyx/server.py", line 7, in <module>
    import happyx.happyx as happyx
ImportError: /usr/local/lib/python3.12/site-packages/happyx/happyx.so: cannot open shared object file: No such file or directory
```
for happyx in python @Ethosa

**Comment by xuyang2** [comment]
The happyx-3.8.14-py3-**none-any**.whl does not seem to be a pure-python wheel, but a platform wheel. 
It contains a x86-64 happyx.so.

https://pypi.org/project/happyx/#files

**Comment by waghanza** [comment]
the need to be compiled on arm, also ;-)

**Comment by Ethosa** [comment]
@waghanza I'll update `happyxpy` to `v4.2.0`, it's compiled for `arm64` also 👀

**Comment by gi0baro** [comment]
> it the same as [emmett-framework/granian#85](https://github.com/emmett-framework/granian/issues/85) @gi0baro

Emmett 2.5.12 should work.

**Comment by waghanza** [comment]
@System-Glitch with `goyave` I have
```

**Comment by waghanza** [comment]
sorry, all's good. I've solved it, wrong arch 😛

**Comment by waghanza** [comment]
@jaguililla on  `arm`, I have
```
root@6d77abc7e450:/usr/src/app# java -server -jar /usr/src/app/build/libs/server.jar
Exception in thread "main" java.lang.UnsatisfiedLinkError: failed to load the required native library
        at io.netty.channel.epoll.Epoll.ensureAvailability(Epoll.java:81)
        at io.netty.channel.epoll.EpollEventLoop.<clinit>(EpollEventLoop.java:57)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:189)
        at io.netty.channel.epoll.EpollEventLoopGroup.newChild(EpollEventLoopGroup.java:37)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:84)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:60)
        at io.netty.util.concurrent.MultithreadEventExecutorGroup.<init>(MultithreadEventExecutorGroup.java:49)
        at io.netty.channel.MultithreadEventLoopGroup.<init>(MultithreadEventLoopGroup.java:59)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:117)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:104)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:81)
        at io.netty.channel.epoll.EpollEventLoopGroup.<init>(EpollEventLoopGroup.java:57)
        at com.hexagonkt.http.server.netty.epoll.NettyEpollServerAdapter.groupSupplier(NettyEpollServerAdapter.kt:49)
        at com.hexagonkt.http.server.netty.NettyServerAdapter.startUp(NettyServerAdapter.kt:76)
        at com.hexagonkt.http.server.HttpServer.start(HttpServer.kt:139)
        at com.hexagonkt.http.server.HttpServersKt.serve(HttpServers.kt:36)
        at com.hexagonkt.BenchmarkKt.main(Benchmark.kt:23)
        at com.hexagonkt.BenchmarkKt.main(Benchmark.kt)
Caused by: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll_aarch_64
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
        at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:334)
        at io.netty.channel.epoll.Native.<clinit>(Native.java:96)
        at io.netty.channel.epoll.Epoll.<clinit>(Epoll.java:40)
        ... 17 more
        Suppressed: java.lang.UnsatisfiedLinkError: could not load a native library: netty_transport_native_epoll
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:239)
                at io.netty.channel.epoll.Native.loadNativeLibrary(Native.java:337)
                ... 19 more
        Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll.so
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
                ... 20 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
                        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
                        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
                        at java.base/java.lang.System.loadLibrary(Unknown Source)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:396)
                        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                        ... 20 more
                        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
                                at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
                                at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
                                at java.base/java.lang.System.loadLibrary(Unknown Source)
                                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                                at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
                                at java.base/java.lang.reflect.Method.invoke(Unknown Source)
                                at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:430)
                                at java.base/java.security.AccessController.doPrivileged(Unknown Source)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:422)
                                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:388)
                                ... 21 more
Caused by: java.io.FileNotFoundException: META-INF/native/libnetty_transport_native_epoll_aarch_64.so
        at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:186)
        ... 20 more
        Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_aarch_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
                at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
                at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
                at java.base/java.lang.System.loadLibrary(Unknown Source)
                at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:396)
                at io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
                ... 20 more
                Suppressed: java.lang.UnsatisfiedLinkError: no netty_transport_native_epoll_aarch_64 in java.library.path: /usr/java/packages/lib:/usr/lib64:/lib64:/lib:/usr/lib
                        at java.base/java.lang.ClassLoader.loadLibrary(Unknown Source)
                        at java.base/java.lang.Runtime.loadLibrary0(Unknown Source)
                        at java.base/java.lang.System.loadLibrary(Unknown Source)
                        at io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
                        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
                        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
                        at io.netty.util.internal.NativeLibraryLoader$1.run(NativeLibraryLoader.java:430)
                        at java.base/java.security.AccessController.doPrivileged(Unknown Source)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibraryByHelper(NativeLibraryLoader.java:422)
                        at io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:388)
```

for `netty-epoll` with **hexagon**

**Comment by waghanza** [comment]
@jackcvr  for `turbo` on `arm`, I have
```
luajit: /usr/local/share/lua/5.1/turbo/util.lua:98: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/turbo/util.lua:98: in function </usr/local/share/lua/5.1/turbo/util.lua:97>
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo/web.lua:37: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo.lua:110: in main chunk
        [C]: in function 'require'
        server.lua:1: in main chunk
        [C]: at 0xaaaba9898eb4
/usr/src/app #
```

any ideao ?

**Comment by waghanza** [comment]
@itsumura-h for `basolato`, I have
```
 > [stage-0 8/8] RUN nim c  -d:release --opt:speed      --assertions:off     --warnings:off     --hints:off     -d:release     --opt:speed     --passC:-flto     --passL:-flto     server.nim:
0.555 /home/nim/.nimble/pkgs2/guildenstern-5.1.0-c1de463229a37b822a431f7b575ff75100938182/guildenstern/httpresponse.nim(11, 23) Error: cannot evaluate at compile time: MSG_NOSIGNAL
```
when buildin on **arm**

**Comment by xuyang2** [comment]
@jaguililla 
When using `netty-transport-native-epoll` with hexagon or other frameworks on aarch64, 
it seems necessary to switch the classifier from `linux-x86_64` to `linux-aarch_64`

https://github.com/the-benchmarker/web-frameworks/blob/e2807561652469c2897b91c48ffdff58f96d00f8/java/vertx/pom.xml#L64-L65

https://github.com/the-benchmarker/web-frameworks/blob/e2807561652469c2897b91c48ffdff58f96d00f8/kotlin/hexagon-netty-epoll/build.gradle#L30

https://github.com/the-benchmarker/web-frameworks/blob/e2807561652469c2897b91c48ffdff58f96d00f8/java/vertx4web/pom.xml#L65-L66

**Comment by waghanza** [comment]
@Ethosa The module tries to load am64 version even if I'm on _arm_  
```
Traceback (most recent call last):
  File "/usr/src/app/server.py", line 1, in <module>
    from happyxpy import Server
  File "/usr/local/lib/python3.12/site-packages/happyxpy/__init__.py", line 4, in <module>
    from .server import Server, happyx
  File "/usr/local/lib/python3.12/site-packages/happyxpy/server.py", line 19, in <module>
    import happyxpy.happyx_unix_amd64 as happyx
ImportError: /usr/local/lib/python3.12/site-packages/happyxpy/happyx_unix_amd64.so: cannot open shared object file: No such file or directory
```

**Comment by jaguililla** [comment]
Helo @waghanza, sorry I won't have much availability until august... If the 'epoll' variant is causing troubles, could you disable it temporary?

However, as @xuyang2 points, excluding the current 'netty-epoll' dependency (transitive on 'http_server_netty_epoll') and including the arm one could fix the problem.

Sorry of no being of much help right now, I'll check it on august.

**Comment by Ethosa** [comment]
@waghanza please run this script:
```py
import platform
_cpu = platform.machine().lower()
_platform = platform.system().lower()

print(_platform, _cpu)
```

**Comment by waghanza** [comment]
@jaguililla it is OK now ❤️ as @xuyang2 mentionned, the targeted arch should be specified in pom.xml (weird however that vertx could run)

but take you time, no rush, at least having this comments on a issue (written), allow others to react as a team 🎉 

@Ethosa `linux aarch64`

**Comment by Ethosa** [comment]
> @Ethosa linux aarch64
thanks! I'll upload v4.3.1 for python soon

**Comment by waghanza** [comment]
I'll publish new results on monday @Ethosa, hop it will be ready on the week end ...

if some frameworks fails, I'll hide them and contact the author in here

**Comment by waghanza** [comment]
@Ethosa for `happyx-js|, I have
```

**Comment by Ethosa** [comment]
4.3.1: https://pypi.org/project/happyxpy/

> for happyx-js, I have

Seems like arm64 issue

**Comment by Ethosa** [comment]
@waghanza Can we remove `happyx-js` from results for now? I have an issue in nodejs bindings library at now

**Comment by waghanza** [comment]
@mimiMonads for ``vixeny`, I have :

+ on `deno`

```
root@00f50163cbc4:/usr/src/app# deno run --allow-net --allow-read=. app.ts
error: Uncaught (in promise) TypeError: A handler function must be provided.
Deno.serve({port: 3000}, app.fetch)
     ^
    at Object.serve (ext:deno_http/00_serve.ts:427:11)
    at file:///usr/src/app/app.ts:21:6
```

**Comment by mimiMonads** [comment]
I see the issue , 
```js
Deno.serve({port: 3000}, app)
```
app doesn't have a `fetch` let me make a quick pr

**Comment by mimiMonads** [comment]
Sorry, tbh I just plain copied hono-deno and forgot to change that.

https://github.com/the-benchmarker/web-frameworks/pull/7595

**Comment by xuyang2** [comment]
> @jaguililla (weird however that vertx could run)
> 

https://vertx.io/docs/vertx-core/java/#_native_transports

> preferring native transport will not prevent the application to execute (for example if a JAR is missing). If your application requires native transport, you need to check [isNativeTransportEnabled](https://vertx.io/docs/apidocs/io/vertx/core/Vertx.html#isNativeTransportEnabled--).

**Comment by waghanza** [comment]
@enghitalo I have a compilation error on `arm`  for all `v` based frameworks :
```
11.96 cc  -std=gnu99 -w -o v1.exe ./vc/v.c -lm -lpthread
18.60 ./v1.exe -no-parallel -o v2.exe  cmd/v
19.32 ./v2.exe -nocache -o ./v  cmd/v
19.32 V panic: array.slice: invalid slice index (1 > 0)
19.32 v hash: 04ff511
19.32 /tmp/v_0/v2.exe.01J2RK7EKZHJ3J9GXKH19S27GC.tmp.c:21601: at _v_panic: Backtrace
19.32 /tmp/v_0/v2.exe.01J2RK7EKZHJ3J9GXKH19S27GC.tmp.c:21037: by array_slice
19.32 /tmp/v_0/v2.exe.01J2RK7EKZHJ3J9GXKH19S27GC.tmp.c:57660: by main__main
19.32 /tmp/v_0/v2.exe.01J2RK7EKZHJ3J9GXKH19S27GC.tmp.c:58511: by main
```

**Comment by waghanza** [comment]
@mimiMonads for `vienxy-bun` I have no stdout / stderr when I execute `root@54c0b885679b:/usr/src/app# bun run app.ts
root@54c0b885679b:/usr/src/app#`, could we open a PR to debug together ?

**Comment by waghanza** [comment]
@kernelsauce @jackcvr with `lua - turbo`, I have 

```` 
luajit: /usr/local/share/lua/5.1/turbo/util.lua:98: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/turbo/util.lua:98: in function </usr/local/share/lua/5.1/turbo/util.lua:97>
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo/web.lua:37: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo.lua:110: in main chunk
        [C]: in function 'require'
        server.lua:1: in main chunk
        [C]: at 0xaaab57c28eb4
```

on **ARM**, it was working fine on **X86_64**

**Comment by waghanza** [comment]
@dom64 @ire4ever1190 @olliNiinivaara on **ARM**, i have compilation error with
```
nim c  -d:release --opt:speed      --assertions:off     --warnings:off     --hints:off     -d:release     --opt:speed     --passC:-flto     --passL:-flto     server.nim
```
with https://github.com/olliNiinivaara/GuildenStern
```
0.521 /home/nim/.nimble/pkgs2/guildenstern-7.1.0-5f4b081c4eb9912d5e57ddd21483e42c679642fe/guildenstern/httpresponse.nim(7, 23) Error: cannot evaluate at compile time: MSG_NOSIGNAL  Error: cannot evaluate at compile time: MSG_NOSIGNAL
````

any ideas ?

**Comment by waghanza** [comment]
@Ethosa I have a compilation error for `happyx`
```
 > [stage-0 7/7] RUN nim c  -d:beast -d:disableApiDoc -d:disableDefDeco -d:useMalloc --threads:on --opt:speed      --assertions:off     --warnings:off     --hints:off     -d:release     --opt:speed     --passC:-flto     --passL:-flto     server.nim:
1.035 /home/nim/.nimble/pkgs2/happyx-4.3.0-056e676f256be57311dd675a882b9dc48cf6bfb5/happyx/ssr/websockets.nim(60, 24) Error: undeclared identifier: 'wsClosedConnection'
```

**Comment by waghanza** [comment]
@ahopkins @defnull Not sure to understand, whith `bottle`,  everything was fine, but after switching to **ARM**, i have
```
 wrk -H 'Connection: keep-alive' --connections 64 --threads 8 --duration 15 --timeout 1 --script /home/waghanza/web-frameworks/pipeline.lua http://172.17.0.2:3000/
Running 15s test @ http://172.17.0.2:3000/
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    10.03ms   59.47ms 831.01ms   96.74%
    Req/Sec   584.29      1.48k   12.08k    95.10%
  38086 requests in 15.08s, 5.59MB read
  Socket errors: connect 64, read 0, write 0, timeout 22
Requests/sec:   2525.15
Transfer/sec:    379.76KB
```

**Comment by waghanza** [comment]
@whiplash @jrudolph @raboof I have a compilation error while doing `sbt universal:packageZipTarball`


```scala
[info] Fetched artifacts of server_3
[info] compiling 1 Scala source to /usr/src/app/target/scala-3.4.2/classes ...
[info]
[info]   exception occurred while typechecking /usr/src/app/src/main/scala/Main.scala
[info]
[info]   An unhandled exception was thrown in the compiler.
[info]   Please file a crash report here:
[info]   https://github.com/scala/scala3/issues/new/choose
[info]   For non-enriched exceptions, compile with -Yno-enrich-error-messages.
[info]
[info]      while compiling: /usr/src/app/src/main/scala/Main.scala
[info]         during phase: typer
[info]                 mode: Mode(ImplicitsEnabled)
[info]      library version: version 2.13.12
[info]     compiler version: version 3.4.2
[info]             settings: -classpath /usr/src/app/target/scala-3.4.2/classes:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala3-library_3/3.4.2/scala3-library_3-3.4.2.jar:/root/.cache/coursier/v1/https/repo.akka.io/maven/com/typesafe/akka/akka-http_3/10.6.3/akka-http_3-10.6.3.jar:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/scala-library/2.13.12/scala-library-2.13.12.jar:/root/.cache/coursier/v1/https/repo.akka.io/maven/com/typesafe/akka/akka-http-core_3/10.6.3/akka-http-core_3-10.6.3.jar:/root/.cache/coursier/v1/https/repo.akka.io/maven/com/typesafe/akka/akka-pki_3/2.9.3/akka-pki_3-2.9.3.jar:/root/.cache/coursier/v1/https/repo.akka.io/maven/com/typesafe/akka/akka-parsing_3/10.6.3/akka-parsing_3-10.6.3.jar:/root/.cache/coursier/v1/https/repo.akka.io/maven/com/typesafe/akka/akka-actor_3/2.9.3/akka-actor_3-2.9.3.jar:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/com/hierynomus/asn-one/0.6.0/asn-one-0.6.0.jar:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/slf4j/slf4j-api/1.7.36/slf4j-api-1.7.36.jar:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/com/typesafe/config/1.4.3/config-1.4.3.jar:/root/.cache/coursier/v1/https/repo1.maven.org/maven2/org/scala-lang/modules/scala-java8-compat_3/1.0.2/scala-java8-compat_3-1.0.2.jar -d /usr/src/app/target/scala-3.4.2/classes
[error] cannot resolve reference to type akka.stream.scaladsl.type.Source
[error] the classfile defining the type might be missing from the classpath
[error] (Compile / compileIncremental) Compilation failed
[error] Total time: 5 s, completed Jul 14, 2024, 1:22:28 PM
```

**Comment by mimiMonads** [comment]
> @mimiMonads for `vienxy-bun` I have no stdout / stderr when I execute `root@54c0b885679b:/usr/src/app# bun run app.ts
> root@54c0b885679b:/usr/src/app#`, could we open a PR to debug together ?

Please, I'm using the same set up as hono and we have basically the same structure. Send me a mention and I will try to fix it tonight

**Comment by waghanza** [comment]
I understand @mimiMonads, but when I ran into container `bun run app.ts`, it seems that nothing run (unelike hono)

**Comment by mimiMonads** [comment]
I found the issue, again it should be `app` , instead of `app.fetch` , at the moment I'm not carrying my laptop, but it should be running if we change that.

**Review by mimiMonads — APPROVED** [review]

**Comment by waghanza** [comment]
If someone know how to use **ARM** architecture on github actions, any help is ❤️

**Comment by waghanza** [comment]
@mimiMonads route `/user` should handle POST, seems not 😛 see CI

**Comment by mimiMonads** [comment]
oh yeah @waghanza , I just need to add {"method" : "POST"} to that route and it should be ready to go 🥳

**Comment by Ethosa** [comment]
@waghanza happyx should be 4.3.1, but installed 4.3.0: https://github.com/the-benchmarker/web-frameworks/actions/runs/9930308215/job/27428902496?pr=7581

I create a new release, hope this help

**Pull request merged**
