### PR TITLE
chore: [Elysia] refactored to builder-pattern

### PR DESCRIPTION
**Pull request by yaikohi**
I refactored the elysia example app to reflect the intended way of writing elysia apps, which is by using a builder pattern.

See the [elysia docs](https://elysiajs.com/at-glance.html).

### CODE REVIEW

**Comment by waghanza** [comment]
@yaikohi `node` based frameworks used `pm2` under the hood.

The primary intention of the previous code was to use reuse port, so that comparison with `node`  is not unfair.

Not sure if this implementation could fulfill this goal.

cc @SaltyAom

**Comment by yaikohi** [comment]
I see. In that case the least amount of change would be something like

```typescript
import { Elysia } from "elysia";

const app = new Elysia()
  .get("/", () => "")
  .get("/user/:id", (req) => req.params.id)
  .post("/user", () => "");

Bun.serve({
  fetch: app.fetch,
  reusePort: true,
  port: 3000
})
```

But I am also curious if my initial commit would suffice.

**Comment by waghanza** [comment]
To have a fair comparison with `pm2` we need to implement the cluster mode ourselves, https://github.com/oven-sh/bun/issues/2428  I think.

This implementation is not ideal, but it is ok for me.

Coyld you updatte your PR accordingly ?

**Comment by waghanza** [comment]
Maybe #7192 could interest you @yaikohi

**Pull request merged**
