### PR TITLE
Update config for simps

### PR DESCRIPTION
**Pull request by sy-records**
Hi, @waghanza Can you test it for me?

### CODE REVIEW

**Comment by waghanza** [comment]
Nice improvement

Could you please make the same for all **swoole** based frameworks ?

|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
Before | php (7.4)| [simps](https://github.com/simple-swoole/simps) (1.0) | 120 776 | 155 576 | 177 734 |
After | php (7.4)| [simps](https://github.com/simple-swoole/simps) (1.0) | 108 843 | 170 021 | 188 892 |

**Comment by sy-records** [comment]
Not necessarily applicable to all Swoole frameworks 🤣

**Comment by waghanza** [comment]
+ tcp_fastopen
+ enable_reuse_port

are not **swoole** options ?

**Comment by sy-records** [comment]
It is a configuration of swoole, but not necessarily useful for other frameworks, I'm not sure.

Merge it later and I'll try to test it again.

**Comment by waghanza** [comment]
Ok. If you have no time to do so, I think I will try later :stuck_out_tongue: 

My purpose is to keep (try to) same behaviours for different **swoole** based framework, I mean having as-far-as possible comparison

**Comment by sy-records** [comment]
What is the linux kernel of the test environment? @waghanza

**Comment by sy-records** [comment]
Can you run again?

**Comment by waghanza** [comment]
> What is the linux kernel of the test environment?

**5.7**, I use the same distro than for `cloud` => `fedora`

> Can you run again?

No. I'm not on a computer. But I can help you 😚

**Comment by sy-records** [comment]
Well, you can run it when you have time.

**Comment by sy-records** [comment]
Hi, @waghanza Do you have time now? Can you run again?

**Comment by waghanza** [comment]
Since my daughter is born I have time @sy-records :stuck_out_tongue: 

I find :

|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
| Before (master) | php (7.4)| [simps](https://github.com/simple-swoole/simps) (1.0) | 104 286 | 144 225 | 165 106 |
| After (this branch) | php (7.4)| [simps](https://github.com/simple-swoole/simps) (1.0) | 108 460 | 169 109 | 188 488 |

**Comment by sy-records** [comment]
Congratulate you on becoming a father.  😆

These configuration items seem to have little effect, and the results of each test are different...

**Comment by waghanza** [comment]
> Congratulate you on becoming a father. laughing

I'm already one, but I've lost my skills 😉 btw, thanks

> These configuration items seem to have little effect, and the results of each test are different.

Due to docker ... There is too much fluctuations to consider something I suggest to wait for the cloud version to test this 😚 or if you have an other idea ....

**Comment by sy-records** [comment]
When can you use the cloud version for testing? 

The [results](https://github.com/the-benchmarker/web-frameworks#results) is using a cloud version, right?  You can also merge first, I can wait for the results to be updated. :)

**Comment by waghanza** [comment]
> When can you use the cloud version for testing?

I don't know, it depends on my own schedule, and as you may know, this is not my top priority, right now

Their is no cloud results published for now, take a look at the roadmap https://github.com/the-benchmarker/web-frameworks/issues/3108

**Comment by sy-records** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/3068#issuecomment-652254170 In this comment, I thought you had used the `cloud`...

Is it still running in a docker environment?

**Comment by waghanza** [comment]
Yes. Cloud is not yet ready ...

`laravel` has too many files, `dart` is failing ... are some issues on `cloud` but I think I'll publish a `cloud` version in September

I'm still running in **docker** as for now. I can try to generate `docker` based results, along `podman`, but I think it will have the same issue

**Comment by sy-records** [comment]
Okay, let's merge.

**Pull request merged**
