### PR TITLE
[Python] Use various engines

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` starts using various engines (or setup) per **python** _frameworks_.

The idea is to run framework on **built-in** capability (if provided) and other deployment options.

The is a lot of server engines (`gunicorn`,`uvicorn`,`bjoern`,`uwsgi` ...). The idea is to test with officially supported deployment options + some few accurate options (`hypercorn` for **ASGI** for example)

I, on purpose, keep a small list of setups per framework :
+ I'm the only one maintaining / creating new features
+ The results could be hard to read / understand

----------------------- 
Here is the list of engines / setups we can use for each frameworks

----------------------- 

+ aiohttp
   + [x] aiohttp
   + [x] gunicorn
   + [x] uvloop
+ apidaora
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ asgineer
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ baize-asgi
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ baize-wsgi
   + [x] gunicorn
   + [x] uwsgi
   + [x] waitress
+ blacksheep
   + [x] uvicorn
   + [x] hypercorn
+ bottle
   + [x] wsgiref
   + [x] bjoern
   + [x] gunicorn
+ cherrypy
   + [x] uwsgi
   + [x] waitress
+ clastic
   + [x] gunicorn
   + [x] uwsgi
   + [x] waitress
+ cyclone
   + [x] twisted 
+ django
   + [x] gunicorn
   + [x] uwsgi
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ django-ninja
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ emmett => https://emmett.sh/docs/2.3.x/deployment
   + [x] uvicorn
   + [x] gunicorn
+ falcon
   + [x] uwsgi
   + [x] waitress
   + [x] gunicorn
+ fastapi => https://fastapi.tiangolo.com/deployment/manually/
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ flask => https://flask.palletsprojects.com/en/2.0.x/deploying/index.html
   + [x] gunicorn
   + [x] uwsgi
   + [x] waitress
+ guillotina => https://guillotina.readthedocs.io/en/latest/developer/advanced.html
   + [x] uvicorn
   + [x] hypercorn
+ hug => https://www.hug.rest/website/quickstart
   + [x] uwsgi
   + [x] gunicorn
   + [x] waitress
+ index.py
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ klein
   + [x] twisted
+ masonite
   + [x] gunicorn
   + [x] uwsgi
   + [x] waitress
+ molten
   + [x] gunicorn
   + [x] uwsgi
   + [x] waitress
+ nameko
   + [x] nameko
+ pyramid
   + [x] gunicorn
   + [x] uwsgi
+ quart => https://pgjones.gitlab.io/quart/tutorials/deployment.html
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ responder
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ sanic => https://sanic.readthedocs.io/en/18.12.0/sanic/deploying.html
   + [x] sanic
   + [x] gunicorn
   + [x] uvicorn
   + [x] hypercorn
+ starlette
   + [x] uvicorn
   + [x] hypercorn
   + [x] daphne
+ tonberry
   + [x] uvicorn
   + [x] hypercorn
   + [ ] daphne
+ tornado => https://www.tornadoweb.org/en/stable/guide/running.html
   + [ ] tornado

Feel free to react / give me some feedback @dutradda @douglasfarinelli @almarklein @abersheeran @RobertoPrevato @webknjaz @defnull @cyclone @bdarnell @vitalik @kgriffs @tiangolo @bloodbare @masipcat @josephmancuso @pgjones @ahopkins @tomchristie @Ayehavgunne @taoufik07 @Bogdanp @gi0baro 

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@RobertoPrevato with `daphne`, I have 
```python
Traceback (most recent call last):
  File "blacksheep/baseapp.pyx", line 79, in blacksheep.baseapp.BaseApplication.handle
TypeError: user_info() missing 1 required positional argument: 'id'
```

The docker file use is
```dockerfile
FROM python:3.9-slim
WORKDIR /usr/src/app
RUN apt-get -qq update
RUN apt-get -qy install build-essential
COPY server.py server.py
COPY requirements.txt requirements.txt
RUN pip install daphne
RUN pip install -r requirements.txt
CMD daphne -b 0.0.0.0 -p 3000 server:app
```

have you ever tried  https://github.com/django/daphne ?

**Comment by RobertoPrevato** [comment]
Hi @waghanza, thanks for the heads up. I never tried Daphne, I'm currently supporting Hypercorn and Uvicorn including integration tests. I will soon check why and if I can make BlackSheep work with it.
ASGI is supposed to be a common interface so I didn't think necessary to test with every single implementation. 😄

**Comment by waghanza** [comment]
> ASGI is supposed to be a common interface so I didn't think necessary to test my web framework with every single implementation. 😄

indeed. the idea of this project is to produce some results from frameworks (but with various setups for this `PR`). in this `PR` context it could be accurate to have results (for `blacksheep`) with at least to setups (`uvicorn` and `hypercorn` could be enough). I'll disable `daphne` (I prefer to stick on officially supported setups for now)

**Comment by RobertoPrevato** [comment]
Yes and I think it's a very good idea to test with different setups, it's very useful for benchmarks to show these scenarios.

**Comment by abersheeran** [comment]
@waghanza  index.py can run on uvicorn, hypercorn, daphne or other servers that implement the ASGI interface.

**Review by josephmancuso — APPROVED** [review]
changes look OK

**Comment by kgriffs** [comment]
@waghanza Falcon should be runnable with any compliant ASGI server. We currently test with uvicorn, daphne, and hypercorn:

https://github.com/falconry/falcon/blob/master/tests/asgi/test_asgi_servers.py#L535

That being said, we recommend uvicorn where performance is concerned.

cc @vytas7

**Comment by waghanza** [comment]
@ahopkins I have a 500 on `daphne` for `sanic`
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 1715, in __call__
    await asgi_app()
  File "/usr/local/lib/python3.9/site-packages/sanic/asgi.py", line 223, in __call__
    await self.sanic_app.handle_exception(self.request, e)
  File "/usr/local/lib/python3.9/site-packages/sanic/app.py", line 736, in handle_exception
    await self.dispatch(
  File "/usr/local/lib/python3.9/site-packages/sanic/signals.py", line 191, in dispatch
    return await dispatch
  File "/usr/local/lib/python3.9/site-packages/sanic/signals.py", line 130, in _dispatch
    group, handlers, params = self.get(event, condition=condition)
  File "/usr/local/lib/python3.9/site-packages/sanic/signals.py", line 92, in get
    group, param_basket = self.find_route(
TypeError: 'NoneType' object is not callable
```

**Comment by waghanza** [comment]
@Ayehavgunne Same issue on `tonberry` with `daphne`
```python
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/daphne/http_protocol.py", line 163, in process
    self.application_queue = yield maybeDeferred(
TypeError: __call__() got an unexpected keyword argument 'receive'
```

**Comment by ahopkins** [comment]
> @ahopkins I have a 500 on `daphne` for `sanic`

This is a known thing. Daphne does not execute the life cycle startup events. Last I checked it was an implementation issue with Daphne.

**Comment by waghanza** [comment]
> This is a known thing. Daphne does not execute the life cycle startup events. Last I checked it was an implementation issue with Daphne.

Ok. Then probably worth to add some point in the doc https://sanicframework.org/en/guide/deployment/running.html#asgi

**Comment by ahopkins** [comment]
Thanks @waghanza. I just updated to docs. 

For reference for anyone coming across this: https://github.com/django/daphne/issues/264

**Comment by bgervan** [comment]
Does anyone has public result with the different engines?

**Comment by waghanza** [comment]
Not yet @bgervan. We need to have a customized frontend first.

Actual results shows only 1 engine => https://web-frameworks-benchmark.netlify.app/result

**Pull request merged**
