### PR TITLE
[PHP] Add Framework X

### PR DESCRIPTION
**Pull request by iAxel**
Hi everyone!

This `PR` adds `Framework X` in here.

Website: https://framework-x.org/
Repository: https://github.com/clue/framework-x/
Maintainer: [Christian Lück](https://github.com/clue)

### CODE REVIEW

**Comment by waghanza** [comment]
Hi @clue,

Would you mind to add (or consent that we add) [framework-x](https://github.com/clue/framework-x) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

**Comment by clue** [comment]
@waghanza Thanks for reaching out! Framework X logic looks about right, so good to go from my side!

Note that Framework X is under active development and currently undergoing some major changes. In particular, the installation instructions currently target `dev-main` which is going to change in the (near?) future. On top of this, the current public version does not take advantage of multiple CPU cores automatically at the moment. Once this feature is in, we would expect a significant performance improvement for your particular benchmark. Do you plan to keep this updated as we make progress or do you need anything from our side?

**Comment by waghanza** [comment]
Hi @clue,

I do not plan to update the implementation myself, but I hope @iAxel will.

Regards,

**Review by waghanza — CHANGES_REQUESTED** [review]

**Comment by clue** [comment]
> Hi @waghanza!
> Yes, I will update the framework version as it develops. The important thing is that @clue doesn't mind.

@iAxel Awesome, go ahead!

Make sure to keep an eye on Framework X, as we're currently busy preparing some major changes and I expect to see some significant effect on synthetic benchmarks such as this in the upcoming weeks 🎉

**Review by waghanza — APPROVED** [review]

**Pull request merged**
