### PR TITLE
[Java] Use Spring boot with webflux

### PR DESCRIPTION
**Pull request by david-m-s**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [ ] A `Dockerfile` exists, or can be built ?
+ [ ] I've updated `CI` config file (and **commited** `.travis.yml`)
~~~sh
bin/make ci_config
~~~
+ [ ] I've updated `.dependabot` config file  (and **commited** `.dependabot/config.yml`)
~~~sh
bin/make deps_config
~~~
+ [ ] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/make config
bin/neph ${FRAMEWORK}
crystal spec
~~~

### CODE REVIEW

**Comment by waghanza** [comment]
Hi @david-m-s,

Thanks for your contribution.

Can you explain a little bit what is `webflux` ?

Regards,

**Comment by david-m-s** [comment]
The original web framework included in the Spring Framework, Spring Web MVC, was purpose-built for the Servlet API and Servlet containers. The reactive-stack web framework, Spring WebFlux, was added later in version 5.0. It is fully non-blocking, supports Reactive Streams back pressure, and runs on such servers as Netty, Undertow, and Servlet 3.1+ containers.

Source:
https://docs.spring.io/spring-framework/docs/5.1.x/spring-framework-reference/web-reactive.html#spring-webflux

**Comment by david-m-s** [comment]
Yes, it is a non-blocking approach.
Btw, the build is failing for some reason related to the tooling. I have tried to discover what is the problem but no luck so far.
```
$ bin/neph ${FRAMEWORK} --mode=CI --seq
[Error] yaml doesn't exist at neph.yaml
The command "bin/neph ${FRAMEWORK} --mode=CI --seq" exited with 1.
```

**Comment by waghanza** [comment]
Yes, my bad, I've messed-up `CI` config

**Pull request merged**
