### PR TITLE
[PHP] SunriseRouter with RoadRunner

### PR DESCRIPTION
**Pull request by fenric**

### CODE REVIEW

**Comment by waghanza** [comment]
@fenric Results updated => https://github.com/fenric/web-frameworks/tree/integration/php-sunrise-router-roadrunner#results :tada:

**Comment by sy-records** [comment]
@waghanza Is it an updated test environment? Why has it changed so much?

https://github.com/the-benchmarker/web-frameworks#results

https://github.com/the-benchmarker/web-frameworks/blob/58117c686bd842f3d361d744c0034486c6425d9f/README.md#results

**Comment by waghanza** [comment]
@sy-records since docker is used ... We will have more stable results when on `cloud`

**Comment by sy-records** [comment]
Using a cloud server now? Not docker anymore?
What configuration? @waghanza

**Comment by waghanza** [comment]
In fact, I'm working for it in https://github.com/the-benchmarker/web-frameworks/tree/cloudify

I'll write a clear `roadmap` (better in an issue than only in my mind :stuck_out_tongue:). For a brief summary, each frameworks will be spotted in an isolated `droplet` (https://digitalocean.com) and I'll test a **real-network**

**Pull request merged**
