### PR TITLE
added haskell/wai code

### PR DESCRIPTION
**Pull request by ekr-**
This is an implementation of the sample code using Haskell and the WAI protocol (not a fully-featured framework, thus it is arguable if it meets the criteria; but it should be interesting nonetheless).

### CODE REVIEW

**Comment by waghanza** [comment]
@ekr- **COULD** you have `routing` feature ? `wai-routing` or else, to handle `POST`

**Comment by ekr-** [comment]
Sure, will do. POST is being handled currently (but so are other methods e.g. HEAD/PUT etc) because  of the wildcard on line 17.

I'll add routing later today.

**Comment by waghanza** [comment]
@ekr- any update ?

**Comment by waghanza** [comment]
@begriffs are you interested in fixing this ? our project is a benchmarking project with the focus of comparing performance only :heart:

**Comment by begriffs** [comment]
@waghanza hey there, sorry -- I've got other things I'm working on right now.

**Comment by waghanza** [comment]
@begriffs no problem I totally understand.

we are benchmarking frameworks as a sport, you will always be :heart: welcome (we have a leak of haskell skills ^^)

**Comment by waghanza** [comment]
@ekr- Do you want to continue this `PR` ?

**Pull request closed without merging**
