### PR TITLE
Fix go resolver issue

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` addresses #998 

Regards,

### CODE REVIEW

**Comment by hmarr** [comment]
I'd actually recommend running a `go get` in this directory - when I did so locally a couple of other things were added to the `go.mod`.

**Comment by guregu** [comment]
I agree with @hmarr, it should really look this the comment I posted in the PR here: https://github.com/the-benchmarker/web-frameworks/pull/988#issuecomment-467777091 (which I just copy/pasted from what `go get` gave me).
I know it feels weird specifying the indirect dependencies but that's just how Go modules work, especially with projects that predate modules and are incompatible with it.

**Comment by waghanza** [comment]
@hmarr @guregu As I understand, `go get` COULD automatically check dependency tree, as `bundle install` does in `ruby` ?

I don't know how `go` works for this, but if this is a **resolver**, I think it should not change file in `git` **repo**, but should be done just before build
+ on @dependabot[bot] side
+ in our local containers

**Comment by waghanza** [comment]
@guregu the behavior described is not so weird, at least it's how ruby / bundler works :tada:

**Pull request merged**
