### PR TITLE
[Javascript] Fyrejet update to 3.0

### PR DESCRIPTION
**Pull request by schamberg97**
New fyrejet major version.

One of the modes in the framework is removed. uWebSockets version is still provided, hopefully it is not going to create problems this time around.

### CODE REVIEW

**Comment by waghanza** [comment]
Awesome. 

You can also test the new features https://github.com/the-benchmarker/web-frameworks/pull/3958, I mean this feature allow one framework to be test with multiple runtimes (`node` / `deno` if provided / `uWebSocket` / `turbo` ...)

**Comment by waghanza** [comment]
oops could you merge/rebase @schamberg97 to trigger CI ?

**Comment by schamberg97** [comment]
> oops could you merge/rebase @schamberg97 to trigger CI ?

Tried, to no avail

**Comment by waghanza** [comment]
could you redo this ? normally you should be able to now ...

**Comment by schamberg97** [comment]
@waghanza seems like it’s finally running :)

**Comment by schamberg97** [comment]
@waghanza surprisingly, the CI shows mixed results - the uWebSockets variant has no problem, while the regular, only native node.js variant has issues. Probably a flake

**Comment by waghanza** [comment]
@schamberg97 `npm` try to install `uWebSocket` for the default
in my `package-lock.json`
```json
"uWebSockets.js": {
      "version": "git+ssh://git@github.com/uNetworking/uWebSockets.js.git#3dbec7b56d627193e20705844b6bd10e49848b8c",
      "from": "uWebSockets.js@github:uNetworking/uWebSockets.js#v18.4.0"
    },
```

2 solutions :
- add `git` to `build_deps`
- does not require `uWebSocket` if mode is default

I find the second solution, more elegant, and liter (no need to install an unused package)

**Review by waghanza — APPROVED** [review]

**Pull request merged**
