### PR TITLE
fix (C#) : use defaults 

### PR DESCRIPTION
**Pull request by ShreyasJejurkar**

### CODE REVIEW

**Comment by waghanza** [comment]
Why removing tiered pgo, it is the default?

**Comment by ShreyasJejurkar** [comment]
It is not now, but as we decided not to use any custom options in framework so I am removing this.

And also in .NET 8 it will be ON by default at runtime level itself, so anyway we don't need this.

**Comment by waghanza** [comment]
Ok. We will have this option by default in mid-November then


Let's avoid it for the couple of updates until then

**Comment by waghanza** [comment]
Thanks @ShreyasJejurkar. I'm aligned with this. Maybe we should / could have the same operation for all F# frameworks

Wdyt @panesofglass @jchannon?

**Review by waghanza — APPROVED** [review]

**Comment by ShreyasJejurkar** [comment]
@waghanza I am addressing that next. Could you please create an issue for all of these settings, so that people will update their FW implementation to respect the same.

**Pull request merged**
