### PR TITLE
Upgrade webgo to v3.4.2

### PR DESCRIPTION
**Pull request by bnkamalesh**

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks @bnkamalesh

**Comment by waghanza** [comment]
@bnkamalesh May I ask you for a review at each update `here` ? I mean add you as code owner ?

**Comment by bnkamalesh** [comment]
> @bnkamalesh May I ask you for a review at each update `here` ? I mean add you as code owner ?

@waghanza yes I could contribute, but definitely with a limited capacity. I'm assuming you're asking if I can be a reviewer for the whole 'web-frameworks' repository, and not just 'webgo' related, right?

**Comment by waghanza** [comment]
> I'm assuming you're asking if I can be a reviewer for the whole 'web-frameworks' repository

No. Assuming I prefer to have multiple reviewers (one per framework at least), but any advice / feedback is :heart: 

>  just 'webgo' related

It will be great if I can ping you / made you `CODEOWNERS`

**Comment by bnkamalesh** [comment]
@waghanza for "webgo" most certainly yes.

**Pull request merged**
