### PR TITLE
New release - 12/08/2024

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ [x] act
+ [x] turbo
+ [x] guildenstern
+ [ ] bottle
+ [x] routerling

### CODE REVIEW

**Comment by waghanza** [comment]
@greenlaw110 for `act` I  have
```
root@faa683a1e2ca:/opt/web# /opt/web/run
  _    _         _                    _                  _  ___
 |_)  |_  |\ |  /   |_|  |\/|   /\   |_)  |/  __   /\   /    |
 |_)  |_  | \|  \_  | |  |  |  /--\  | \  |\      /--\  \_   |

                            powered by ActFramework r1.9.2-c4fe6

 version: unknown
scan pkg: benchmark.act
base dir: /opt/web
     pid: 12
 profile: prod
    mode: PROD
      OS: Linux
     jdk: OpenJDK 64-Bit Server VM 11

     zen: Now is better than never.
          Although never is often better than *right* now.

                                                    -  Zen of Python

Exception in thread "main" java.lang.IllegalArgumentException
        at act.asm.ClassReader.<init>(ClassReader.java:170)
        at act.asm.ClassReader.<init>(ClassReader.java:153)
        at act.app.AppClassLoader.scanByteCode(AppClassLoader.java:314)
        at act.app.AppClassLoader.scan(AppClassLoader.java:266)
        at act.app.App.scanAppCodes(App.java:1868)
        at act.app.App.refresh(App.java:783)
        at act.app.AppManager.load(AppManager.java:77)
        at act.app.AppManager$_F$1.visit(AppManager.java:145)
        at act.app.AppManager$_F$1.visit(AppManager.java:141)
        at org.osgl.Lang$Visitor.apply(Lang.java:2462)
        at org.osgl.Lang$Visitor.apply(Lang.java:2452)
        at act.app.AppScanner.scan(AppScanner.java:91)
        at act.app.AppScanner.scan(AppScanner.java:71)
        at act.app.AppManager.loadSingleApp(AppManager.java:55)
        at act.Act.startup(Act.java:338)
        at act.Act.startup(Act.java:1322)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.osgl.Lang.invokeStatic(Lang.java:8150)
        at act.Act.bootstrap(Act.java:1221)
        at act.Act.start(Act.java:703)
        at benchmark.act.AppEntry.main(AppEntry.java:29)
```

any idea ?

**Comment by waghanza** [comment]
@kernelsauce for `lua`, I have
```
/usr/src/app # luajit server.lua
luajit: /usr/local/share/lua/5.1/turbo/util.lua:98: bad argument #1 to 'pairs' (table expected, got nil)
stack traceback:
        [C]: in function 'pairs'
        /usr/local/share/lua/5.1/turbo/util.lua:98: in function </usr/local/share/lua/5.1/turbo/util.lua:97>
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo/web.lua:37: in main chunk
        [C]: in function 'require'
        /usr/local/share/lua/5.1/turbo.lua:110: in main chunk
        [C]: in function 'require'
        server.lua:1: in main chunk
        [C]: at 0xaaab8bc08eb4
```

any idea ?

**Comment by waghanza** [comment]
@olliNiinivaara @dom96 @ire4ever1190 seem that https://github.com/olliNiinivaara/GuildenStern api has changer for 7.2, any help ?

**Comment by waghanza** [comment]
@rayattack With the latest version of **routerling** I have
```python
root@57b363f9a5e8:/usr/src/app# pip install
ERROR: You must give at least one requirement to install (see "pip help install")
root@57b363f9a5e8:/usr/src/app# pip install .
Processing /usr/src/app
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting routerling<0.6,>=0.5 (from server==1.0.0)
  Downloading routerling-0.5.1-py3-none-any.whl.metadata (2.1 kB)
Collecting uvicorn<0.15.0,>=0.14.0 (from routerling<0.6,>=0.5->server==1.0.0)
  Downloading uvicorn-0.14.0-py3-none-any.whl.metadata (4.5 kB)
WARNING: Ignoring version 0.14.0 of uvicorn since it has invalid metadata:
Requested uvicorn<0.15.0,>=0.14.0 from https://files.pythonhosted.org/packages/bf/fe/a41994c92897b162c0c83e8ef10bec54ebdefbce3f3725b530d2091492ac/uvicorn-0.14.0-py3-none-any.whl (from routerling<0.6,>=0.5->server==1.0.0) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    click (>=7.*)
           ~~~~^
Please use pip<24.1 if you need to use this version.
INFO: pip is looking at multiple versions of routerling to determine which version is compatible with other requirements. This could take a while.
Collecting routerling<0.6,>=0.5 (from server==1.0.0)
  Downloading routerling-0.5.0-py3-none-any.whl.metadata (2.1 kB)
Collecting uvicorn<0.15.0,>=0.14.0 (from routerling<0.6,>=0.5->server==1.0.0)
  Using cached uvicorn-0.14.0-py3-none-any.whl.metadata (4.5 kB)
WARNING: Ignoring version 0.14.0 of uvicorn since it has invalid metadata:
Requested uvicorn<0.15.0,>=0.14.0 from https://files.pythonhosted.org/packages/bf/fe/a41994c92897b162c0c83e8ef10bec54ebdefbce3f3725b530d2091492ac/uvicorn-0.14.0-py3-none-any.whl (from routerling<0.6,>=0.5->server==1.0.0) has invalid metadata: .* suffix can only be used with `==` or `!=` operators
    click (>=7.*)
           ~~~~^
Please use pip<24.1 if you need to use this version.
ERROR: Cannot install server because these package versions have conflicting dependencies.

The conflict is caused by:
    routerling 0.5.1 depends on uvicorn<0.15.0 and >=0.14.0
    routerling 0.5.0 depends on uvicorn<0.15.0 and >=0.14.0

To fix this you could try to:
1. loosen the range of package versions you've specified
2. remove package versions to allow pip to attempt to solve the dependency conflict

ERROR: ResolutionImpossible: for help visit https://pip.pypa.io/en/latest/topics/dependency-resolution/#dealing-with-dependency-conflicts
```

**Comment by olliNiinivaara** [comment]
Regarding GuildenStern, here is something that works, and is more idiomatic.
- Check that your version is 7.2.
- Note that performance depends on finding suitable ThreadCount (here 100 as a guess). If you leave it out, it defaults to countProcessors().


```nim
# nim r -d:release -d:threadsafe server

import guildenstern/[dispatcher, httpserver]

const ThreadCount = 100

proc handle() =
  try:
    if not isMethod("GET") or not startsUri("/user/"): reply(Http200)
    else:
      let id = getUri()[6 .. ^1]
      reply(id)
  except: reply(Http500)
  
proc run() =
  let server = newHttpServer(handle, NONE, true, NoBody)
  server.start(3000, ThreadCount, ThreadCount)
  joinThread(server.thread)

run()
```

**Pull request merged**
