### PR TITLE
[Release] 07th of August 2023

### PR DESCRIPTION
**Pull request by waghanza**
@itsumura-h I have a compilation issue for `basolato` (with nim2)
```nim
command line(1, 2) Warning: `gc:option` is deprecated; use `mm:option` instead [Deprecated]
Hint: used config file '/nim/config/nim.cfg' [Conf]
Hint: used config file '/nim/config/config.nims' [Conf]
Hint: used config file '/usr/src/app/config.nims' [Conf]
.......................................................................................................................................................
/root/.nimble/pkgs2/basolato-0.14.1-94cac86836d620bbef281bc9886476b9677502ff/basolato/core/header.nim(56, 11) Warning: a, b all have default value 'newHttpHeaders(true)', this may be unintentional, either use ';' (semicolon) or explicitly write each default value [ImplicitDefaultValue]
.....
/root/.nimble/pkgs2/basolato-0.14.1-94cac86836d620bbef281bc9886476b9677502ff/basolato/core/logger.nim(3, 11) Warning: imported and not used: 'terminal' [UnusedImport]
...................
/root/.nimble/pkgs2/basolato-0.14.1-94cac86836d620bbef281bc9886476b9677502ff/basolato/core/security/session_db/file_session_db.nim(37, 59) template/generic instantiation of `async` from here
/root/.nimble/pkgs2/basolato-0.14.1-94cac86836d620bbef281bc9886476b9677502ff/basolato/core/security/session_db/file_session_db.nim(38, 51) template/generic instantiation of `>` from here
/root/.nimble/pkgs2/flatdb-0.2.6-23eea36f78fd60d6798f8c32ccb85e91bfd1e356/flatdb.nim(271, 15) Error: type mismatch: got 'proc (x: JsonNode): bool{.closure, noSideEffect, gcsafe.}' for 'proc (x: JsonNode): bool = return getStr(getOrDefault(x, key), "") == val' but expected 'proc'
```

@jim-king-2000 @koplenov When this `PR` will be merge, results will be refreshed

###### Failing framowrks

+ handy
+ servernio
+ archttp
+ beetlex
+ amber

ℹ️  Failing frameworks will be hidden

### CODE REVIEW

**Comment by waghanza** [comment]
@dom96 with `jester` I have
```nim
INFO Jester is making jokes at http://0.0.0.0:3000
Starting 4 threads
Listening on port 3000
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
Segmentation fault
```
ℹ️  On nim **2.0**

**Comment by waghanza** [comment]
@ringabout Not sure why but `prologue` does not seems to listen to port 3000 anymore like expected. Could you take a look ?

**Comment by waghanza** [comment]
@mattaylor I have a compilation error on `whip`
```nim
/root/.nimble/pkgs2/packedjson-0.2.2-31464998abf68abd1e9ded84a8692bc8d98c319a/packedjson.nim(325, 5) Error: undeclared identifier: 'shallowCopy'
candidates (edit distance, scope distance); see '--spellSuggest':
 (6, 6): 'alloc'
 (6, 6): 'alloc0'
 (6, 6): 'allocImpl'
```

**Comment by waghanza** [comment]
@crimson-knight During `amber` compilation I have some warnings
```crystal
Shard "inflector" version (0.1.8) doesn't match tag version (1.0.0)
Shard "micrate" version (0.14.0) doesn't match tag version (0.15.0)
```
When running `amber`, I have 
```crystal
Unhandled exception: Error executing process: 'amber': No such file or directory (File::NotFoundError)
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from ???
  from src/env/__libc_start_main.c:95:2 in 'libc_start_main_stage2'
```
Perhaps, the dockerfile is not correct
```dockerfile
  FROM crystallang/crystal:1.9.2-alpine

WORKDIR /usr/src/app

  COPY 'config/application.cr' 'config/application.cr'
  COPY 'config/routes.cr' 'config/routes.cr'
  COPY 'src/amber.cr' 'src/amber.cr'
  COPY 'src/benchmark_amber.cr' 'src/benchmark_amber.cr'
  COPY 'src/controllers/application_controller.cr' 'src/controllers/application_controller.cr'
  COPY 'shard.yml' 'shard.yml'

RUN apk add --update yaml-static

RUN apk add --update sqlite-dev

RUN shards lock
RUN shards install --production
RUN shards build --release --no-debug --static

FROM alpine

WORKDIR /usr/bin

COPY --from=0 /usr/src/app/bin/server /usr/bin/app

  COPY 'config/environments/production.yml' 'config/environments/production.yml'


CMD /usr/bin/app
```

**Comment by dom96** [comment]
@waghanza can you just keep running jester/httpbeast with old Nim?

**Comment by cyrusmsk** [comment]
@waghanza any additional info regarding handy and serverino? So I can test and fix them? Because they are passing tests. Probably problems are raising after high load..

**Comment by ringabout** [comment]
> can you just keep running jester/httpbeast with old Nim?

Or might try with `--mm:refc`.

**Comment by waghanza** [comment]
> can you just keep running jester/httpbeast with old Nim? 

if no solution is found on monday @dom96 

> Or might try with --mm:refc.

Seems working ❤️

**Comment by waghanza** [comment]
> @waghanza any additional info regarding handy and serverino? So I can test and fix them? Because they are passing tests. Probably problems are raising after high load..

Exactly. I have the same for archttp, that is why I prefer to open a new PR (in fact you can) to enable debug mode and try to debug together.

For archttp, I have noticed that at a certain level, the server stops (with a segfault iirc)

**Comment by waghanza** [comment]
@jim-king-2000 @SaltyAom results changed a lot in https://web-frameworks-benchmark.netlify.app/result?l=javascript

**Comment by jim-king-2000** [comment]
Fantastic! Thanks.

**Comment by dom96** [comment]
This might fix the issues https://github.com/dom96/httpbeast/commit/17e322ba68b264e9f4ec755e6946c64242d289ad

**Pull request merged**
