### PR TITLE
New release - 14102024

### PR DESCRIPTION
**Pull request by waghanza**
###### Missing

+ dancer2
+ grip
+ act
+ turbo
+ dream

### CODE REVIEW

**Comment by waghanza** [comment]
@neomatrixcode with `merly` (on latest julia, 1.11), I have 
```julia
┌ Error:
│   exception =
│    MethodError: Cannot `convert` an object of type
│      SubArray{UInt8,1,Memory{UInt8},Tuple{UnitRange{Int64}},true} to an object of type
│      SubArray{UInt8,1,Vector{UInt8},Tuple{UnitRange{Int64}},true}
│    The function `convert` exists, but no method is defined for this combination of argument types.
│
│    Closest candidates are:
│      SubArray{T, N, P, I, L}(::Any, ::Any, ::Any, ::Any) where {T, N, P, I, L}
│       @ Base subarray.jl:19
│      convert(::Type{T}, ::T) where T
│       @ Base Base.jl:126
│      convert(::Type{T}, ::LinearAlgebra.Factorization) where T<:AbstractArray
│       @ LinearAlgebra /usr/local/julia/share/julia/stdlib/v1.11/LinearAlgebra/src/factorization.jl:104
│      ...
│
│    Stacktrace:
│     [1] readuntil(buf::IOBuffer, find_delimiter::typeof(HTTP.Parsers.find_end_of_header))
│       @ HTTP.IOExtras ~/.julia/packages/HTTP/aTjcj/src/IOExtras.jl:139
│     [2] readuntil(t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, f::Function, sizehint::Int64)
│       @ HTTP.ConnectionPool ~/.julia/packages/HTTP/aTjcj/src/ConnectionPool.jl:296
│     [3] readuntil(t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, f::Function)
│       @ HTTP.ConnectionPool ~/.julia/packages/HTTP/aTjcj/src/ConnectionPool.jl:292
│     [4] readheaders(io::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, message::HTTP.Messages.Request)
│       @ HTTP.Messages ~/.julia/packages/HTTP/aTjcj/src/Messages.jl:537
│     [5] startread(http::HTTP.Streams.Stream{HTTP.Messages.Request, HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}})
│       @ HTTP.Streams ~/.julia/packages/HTTP/aTjcj/src/Streams.jl:170
│     [6] handle_transaction(f::HTTP.Handlers.var"#4#5"{HTTP.Handlers.RequestHandlerFunction{Merly.var"#handler#13"{Vector{Pair{String, String}}, Merly.var"#service#12"{Dict{Int64, Vector{@NamedTuple{route::Union{Regex, String}, toexec::Function, urlparams::Union{Nothing, Dict{Int64, String}}}}}, Merly.var"#search#9", Merly.var"#urlparams#7"}, Merly.var"#processrequest#8"{Dict{String, Char}, Dict{String, Function}, typeof(Merly.cleanurl), Merly.var"#myqueryparams#6"}}}}, t::HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}, server::HTTP.Servers.Server{Nothing, Sockets.TCPServer}; final_transaction::Bool)
│       @ HTTP.Servers ~/.julia/packages/HTTP/aTjcj/src/Servers.jl:391
│     [7] handle_connection(f::Function, c::HTTP.ConnectionPool.Connection{Sockets.TCPSocket}, server::HTTP.Servers.Server{Nothing, Sockets.TCPServer}, reuse_limit::Int64, readtimeout::Int64)
│       @ HTTP.Servers ~/.julia/packages/HTTP/aTjcj/src/Servers.jl:347
│     [8] (::HTTP.Servers.var"#8#9"{HTTP.Handlers.var"#4#5"{HTTP.Handlers.RequestHandlerFunction{Merly.var"#handler#13"{Vector{Pair{String, String}}, Merly.var"#service#12"{Dict{Int64, Vector{@NamedTuple{route::Union{Regex, String}, toexec::Function, urlparams::Union{Nothing, Dict{Int64, String}}}}}, Merly.var"#search#9", Merly.var"#urlparams#7"}, Merly.var"#processrequest#8"{Dict{String, Char}, Dict{String, Function}, typeof(Merly.cleanurl), Merly.var"#myqueryparams#6"}}}}, HTTP.Servers.Server{Nothing, Sockets.TCPServer}, Base.RefValue{Int64}, Int64, Int64, Bool, Base.Semaphore, HTTP.ConnectionPool.Connection{Sockets.TCPSocket}})()
│       @ HTTP.Servers ~/.julia/packages/HTTP/aTjcj/src/Servers.jl:304
└ @ HTTP.Servers ~/.julia/packages/HTTP/aTjcj/src/Servers.jl:311
```

**Comment by waghanza** [comment]
@aantron when installing `dream`, I have
```ocaml
 > [8/8] RUN opam install --deps-only --yes .:
0.433 [WARNING] Failed checks on server package definition from source at file:///usr/src/app:
0.433              error 23: Missing field 'maintainer'
0.433            warning 25: Missing field 'authors'
0.433            warning 35: Missing field 'homepage'
0.433            warning 36: Missing field 'bug-reports'
0.433              error 57: Synopsis and description must not be both empty
3.893 The following actions will be performed:
3.894   - install ocamlfind             1.9.6
3.894   - install conf-libev            4-12
3.894   - install conf-gmp              4
3.894   - install conf-pkg-config       3
3.894   - install ocamlbuild            0.15.0
3.894   - install seq                   base
3.894   - install dune                  3.16.0
3.894   - install base-bytes            base
3.894   - install conf-gmp-powm-sec     3
3.894   - install zarith                1.14
3.894   - install conf-libssl           4
3.894   - install uchar                 0.0.2
3.894   - install topkg                 1.0.7
3.894   - install yojson                2.2.2
3.894   - install stringext             1.6.0
3.894   - install stdlib-shims          0.3.0
3.894   - install sexplib0              v0.17.0
3.894   - install re                    1.12.0
3.894   - install psq                   0.2.1
3.894   - install ppx_derivers          1.2.1
3.894   - install pp                    1.2.0
3.894   - install pecu                  0.7
3.894   - install ordering              3.16.0
3.894   - install ohex                  0.2.0
3.894   - install ocaml-syntax-shims    1.0.0
3.894   - install ocaml-compiler-libs   v0.17.0
3.894   - install mirage-clock          4.2.0
3.894   - install menhirSdk             20240715
3.894   - install menhirLib             20240715
3.894   - install menhirCST             20240715
3.894   - install magic-mime            1.3.1
3.894   - install macaddr               5.6.0
3.894   - install lwt-dllist            1.0.1
3.894   - install gmap                  0.3.0
3.894   - install eqaf                  0.10
3.894   - install duration              0.2.1
3.894   - install domain-name           0.4.0
3.894   - install csexp                 1.5.2
3.894   - install cppo                  1.7.0
3.894   - install camlp-streams         5.0.1
3.894   - install bigarray-overlap      0.2.1
3.894   - install bigarray-compat       1.1.0
3.894   - install base64                3.5.1
3.894   - install uutf                  1.0.3
3.894   - install rresult               0.7.0
3.894   - install ptime                 1.2.0
3.894   - install mtime                 2.1.0
3.894   - install hmap                  0.8.1
3.894   - install fmt                   0.9.0
3.894   - install dyn                   3.16.0
3.894   - install ppxlib                0.33.0
3.894   - install menhir                20240715
3.894   - install digestif              1.2.0
3.894   - install ipaddr                5.6.0
3.894   - install dune-configurator     3.16.0
3.894   - install ocplib-endian         1.2
3.894   - install markup                1.0.3
3.894   - install asn1-combinators      0.3.2
3.894   - install ke                    0.6
3.894   - install cstruct               6.2.0
3.894   - install stdune                3.16.0
3.894   - install graphql_parser        0.14.0
3.894   - install ssl                   0.7.0
3.895   - install mirage-crypto         1.1.0
3.895   - install bigstringaf           0.10.0
3.895   - install lwt                   5.7.0
3.895   - install lambdasoup            1.1.1
3.895   - install dune-private-libs     3.16.0
3.895   - install graphql               0.14.0
3.895   - install kdf                   1.0.0
3.895   - install prettym               0.0.3
3.895   - install faraday               0.8.2
3.895   - install angstrom              0.16.1
3.895   - install lwt_ssl               1.2.0
3.895   - install lwt_ppx               2.1.0
3.895   - install logs                  0.7.0
3.895   - install dune-site             3.16.0
3.895   - install graphql-lwt           0.14.0
3.895   - install faraday-lwt           0.8.2
3.895   - install uri                   4.4.0
3.895   - install unstrctrd             0.4
3.895   - install mirage-crypto-rng     1.1.0
3.895   - install faraday-lwt-unix      0.8.2
3.895   - install dream-pure            1.0.0~alpha2
3.895   - install multipart_form        0.6.0
3.895   - install mirage-crypto-rng-lwt 1.1.0
3.895   - install mirage-crypto-pk      1.1.0
3.895   - install mirage-crypto-ec      1.1.0
3.895   - install dream-httpaf          1.0.0~alpha3
3.895   - install multipart_form-lwt    0.6.0
3.895   - install x509                  1.0.4
3.895   - install tls                   1.0.2
3.895   - install caqti                 2.1.2
3.895   - install caqti-lwt             2.1.1
3.895   - install dream                 1.0.0~alpha7
3.895 ===== 95 to install =====
3.895
3.895 <><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
4.307 [base64.3.5.1] downloaded from https://github.com/mirage/ocaml-base64/releases/download/v3.5.1/base64-3.5.1.tbz
4.326 [angstrom.0.16.1] downloaded from https://github.com/inhabitedtype/angstrom/archive/0.16.1.tar.gz
4.699 [asn1-combinators.0.3.2] downloaded from https://github.com/mirleft/ocaml-asn1-combinators/releases/download/v0.3.2/asn1-combinators-0.3.2.tbz
4.736 [bigarray-overlap.0.2.1] downloaded from https://github.com/dinosaure/overlap/releases/download/v0.2.1/bigarray-overlap-0.2.1.tbz
5.049 [bigarray-compat.1.1.0] downloaded from https://github.com/mirage/bigarray-compat/releases/download/v1.1.0/bigarray-compat-1.1.0.tbz
5.186 [bigstringaf.0.10.0] downloaded from https://github.com/inhabitedtype/bigstringaf/archive/0.10.0.tar.gz
5.252 [camlp-streams.5.0.1] downloaded from https://github.com/ocaml/camlp-streams/archive/v5.0.1.tar.gz
5.501 [conf-gmp.4/test.c] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-gmp/test.c.4
5.751 [conf-gmp-powm-sec.3/test.c] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-gmp-powm-sec/test.c.3
5.844 [conf-libev.4-12/build.sh] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-libev/build.sh
5.866 [caqti.2.1.2] downloaded from https://github.com/paurkedal/ocaml-caqti/releases/download/v2.1.2/caqti-v2.1.2.tbz
5.946 [conf-libev.4-12/discover.ml] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-libev/discover.ml.4-12
6.011 [conf-libssl.4/homebrew.sh] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/conf-libssl/homebrew.sh.4
6.024 [caqti-lwt.2.1.1] downloaded from https://github.com/paurkedal/ocaml-caqti/releases/download/v2.1.1/caqti-v2.1.1.tbz
6.362 [cppo.1.7.0] downloaded from https://github.com/ocaml-community/cppo/archive/refs/tags/v1.7.0.tar.gz
6.411 [csexp.1.5.2] downloaded from https://github.com/ocaml-dune/csexp/releases/download/1.5.2/csexp-1.5.2.tbz
6.846 [cstruct.6.2.0] downloaded from https://github.com/mirage/ocaml-cstruct/releases/download/v6.2.0/cstruct-6.2.0.tbz
7.149 [domain-name.0.4.0] downloaded from https://github.com/hannesm/domain-name/releases/download/v0.4.0/domain-name-0.4.0.tbz
7.187 [digestif.1.2.0] downloaded from https://github.com/mirage/digestif/releases/download/v1.2.0/digestif-1.2.0.tbz
7.914 [dream-httpaf.1.0.0~alpha3] downloaded from https://github.com/aantron/dream/releases/download/1.0.0-alpha6/dream-1.0.0-alpha6.tar.gz
8.029 [dream.1.0.0~alpha7] downloaded from https://github.com/aantron/dream/releases/download/1.0.0-alpha7/dream-1.0.0-alpha7.tar.gz
8.162 [dream-pure.1.0.0~alpha2] downloaded from https://github.com/aantron/dream/releases/download/1.0.0-alpha4/dream-1.0.0-alpha4.tar.gz
8.509 [dune-configurator.3.16.0] downloaded from https://github.com/ocaml/dune/releases/download/3.16.0/dune-3.16.0.tbz
8.710 [dune.3.16.0] downloaded from https://github.com/ocaml/dune/releases/download/3.16.0/dune-3.16.0.tbz
8.844 [dune-private-libs.3.16.0] downloaded from https://github.com/ocaml/dune/releases/download/3.16.0/dune-3.16.0.tbz
9.544 [dune-site.3.16.0] found in cache
10.90 [dyn.3.16.0] found in cache
11.86 [duration.0.2.1] downloaded from https://github.com/hannesm/duration/releases/download/v0.2.1/duration-0.2.1.tbz
12.76 [eqaf.0.10] downloaded from https://github.com/mirage/eqaf/releases/download/v0.10/eqaf-0.10.tbz
13.24 [faraday.0.8.2] downloaded from https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz
13.27 [faraday-lwt.0.8.2] downloaded from https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz
13.29 [faraday-lwt-unix.0.8.2] downloaded from https://github.com/inhabitedtype/faraday/archive/0.8.2.tar.gz
13.36 [fmt.0.9.0] downloaded from https://erratique.ch/software/fmt/releases/fmt-0.9.0.tbz
13.69 [graphql-lwt.0.14.0] downloaded from https://github.com/andreas/ocaml-graphql-server/releases/download/0.14.0/graphql-0.14.0.tbz
13.71 [graphql.0.14.0] downloaded from https://github.com/andreas/ocaml-graphql-server/releases/download/0.14.0/graphql-0.14.0.tbz
13.74 [graphql_parser.0.14.0] found in cache
13.89 [hmap.0.8.1] downloaded from http://erratique.ch/software/hmap/releases/hmap-0.8.1.tbz
14.11 [gmap.0.3.0] downloaded from https://github.com/hannesm/gmap/releases/download/0.3.0/gmap-0.3.0.tbz
14.25 [ipaddr.5.6.0] downloaded from https://github.com/mirage/ocaml-ipaddr/releases/download/v5.6.0/ipaddr-5.6.0.tbz
14.66 [kdf.1.0.0] downloaded from https://github.com/robur-coop/kdf/releases/download/v1.0.0/kdf-1.0.0.tbz
14.77 [logs.0.7.0] downloaded from https://erratique.ch/software/logs/releases/logs-0.7.0.tbz
14.82 [ke.0.6] downloaded from https://github.com/mirage/ke/releases/download/v0.6/ke-0.6.tbz
14.83 [lambdasoup.1.1.1] downloaded from https://github.com/aantron/lambdasoup/archive/1.1.1.tar.gz
15.33 [lwt.5.7.0] downloaded from https://github.com/ocsigen/lwt/archive/refs/tags/5.7.0.tar.gz
15.35 [lwt_ppx.2.1.0] downloaded from https://github.com/ocsigen/lwt/archive/5.6.0.tar.gz
15.51 [macaddr.5.6.0] found in cache
15.52 [lwt-dllist.1.0.1] downloaded from https://github.com/mirage/lwt-dllist/releases/download/v1.0.1/lwt-dllist-v1.0.1.tbz
15.86 [lwt_ssl.1.2.0] downloaded from https://github.com/ocsigen/lwt_ssl/releases/download/1.2.0/lwt_ssl-1.2.0.tbz
15.98 [magic-mime.1.3.1] downloaded from https://github.com/mirage/ocaml-magic-mime/releases/download/v1.3.1/magic-mime-1.3.1.tbz
16.09 [markup.1.0.3] downloaded from https://github.com/aantron/markup.ml/archive/1.0.3.tar.gz
16.40 [mirage-clock.4.2.0] downloaded from https://github.com/mirage/mirage-clock/releases/download/v4.2.0/mirage-clock-4.2.0.tbz
16.87 [mirage-crypto.1.1.0] downloaded from https://github.com/mirage/mirage-crypto/releases/download/v1.1.0/mirage-crypto-1.1.0.tbz
17.00 [mirage-crypto-ec.1.1.0] downloaded from https://github.com/mirage/mirage-crypto/releases/download/v1.1.0/mirage-crypto-1.1.0.tbz
17.05 [mirage-crypto-pk.1.1.0] downloaded from https://github.com/mirage/mirage-crypto/releases/download/v1.1.0/mirage-crypto-1.1.0.tbz
17.16 [mirage-crypto-rng.1.1.0] found in cache
17.30 [mirage-crypto-rng-lwt.1.1.0] found in cache
17.45 [mtime.2.1.0] downloaded from https://erratique.ch/software/mtime/releases/mtime-2.1.0.tbz
18.04 [ocaml-compiler-libs.v0.17.0] downloaded from https://github.com/janestreet/ocaml-compiler-libs/archive/refs/tags/v0.17.0.tar.gz
18.09 [multipart_form-lwt.0.6.0] downloaded from https://github.com/dinosaure/multipart_form/releases/download/v0.6.0/multipart_form-0.6.0.tbz
18.10 [multipart_form.0.6.0] downloaded from https://github.com/dinosaure/multipart_form/releases/download/v0.6.0/multipart_form-0.6.0.tbz
18.38 [ocamlfind.1.9.6] downloaded from http://download.camlcity.org/download/findlib-1.9.6.tar.gz
18.53 [ocamlfind.1.9.6/0001-Harden-test-for-OCaml-5.patch] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/ocamlfind/0001-Harden-test-for-OCaml-5.patch
18.61 [ocamlbuild.0.15.0] downloaded from https://github.com/ocaml/ocamlbuild/archive/refs/tags/0.15.0.tar.gz
18.78 [ocaml-syntax-shims.1.0.0] downloaded from https://github.com/ocaml-ppx/ocaml-syntax-shims/releases/download/1.0.0/ocaml-syntax-shims-1.0.0.tbz
18.80 [ordering.3.16.0] found in cache
19.01 [ocplib-endian.1.2] downloaded from https://github.com/OCamlPro/ocplib-endian/archive/refs/tags/1.2.tar.gz
19.15 [ohex.0.2.0] downloaded from https://github.com/ocaml/opam-source-archives/raw/main/ohex-0.2.0.tar.gz
20.16 [pecu.0.7] downloaded from https://github.com/mirage/pecu/releases/download/v0.7/pecu-0.7.tbz
20.18 [pp.1.2.0] downloaded from https://github.com/ocaml-dune/pp/releases/download/1.2.0/pp-1.2.0.tbz
20.54 [ppx_derivers.1.2.1] downloaded from https://github.com/ocaml-ppx/ppx_derivers/archive/1.2.1.tar.gz
20.59 [prettym.0.0.3] downloaded from https://github.com/dinosaure/prettym/releases/download/0.0.3/prettym-0.0.3.tbz
20.62 [ppxlib.0.33.0] downloaded from https://github.com/ocaml-ppx/ppxlib/releases/download/0.33.0/ppxlib-0.33.0.tbz
20.70 [ptime.1.2.0] downloaded from https://erratique.ch/software/ptime/releases/ptime-1.2.0.tbz
20.89 [rresult.0.7.0] downloaded from https://erratique.ch/software/rresult/releases/rresult-0.7.0.tbz
20.99 [seq.base/META.seq] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/META.seq
21.06 [seq.base/seq.install] downloaded from https://raw.githubusercontent.com/ocaml/opam-source-archives/main/patches/seq/seq.install
21.16 [re.1.12.0] downloaded from https://github.com/ocaml/ocaml-re/releases/download/1.12.0/re-1.12.0.tbz
21.22 [psq.0.2.1] downloaded from https://github.com/pqwy/psq/releases/download/v0.2.1/psq-0.2.1.tbz
21.46 [sexplib0.v0.17.0] downloaded from https://github.com/janestreet/sexplib0/archive/refs/tags/v0.17.0.tar.gz
21.48 [stdune.3.16.0] found in cache
21.68 [ssl.0.7.0] downloaded from https://github.com/savonet/ocaml-ssl/archive/refs/tags/v0.7.0.tar.gz
21.94 [stdlib-shims.0.3.0] downloaded from https://github.com/ocaml/stdlib-shims/releases/download/0.3.0/stdlib-shims-0.3.0.tbz
22.87 [stringext.1.6.0] downloaded from https://github.com/rgrinberg/stringext/releases/download/1.6.0/stringext-1.6.0.tbz
22.90 [tls.1.0.2] downloaded from https://github.com/mirleft/ocaml-tls/releases/download/v1.0.2/tls-1.0.2.tbz
22.99 [topkg.1.0.7] downloaded from https://erratique.ch/software/topkg/releases/topkg-1.0.7.tbz
23.35 [uchar.0.0.2] downloaded from https://github.com/ocaml/uchar/releases/download/v0.0.2/uchar-0.0.2.tbz
23.43 [unstrctrd.0.4] downloaded from https://github.com/dinosaure/unstrctrd/releases/download/v0.4/unstrctrd-0.4.tbz
23.52 [uutf.1.0.3] downloaded from https://erratique.ch/software/uutf/releases/uutf-1.0.3.tbz
23.72 [uri.4.4.0] downloaded from https://github.com/mirage/ocaml-uri/releases/download/v4.4.0/uri-4.4.0.tbz
23.95 [yojson.2.2.2] downloaded from https://github.com/ocaml-community/yojson/releases/download/2.2.2/yojson-2.2.2.tbz
23.99 [x509.1.0.4] downloaded from https://github.com/mirleft/ocaml-x509/releases/download/v1.0.4/x509-1.0.4.tbz
24.26 [zarith.1.14] downloaded from https://github.com/ocaml/Zarith/archive/release-1.14.tar.gz
24.28 [ERROR] The sources of the following couldn't be obtained, aborting:
24.28           - menhir.20240715: Curl failed
24.28           - menhirCST.20240715: Curl failed
24.28           - menhirLib.20240715: Curl failed
24.28           - menhirSdk.20240715: Curl failed
24.28
------
```

any idea ?

**Comment by waghanza** [comment]
@grkek I have a compilation error for **grip** _3_
```
 > [stage-0 8/8] RUN shards build --release --no-debug --static:
0.118 I: Dependencies are satisfied
0.118 I: Building: server
5.251 E: Error target server failed to compile:
5.251 /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/libevent.a(evutil.o): in function `test_for_getaddrinfo_hacks':
5.251 (.text+0xe4): warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
5.251 /usr/bin/ld: /usr/lib/gcc/aarch64-linux-gnu/12/../../../aarch64-linux-gnu/libevent.a(evutil.o): in function `evutil_getaddrinfo_common_':
5.251 (.text+0x1b10): warning: Using 'getprotobynumber' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
5.251 /usr/bin/ld: (.text+0x1a88): warning: Using 'getservbyname' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
5.251 Showing last frame. Use --error-trace for full trace.
5.251
5.251 In lib/grip/src/grip/handlers/exception.cr:47:67
5.251
5.251  47 | context.response.print(Grip::Minuscule::ExceptionPage.for_runtime_exception(context, exception).to_s)
5.251                                                             ^--------------------
5.251 Error: undefined method 'for_runtime_exception' for Grip::Minuscule::ExceptionPage.class
5.251
------
```

could you please check the implementation ?

I use an ARM platform, mac m1.

Regards,

**Comment by aantron** [comment]
> ```ocaml
> 24.28 [ERROR] The sources of the following couldn't be obtained, aborting:
> 24.28           - menhir.20240715: Curl failed
> 24.28           - menhirCST.20240715: Curl failed
> 24.28           - menhirLib.20240715: Curl failed
> 24.28           - menhirSdk.20240715: Curl failed
> 24.28
> ------
> ```
> 
> any idea ?

This looks like, most likely, a temporary error. Were you able to successfully retry at another time?

**Pull request merged**
