### PR TITLE
Go framework - GF version upgrades

### PR DESCRIPTION
**Pull request by johng-cn**
The go framework `GF` version upgrades, performance boosts!

What will the result be? 😄

### CODE REVIEW

**Comment by waghanza** [comment]
@johng-cn `CI` has failed

**Comment by waghanza** [comment]
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/159273267

**Comment by johng-cn** [comment]
I see, I'll check it later.

**Comment by johng-cn** [comment]
@waghanza OK, my bad, a small bug fixed. 😄

**Pull request merged**
