### PR TITLE
Rust.warp

### LINKED ISSUE #2637: Add warp
https://github.com/seanmonstar/warp

I'm working on this.

### PR DESCRIPTION
**Pull request by whiplash**
Closes #2637 #751

### CODE REVIEW

**Comment by waghanza** [comment]
@seanmonstar do you agree (or at least not opposed) to include `warp` in this list ?

**Comment by seanmonstar** [comment]
If asking my personal opinion, I wouldn't want it included. It's stressful to manage benchmarks, and fixing them or making sure they are up-to-date. And techempower already has a really big one.

**Comment by waghanza** [comment]
@seanmonstar we are taking care of updates :heart: I know **tfb** has a big benchmark, but we want to create a simpler benchmark, and compare performances across the same version of `rust`.

BTW, if you think it is a bad idea to list it `here`, or if you could hurt anyone in you community, we are **NOT** going against your opinion

**Comment by waghanza** [comment]
@seanmonstar Do yout want us **NOT** to list `warp` here ? 

We won't ask you for extra work :heart:

**Comment by waghanza** [comment]
@seanmonstar do you prefer **NOT** to have `warp` included `here` ?

In any case, no obligation, neither to contribute, nor to be requested if you do not want.

**Comment by waghanza** [comment]
I close this `PR` @whiplash 

Feel free to come back at any time @seanmonstar

**Pull request closed without merging**
