### PR TITLE
Update aplus framework version

### PR DESCRIPTION
**Pull request by natanfelles**
Latest version is [23.0.1](https://github.com/aplus-framework/framework/releases).

### CODE REVIEW

**Review by waghanza — CHANGES_REQUESTED** [review]
Missing config.yaml

**Comment by natanfelles** [comment]
Hello @waghanza !
The version of [aplus/app](https://github.com/aplus-framework/app/releases) is `23.3.2` now. This is set as `23.3` in the config.yaml file.
But [aplus/framework](https://github.com/aplus-framework/framework/releases) is `23.0.1`. This is required in the composer.json.

**Comment by waghanza** [comment]
I've made changes in the next release branch @natanfelles

**Comment by natanfelles** [comment]
Sorry, but I don't know which branch is next release.
Is it in that repository?

**Comment by natanfelles** [comment]
Sorry, but I don't know which branch is next release.
Is it in this repository?

**Comment by waghanza** [comment]
- [ ] sorry, next release on https://github.com/the-benchmarker/web-frameworks/pull/6690

Results will be updated as soon as this PR is merged

**Pull request closed without merging**
