### PR TITLE
[PHP] Upgrade containers to 8.0

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` upgrade **PHP** to `8.0`

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@l0gicgate @luoxiaojun1992 @huangzhhui @limingxinleo @dominikzogg @fenric @ruudboon @wolfy-j @48d90782 @jcheron  Is your framework compliant (or will be seen) with PHP 8.0 ?

--------------
@jcheron @luoxiaojun1992 @fenric May I add you to `reviewer` in order to notify you of any change that affect your framework ?

--------
I have a full CI with failing cases in https://the-benchmarker.semaphoreci.com/workflows/cb10ef80-08b9-4045-bf3d-f7e129bde0ca

**Comment by l0gicgate** [comment]
@waghanza

Slim ^4.7 is PHP 8.0 compatible so should be good to go.

**Comment by fenric** [comment]
Hello @waghanza

`Sunrise // PHP` packages will be updated this month... I'm not against reviewing... Thx!

**Comment by waghanza** [comment]
> @waghanza
> 
> Slim ^4.7 is PHP 8.0 compatible so should be good to go.

Indeed, only failing in `swoole` because of `chubbyphp/chubbyphp-swoole-request-handler`
https://the-benchmarker.semaphoreci.com/jobs/b4a4d6ab-6aa6-4794-89c8-cff49e6fffae

**Comment by dominikzogg** [comment]
@waghanza on it (swoole) forgot to tag the repository

**Comment by dominikzogg** [comment]
@waghanza my framework is php 8.0 ready but not the psr7 implementation (the one from @fenric) i could switch to another if you like

**Comment by waghanza** [comment]
> @waghanza on it (swoole) forgot to tag the repository

feel free to add any change in this branch, via `PR` for example

**Comment by dominikzogg** [comment]
@waghanza swoole and workerman libraries are tagged, should be available soon (should for the issue with slim-swoole. FYI: @l0gicgate

**Comment by limingxinleo** [comment]
Sorry, hyperf does not works in php8.

Better reflection will compliant in january

**Comment by luoxiaojun1992** [comment]
Elasticsearch sdk is not compatible for php8 now. Maybe I can move it from require section to suggestion and test again.

@waghanza

**Comment by dominikzogg** [comment]
@waghanza https://github.com/the-benchmarker/web-frameworks/pull/3618

**Comment by DocDocTeam** [comment]
You can enable JIT. Add configuration for opcache.ini config:

```ini
opcache.enable_cli=1
opcache.enable=1
opcache.jit_buffer_size=64M
opcache.jit=1255
```

**Comment by alexpts** [comment]
You can enable JIT for more performance. Add configuration for opcache.ini config:

```ini
opcache.enable_cli=1
opcache.enable=1
opcache.jit_buffer_size=64M
opcache.jit=1255
```

**Comment by waghanza** [comment]
Thanks @alexpts for your feedback. I have however some questions :

> You can enable JIT for more performance. Add configuration for opcache.ini config:
> 
> ```ini
> opcache.enable_cli=1
> opcache.enable=1
> opcache.jit_buffer_size=64M
> opcache.jit=1255
> ```

How do you compute buffer size for the not compiler ?
Why this number for `opcache.jit` ?

**Comment by fenric** [comment]
#3654

**Comment by alexpts** [comment]
> How do you compute buffer size for the not compiler ?
> Why this number for `opcache.jit` ?

This is a number for example, it is not calculated for a specific case.

**Comment by waghanza** [comment]
Replaced with #3655

**Pull request merged**
