### PR TITLE
Cloudification

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` upgrade this project. It allow to build _cloud instances_ (`droplet`) so as metrics can be collected from a closer environment to what could be made in **real-life**

Actually, metrics are collected from a **local** `docker`

##### Achievements

+ Nim
   + [ ] httpbeast
   + [ ] jester
+ C
   + [ ] kore
   + [ ] agoo-c
+ Clojure
   + [ ] coast
+ Elixir
   + [ ] cowboy_stream
   + [ ] phoenix
   + [ ] cowboy
   + [ ] plug
+ Rust
   + [ ] nickel
   + [ ] actix
   + [ ] iron
   + [ ] gotham
+ Julia
   + [ ] merly
+ C++
   + [ ] evhtp
   + [ ] drogon
+ Crystal
   + [x] kemal
   + [x] spider-gazelle
   + [x] router.cr
   + [x] amber
   + [x] ricr
   + [x] athena
   + [x] grip
   + [x] onyx
   + [x] lucky
   + [x] orion
   + [x] toro
+ Ruby
   + [x] rails
   + [x] grape
   + [x] rack_app
   + [x] flame
   + [x] agoo
   + [x] roda
   + [x] rack-routing
   + [x] syro
   + [x] sinatra
   + [x] camping
   + [x] hanami
   + [x] hanami-api
   + [x] cuba
+ Scala
   + [ ] akkahttp
   + [ ] http4s
+ Go
   + [x] gramework
   + [x] fasthttprouter
   + [x] router
   + [x] gin
   + [x] echo
   + [x] aero
   + [x] webgo
   + [x] chi
   + [x] mars
   + [x] air
   + [x] gorouter
   + [x] kami
   + [x] fasthttp
   + [x] goroute
   + [x] atreugo
   + [x] gorilla-mux
   + [x] violetear
   + [x] rte
   + [x] gorouter-fasthttp
   + [x] fiber
   + [x] gf
   + [x] httprouter
   + [x] beego
+ C#
   + [ ] aspnetcore
+ Dart
   + [ ] aqueduct
+ PHP
   + [ ] imi
   + [ ] swoft
   + [ ] laravel
   + [ ] lumen
   + [ ] slim
   + [ ] hyperf
   + [ ] laminas
   + [ ] one-fpm
   + [ ] phalcon
   + [ ] chubbyphp
   + [ ] one
   + [ ] ubiquity
   + [ ] sw-fw-less
   + [ ] mezzio
   + [ ] basicphp
   + [ ] symfony
   + [ ] spiral
   + [ ] hamlet
   + [ ] yii
   + [ ] workerman
+ Python
   + [x] cherrypy
   + [x] apidaora
   + [x] responder
   + [x] asgineer
   + [x] quart
   + [x] emmett
   + [x] hug
   + [x] pyramid
   + [x] blacksheep
   + [x] starlette
   + [x] clastic
   + [x] aiohttp
   + [x] falcon
   + [x] molten
   + [x] flask
   + [x] fastapi
   + [x] django
   + [x] klein
   + [x] sanic
   + [x] bottle
   + [x] masonite
   + [x] tornado
   + [x] cyclone
   + [x] nameko
+ Kotlin
   + [ ] ktor
+ Java
   + [ ] micronaut
   + [ ] rapidoid
   + [ ] spring-framework
   + [ ] act
   + [ ] spring-boot
   + [ ] javalin
+ Perl
   + [ ] dancer2
+ F#
   + [ ] suave
+ Javascript
   + [x] restana
   + [x] express
   + [x] muneem
   + [x] iotjs-express
   + [x] feathersjs
   + [x] polka
   + [x] nanoexpress-pro
   + [x] fastify
   + [x] nanoexpress
   + [x] turbo_polka
   + [x] foxify
   + [x] 0http
   + [x] polkadot
   + [x] rayo
   + [x] sails
   + [x] koa
   + [x] moleculer
   + [x] hapi
   + [x] restify
   + [x] sifrr
+ Swift
   + [x] perfect
   + [x] vapor
   + [x] swifter
   + [x] kitura-nio
   + [x] kitura

</details>

<details>
<summary>Results</summary>
Not available, yet
</details>

Regards,

### CODE REVIEW

**Comment by j8r** [comment]
The results looks wrong, likely due to performance variation. The [official performance report](https://www.digitalocean.com/resources/cloud-performance-report/#cpu-multi-core-overview) shows up to 10%.

**Comment by waghanza** [comment]
Thanks @j8r for your feedback. I see the link above, but not sure it is a relevant for this test.
+ I use **s-8vcpu-32gb** `droplet to run those tests
@see https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/
+ The results are not _yet_ stable, sometimes it fails ... I'm investigating ... (but `go` and `crystal` seems OK) -> I'll merge only when I can reproduce results twice or three times (to ensure stability)
+ Those results, comparing to [tfb](https://www.techempower.com/benchmarks) seems quite OK (for `crystal` and `go`)
+ The link above is mainly about comparing `AWS`, `GCP` and `DO`, I can not (despite I wish) test on those clouds

BTW, I think there is also some performance decrease due to any compilation option, or else. Feel free to check the codebase, and give me your improvements ideas :heart:

**Comment by j8r** [comment]
I don't see how size slugs are related to performance stability.

The important sentence in the article is:
> This speed, however, was accompanied by approximately double the performance variation. This variation, however, remains well within expectations for the Cloud servers due to affects from noisy neighbors or shared hosting infrastructure.

`s-8vcpu-32gb` is very likely as affected as the instance type used in the article.  

An other point, no, the results are not on par with TFB. Let's take a few:
|benchmark|||||
|-|-|-|-|-|
|TFB| fasthttp | kemal | amber | gin |
|current web-frameworks| fasthttp | kemal | amber | gin |
|this branch| amber | fasthttp | gin | kemal |

**Comment by j8r** [comment]
According to [their docs](https://www.digitalocean.com/docs/droplets/how-to/create/), the instance type that will fit the best is CPU-optimized.
> CPU-Optimized Performance Droplets, best for CPU intensive tasks and projects that require predictable performance or rely on CPU more than RAM or I/O, like batch processing large data sets, large builds, and video encoding.

Predictable performance and consistency are the most important in benchmarks.

See also [Shared vs Dedicated Droplets](https://www.digitalocean.com/docs/droplets/resources/choose-plan/#shared-vs-dedicated). Dedicated droplets is a must for stability.

**Comment by waghanza** [comment]
> I don't see how size slugs are related to performance stability.

Me neither ... But I run all tests using the cheapest droplet, and I have not any trouble

> According to their docs, the instance type that will fit the best is CPU-optimized.

I have not access to droplet creation via API (despite it is with https://github.com/digitalocean/doctl), but I will ask :ok_hand: 

> See also Shared vs Dedicated Droplets. Dedicated droplets is a must for stability.

Thanks for the tips, I have to see if I can create this with https://github.com/digitalocean/doctl

**Comment by waghanza** [comment]
Like I said, **tfb** has not the same purpose. In other words, I use the most update to date version, what is not a **tfb** feature.

As for now :

|   | fasthttp | kemal | amber | gin |
-- | -- | -- | -- | -- |
| TFB | 1.9 (go 1.14) | 0.26 (crystal 0.32.1) | 0.9 (crystal 0.26.1) | master (go 1.12) |
| here | 1.9 (go 1.14) | 0.26 (crystal 0.33) | 0.33 (crystal 0.33) | 1.6.2 (go 1.14) |

/cc @msmith-techempower, please correct me if I'm wrong (especially in `go`) and I do not know how **production** results are `built`

Also, the **master** branch `here` use a `local` **docker** so do not use a **real-network** stack

**Comment by j8r** [comment]
@waghanza I don't think it explains this performance difference. Also keep it mind that the LLVM version used is as important, sometimes even more than the compiler version.

**Comment by j8r** [comment]
The network can't explain performance difference, just latency.
So in the paper, Kemal and fasthttp are quite similarly compiled, but they are not placed on the same order...

**Comment by waghanza** [comment]
@j8r Also keep it mind that the LLVM version used is as important, sometimes even more than the compiler version, sure

For this branch, I compile on the official `docker` **image** and I run on ubuntu 18.04, btw I'll check the LLVM version

**Pull request closed without merging**
