### PR TITLE
Added uWebSocketjs server in routejs

### PR DESCRIPTION
**Pull request by rajkumardusad**

### CODE REVIEW

**Review by waghanza — COMMENTED** [review]
Will not it be a good idea to compare both ?
I mean having a folder `router.js` (with default node http layer) and `routerjs-uwebsocket` ? I'm doing a PR to enable having both runtime in the same folder

**Comment by rajkumardusad** [comment]
> Will not it be a good idea to compare both ? I mean having a folder `router.js` (with default node http layer) and `routerjs-uwebsocket` ? I'm doing a PR to enable having both runtime in the same folder

Ok

**Comment by rajkumardusad** [comment]
> 

Are you doing a PR or i have to submit a new PR for `routerjs-uwebsocket` ?

**Comment by waghanza** [comment]
Yes, I prefer you make it :-) Maybe in this one :-)

**Comment by rajkumardusad** [comment]
> Yes, I prefer you make it :-) Maybe in this one :-)

Ok I will submit a new PR :-)

**Pull request closed without merging**
