### PR TITLE
Removed DriftPHP

### PR DESCRIPTION
**Pull request by mmoreram**
- Results are not representing real framework performance.
- As we can't control what's being installed here, there's nothing we
can do to check what's going on.
- Non representative results can hurt a project with thousands of
worked hours.

### CODE REVIEW

**Comment by waghanza** [comment]
Hi @mmoreram,

> Results are not representing real framework performance

Not sure about that, btw, we must start any development about having a better implementation. 

I mean
- a simple one (not saying that the one here must be kept) but more reflecting real world workload
- an implementation without any favor (some implementations could favor async based)

> As we can't control what's being installed here, there's nothing we can do to check what's going on. 

I do not get you point here

> Non representative results can hurt a project with thousands of worked hours.

I totally agree, and be sure I'm working as hard as you to deliver some proper results (anything running locally could not reflect wha's going on in production)



Saying that, if you want to remove `driftphp`, I can not (do not want) be opposed on such a decision. You will always be free to live, and, perhaps, come back later ❤️

**Comment by mmoreram** [comment]
Hello @waghanza 

Don't misunderstand me. This is a great project and deserves, as any other open source project, the maximum respect for absolutely everyone.

The thing here is that, in the case of DriftPHP, something is not going properly, what is a problem for the framework itself. This benchmark project works on top of some (useful) magic, where you don't even have to provide a dockerfile, which is great in many ways, but disables us to control what is exactly going on inside.

In the case of DriftPHP, is basically impossible to be serving 3000 requests per second using 8 cores and alive connections. Is just impossible. And we have no way of knowing what's going on there.

This is why I'd like DriftPHP to me deleted from the list, at least until I know what's missing (or whats failing here)

Thanks for your amazing work.

**Comment by mmoreram** [comment]
@waghanza Oh, and BTW, thanks explicitly to you because you cared about the project integration.

**Comment by waghanza** [comment]
> Don't misunderstand me. This is a great project and deserves, as any other open source project, the maximum respect for absolutely everyone.

I do not make this personal, I can understand your point of view

> The thing here is that, in the case of DriftPHP, something is not going properly, what is a problem for the framework itself. This benchmark project works on top of some (useful) magic, where you don't even have to provide a dockerfile, which is great in many ways, but disables us to control what is exactly going on inside.

That's exactly the point about design choosed. I mean the tools in use here a only command line tool. For example, to generate `Dockerfile`s, a simple `bundle exec rake config` will create this file.

The only thing, I think, I have left in this subject, is to specify `config.yaml` definition.

> Thanks for your amazing work.

Always a please ❤️ 

Despite of that, I have made an other round (for me) for all **PHP** `frameworks`, and I have :
|    | Language | Framework | Speed (64) | Speed (256) | Speed (512) |
|----|----------|-----------|-----------:|------------:|------------:|
| 1 | php (7.4)| [mark](https://github.com/passwalls/mark) (1.1) | 179 039.58 | 199 861.14 | 203 487.54 |
| 2 | php (7.4)| [webman](https://github.com/walkor/webman) (1.0) | 157 538.62 | 167 480.13 | 170 241.97 |
| 3 | php (7.4)| [workerman](https://github.com/walkor/Workerman) (4.0) | 144 716.99 | 178 700.50 | 182 593.67 |
| 4 | php (7.4)| [simps](https://github.com/simple-swoole/simps) (1.0) | 115 688.68 | 143 536.30 | 160 270.80 |
| 5 | php (7.4)| [swoole](https://github.com/swoole/swoole-src) (4.6) | 96 385.96 | 119 792.85 | 129 836.71 |
| 6 | php (7.4)| [nano](https://gitlab.com/x.laylatichy.x/nano) (0.0.9) | 91 966.93 | 137 290.27 | 148 291.07 |
| 7 | php (7.4)| [swoole-coroutine](https://github.com/swoole/swoole-src) (4.6) | 89 664.24 | 123 161.42 | 135 562.83 |
| 8 | php (7.4)| [one](https://github.com/lizhichao/one) (2.2) | 73 828.86 | 87 904.71 | 94 455.52 |
| 9 | php (7.4)| [hyperf](https://hyperf.io) (2.1) | 72 450.98 | 86 199.52 | 94 629.83 |
| 10 | php (7.4)| [chubbyphp-workerman](https://github.com/chubbyphp/chubbyphp-framework) (3.4) | 49 981.98 | 53 273.99 | 53 672.33 |
| 11 | php (7.4)| [siler-swoole](https://siler.leocavalcante.dev) (1.7) | 46 701.06 | 53 706.57 | 56 641.92 |
| 12 | php (7.4)| [imi](https://imiphp.com) (1.2) | 43 033.63 | 46 588.37 | 48 348.82 |
| 13 | php (7.4)| [yii-swoole](https://yiiframework.com) (2.0) | 41 365.21 | 45 144.39 | 47 507.91 |
| 14 | php (7.4)| [comet](https://github.com/gotzmann/comet) (1.2) | 37 562.76 | 37 991.54 | 37 730.24 |
| 15 | php (7.4)| [swoft](https://swoft.org) (2.0) | 25 084.04 | 29 168.20 | 30 058.98 |
| 16 | php (7.4)| [sw-fw-less](https://github.com/luoxiaojun1992/sw-fw-less) (preview) | 22 765.76 | 26 073.64 | 26 222.17 |
| 17 | php (7.4)| [chubbyphp-swoole](https://github.com/chubbyphp/chubbyphp-framework) (3.4) | 21 432.78 | 24 576.60 | 25 263.94 |
| 18 | php (7.4)| [slim-swoole](https://slimframework.com) (4.7) | 20 546.20 | 23 202.88 | 23 814.57 |
| 19 | php (7.4)| [antidot](https://github.com/antidot-framework/react-framework) (0.2) | 17 706.21 | 11 320.49 | NaN |
| 20 | php (7.4)| [driftphp](https://github.com/driftphp/driftphp) (0.1) | 16 034.39 | 17 826.55 | 17 161.46 |
| 21 | php (7.4)| [chubbyphp-roadrunner](https://github.com/chubbyphp/chubbyphp-framework) (3.4) | 14 745.41 | 15 115.34 | 15 227.04 |
| 22 | php (7.4)| [slim-roadrunner](https://slimframework.com) (4.7) | 14 419.57 | 14 770.29 | 14 822.08 |
| 23 | php (7.4)| [sunrise-router-roadrunner](https://github.com/sunrise-php/http-router) (2.6) | 14 345.20 | 14 742.18 | 14 848.02 |
| 24 | php (7.4)| [spiral](https://github.com/spiral/framework) (2.7) | 14 253.72 | 14 504.68 | 14 578.45 |
| 25 | php (7.4)| [laravel-s-lumen](https://github.com/hhxsv5/laravel-s) (3.7) | 13 285.99 | 13 938.21 | 13 916.87 |
| 26 | php (7.4)| [basicphp](https://github.com/ray-ang/basicphp) (0.9) | 10 234.99 | 11 049.97 | 10 872.77 |
| 27 | php (7.4)| [fastsitephp](https://github.com/fastsitephp/fastsitephp) (1.4) | 9 890.86 | 10 597.09 | 10 456.94 |
| 28 | php (7.4)| [laravel-s-laravel](https://github.com/hhxsv5/laravel-s) (3.7) | 9 373.46 | 9 330.58 | 9 225.15 |
| 29 | php (7.4)| [ubiquity](https://ubiquity.kobject.net) (2.3) | 8 438.92 | 8 847.94 | 8 724.56 |
| 30 | php (7.4)| [one-fpm](https://github.com/lizhichao/one) (2.2) | 7 437.79 | 7 770.66 | 7 666.78 |
| 31 | php (7.4)| [fatfree](https://fatfreeframework.com) (3.7) | 7 098.78 | 7 550.57 | 7 489.21 |
| 32 | php (7.4)| [phalcon](https://phalcon.io) (4.1) | 7 019.78 | 7 533.92 | 7 460.74 |
| 33 | php (7.4)| [hamlet](https://github.com/vasily-kartashov/hamlet-core) (3.2) | 6 844.52 | 7 263.65 | 7 122.80 |
| 34 | php (7.4)| [siler](https://siler.leocavalcante.dev) (1.7) | 6 708.80 | 7 054.80 | 6 973.09 |
| 35 | php (7.4)| [bearframework](https://github.com/bearframework/bearframework) (1.3) | 5 971.89 | 6 277.89 | 6 275.10 |
| 36 | php (7.4)| [ice](https://iceframework.org) (1.5) | 5 887.58 | 6 069.21 | 6 143.56 |
| 37 | php (7.4)| [sunrise-router](https://github.com/sunrise-php/http-router) (2.6) | 5 560.45 | 5 776.32 | 5 771.55 |
| 38 | php (7.4)| [chubbyphp](https://github.com/chubbyphp/chubbyphp-framework) (3.4) | 5 078.18 | 5 290.37 | 5 293.38 |
| 39 | php (7.4)| [cubex](https://cubex.io) (4.16) | 4 496.07 | 4 612.76 | 4 642.94 |
| 40 | php (7.4)| [sunrise-router-annotations](https://github.com/sunrise-php/http-router) (2.6) | 4 350.24 | 4 444.73 | 4 481.59 |
| 41 | php (7.4)| [slim](https://slimframework.com) (4.7) | 4 338.50 | 4 459.30 | 4 468.47 |
| 42 | php (7.4)| [lumen](https://lumen.laravel.com) (8.2) | 3 884.53 | 3 956.45 | 3 962.10 |
| 43 | php (7.4)| [nette](https://nette.org/en/) (3.1) | 3 882.06 | 3 959.52 | 3 953.80 |
| 44 | php (7.4)| [yii](https://yiiframework.com) (2.0) | 3 742.14 | 3 847.62 | 3 855.96 |
| 45 | php (7.4)| [symfony](https://symfony.com) (5.2) | 3 031.65 | 3 056.53 | 3 064.74 |
| 46 | php (7.4)| [mezzio](https://docs.mezzio.dev) (3.3) | 2 762.16 | 2 805.27 | 2 797.11 |
| 47 | php (7.4)| [laminas](https://getlaminas.org) (3.2) | 1 744.86 | 1 761.46 | 1 756.51 |
| 48 | php (7.4)| [laravel](https://laravel.com) (8.37) | 1 495.74 | 1 510.88 | 1 509.38 |
| 49 | php (7.4)| [codeigniter4](https://codeigniter.com) (4.1) | 1 212.40 | 1 239.72 | 1 233.16 |
| 50 | php (7.4)| [unic](https://unicframework.github.io/docs) (1.0) | 522.88 | 479.30 | 386.56 |

**Comment by waghanza** [comment]
Comparing the above result with https://github.com/the-benchmarker/web-frameworks/blob/cf1413d367bd7b65a0e83573b2aa0c06e392dbac/README.md#results (last update) seems that their is significant changes for `driftphp`

**Comment by waghanza** [comment]
I close this issue due to inactivity, feel free to re-open if their is still an issue @mmoreram

**Pull request closed without merging**
