### PR TITLE
[Javascript]: Add nhttp

### PR DESCRIPTION
**Pull request by herudi**
Add JS framework [nhttp](https://nhttp.deno.dev). ported to Node using [Undici](https://github.com/nodejs/undici)

### CODE REVIEW

**Comment by waghanza** [comment]
Hi @herudi,

Thanks for your contribution. `deno` is not supported yet.

There is a work in progress in https://github.com/the-benchmarker/web-frameworks/pull/3958.

Maybe you should target you PR against the above.

Regards,

**Comment by herudi** [comment]
Hi @waghanza i have fixed the POST path `/` to `/user`.  thanks.

**Comment by waghanza** [comment]
Ok  I understand @herudi, you mean that `nhttp` could run both `node` and `deno` (and `bun`).

I'll be glad then if you can add those engines https://github.com/the-benchmarker/web-frameworks/pull/3958, but using `nhttp`, `nhttp-deno`, `nhttp-bun`, you can start a PR I'll help

**Comment by herudi** [comment]
can I try it on this branch https://github.com/the-benchmarker/web-frameworks/tree/variants ?

**Pull request merged**
