### PR TITLE
[C] Update agoo-c to 0.7

### PR DESCRIPTION
**Pull request by waghanza**
Hi @ohler55,

This is a `PR` that update [agoo-c](https://github.com/ohler55/agoo-c)

This time I've updated this framework manually.

Is there any way to have an automated process ?

@OvermindDL1 Any suggestion 

Regard,

### CODE REVIEW

**Comment by ohler55** [comment]
I wonder if there is a way to make use of the GitHub web hooks.

**Comment by OvermindDL1** [comment]
A poller could at least tell when an update is pending?

**Comment by waghanza** [comment]
if will be awesome to a feature like this in dependabot => https://github.com/dependabot/dependabot-core

**Comment by ohler55** [comment]
Something like that but without all the dependencies. That thing is huge for such a simple task.

**Comment by waghanza** [comment]
> That thing is huge for such a simple task.

No so **huge**, because of languages support (several)

@ohler55 Could you look at `Makefile` ? seems to be **broken** for `0.7`
https://travis-ci.com/the-benchmarker/web-frameworks/jobs/243017523#L259

**Comment by ohler55** [comment]
Ahh, not the make file, I changed a call signature. I'll put in a change for that. Can I edit this branch directly?

**Comment by waghanza** [comment]
@ohler55 you can now, I've invited you on my fork

**Comment by ohler55** [comment]
Thanks. I'll get it done today.

**Comment by ohler55** [comment]
Pushed the change.

**Comment by waghanza** [comment]
I don't see

**Comment by ohler55** [comment]
Finally back on line at a friends house. Currently in California, 3rd world California with no power. Anyway, I thought you wanted me to push directly to your branch. I changed two lines in simple.c. `agoo_res_message_push` is the new function name.

**Pull request merged**
