### PR TITLE
[Swift] Fix Vapor 4 testing

### LINKED ISSUE #2575: [Vapor] Core dump
Hi,

With the following command 
```
wrk --latency --duration 15s --connections 8 --timeout 8 --threads 8 http://172.17.0.2:3000/
```

I have `double free or corruption (out)` on https://github.com/the-benchmarker/web-frameworks/blob/0fbe4912abc6923ddd625ccbb46349e4d64432ff/swift/vapor-framework/main.swift#L1

Do you need more info to debug ?

### PR DESCRIPTION
**Pull request by 0xTim**
This PR resolves #2575 

SwiftPM with 5.2 also doesn't seem to like having yaml files in the same directory as the source files, so I've had to use the proper source layout for SwiftPM projects. I've updated all the Swift projects to work like this and I've also updated the Dockerfile for the new source location.

### CODE REVIEW

**Comment by waghanza** [comment]
@0xTim you forget to push `Package.swift`

**Comment by 0xTim** [comment]
@waghanza which Package.swift? I can see them all there 🤔

**Comment by waghanza** [comment]
`Perfect` one, sorry must be more precise

I fact I don't understand 
~~~
swift/perfect/Package.swift → swift/perfect/Sources/server/Package.swift
~~~

**Comment by waghanza** [comment]
In fact I have 

~~~swift
'server' /usr/src/app: error: dependency 'PerfectHTTPServer' in target 'server' requires explicit declaration; provide the name of the package dependency with '.package(name: "PerfectHTTPServer", url: "https://github.com/PerfectlySoft/Perfect-HTTPServer.git", .upToNextMinor("3.0.0"))'
~~~

**Comment by 0xTim** [comment]
🤦 had the files in the wrong location! Fixed now

**Comment by 0xTim** [comment]
@waghanza do you know why crystal is failing with Swifter? I can build it locally fine

**Pull request closed without merging**
