### PR TITLE
[Nim] Add more optimisations

### PR DESCRIPTION
**Pull request by ire4ever1190**
* Add -d:danger to remove more runtime checks
* Add link time optimisation

### CODE REVIEW

**Comment by ire4ever1190** [comment]
The CI seems to fail since it is still trying to use the older version of mike which won't be a problem once #4208 is merged

**Review by waghanza — COMMENTED** [review]
Thank for this. Honestly, I can not propose any solution / confirm we should use this 😛 

What is a common usage in `nim` ? I mean, is it really safe to use something like `-d:danger` in **production** ?

**Comment by ire4ever1190** [comment]
`-d:danger` turns off checks (so assert statements and things like that). It's usually recommended for production builds so that you have the most performance
But no it **wouldn't be** safe in production since it removes asserts so I'll remove it

**Comment by waghanza** [comment]
could you merge (or rebase) to trigger CI with `mike` **1.1** ?

**Review by waghanza — APPROVED** [review]

**Pull request merged**
