### PR TITLE
Introduce bocadillo

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` addresses 
+ #951
+ https://github.com/bocadilloproject/bocadillo/issues/150

@florimondmanca Here some results (using `docker` on 4x CPU / 16 Gb)

| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| python (3.7) | [japronto](http://github.com/squeaky-pl/japronto) (0.1) | 4.82 ms | 4.35 ms | 9.11 ms | 15.27 ms | 32.09 ms | 3319.00 | 
| python (3.6) | [vibora](http://vibora.io) (0.0) | 7.32 ms | 6.60 ms | 13.57 ms | 22.76 ms | 66.30 ms | 5016.67 | 
| python (3.7) | [falcon](http://falconframework.org) (1.4) | 21.20 ms | 15.54 ms | 37.52 ms | 87.57 ms | 313.04 ms | 17201.00 | 
| python (3.7) | [bottle](http://bottlepy.org) (0.12) | 24.24 ms | 20.97 ms | 39.23 ms | 75.16 ms | 310.65 ms | 15832.33 | 
| python (3.7) | [starlette](http://starlette.io) (0.10) | 24.08 ms | 22.51 ms | 38.84 ms | 50.60 ms | 166.28 ms | 10353.67 | 
| python (3.7) | [hug](http://hug.rest) (2.4) | 29.35 ms | 23.80 ms | 45.23 ms | 88.80 ms | 296.49 ms | 16164.67 | 
| python (3.7) | [bocadillo](http://bocadilloproject.github.io) (0.11) | 35.18 ms | 32.28 ms | 52.10 ms | 60.30 ms | 226.65 ms | 12090.00 | 
| python (3.7) | [aiohttp](http://aiohttp.readthedocs.io) (3.5) | 45.61 ms | 36.25 ms | 78.47 ms | 128.66 ms | 321.72 ms | 28197.33 | 
| python (3.7) | [flask](http://flask.pocoo.org) (1.0) | 61.11 ms | 50.34 ms | 96.62 ms | 172.84 ms | 593.91 ms | 36741.67 | 
| python (3.7) | [sanic](http://github.com/huge-success/sanic) (18.12) | 71.22 ms | 67.71 ms | 102.90 ms | 156.87 ms | 303.14 ms | 26095.00 | 
| python (3.7) | [quart](http://pgjones.gitlab.io/quart) (0.8) | 98.78 ms | 80.97 ms | 173.51 ms | 217.64 ms | 365.27 ms | 50984.67 | 
| python (3.7) | [django](http://djangoproject.com) (2.1) | 101.07 ms | 98.40 ms | 137.21 ms | 360.07 ms | 1301.43 ms | 74276.00 | 
| python (3.7) | [responder](http://github.com/kennethreitz/responder) (1.1) | 118.28 ms | 110.57 ms | 185.81 ms | 227.82 ms | 506.15 ms | 48294.33 | 
| python (3.7) | [tornado](http://tornadoweb.org) (5.1) | 207.86 ms | 142.21 ms | 193.52 ms | 2357.72 ms | 5505.57 ms | 413908.00 |

Regards,

### CODE REVIEW

**Comment by florimondmanca** [comment]
@waghanza Can you also mention this PR fixes https://github.com/bocadilloproject/bocadillo/issues/150? Thanks!

**Comment by florimondmanca** [comment]
By the way @waghanza, I doesn’t seem like the repo’s README has been updated yet. I suppose it will be once you run the tests in production later on?

**Comment by waghanza** [comment]
Hi @florimondmanca, the README will be updated with bocadillo in the next round (either today or tomorrow). However, we are still in development, meaning that we are using docker instead of host per framework (the results could vary upto 40%). I'm working on a cloud solution in https://github.com/the-benchmarker/web-frameworks/pull/632

**Comment by aichholzer** [comment]
@waghanza -My two cents, the numbers should definitely include RPS (requests per second) and throughput. Average response times and percentiles are almost 100% useless as they do not have any context.

**Comment by waghanza** [comment]
@aichholzer yes, by my laziness I have displayed here only `latency` but `req/s` will be in the README :stuck_out_tongue: 

Let open an issue to talk about useful metrics then (all ideas are welcome, and I could not pretend to be an expert) :heart:

**Pull request merged**
