### PR TITLE
Upgrades to Struts 7 and JakartaEE

### PR DESCRIPTION
**Pull request by lukaszlenart**
Upgrades the example app to use the latest Apache Struts 7 and JakartaEE 10

### CODE REVIEW

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
CI is failing, but it's not due to struts2

**Comment by whiplash** [comment]
Is the `struts2` benchmark running?

**Comment by waghanza** [comment]
failing on the last release @lukaszlenart

**Comment by lukaszlenart** [comment]
As far I see everything is fine, ot maybe there is some other place I should look
https://github.com/the-benchmarker/web-frameworks/actions/runs/13473909003/job/37650728320?pr=8258

**Pull request merged**
