### PR TITLE
Ruby: Hanami 2.0.0.rc1

### PR DESCRIPTION
**Pull request by jodosha**

### CODE REVIEW

**Comment by jodosha** [comment]
@waghanza Hold on with the review, I discovered a bug.
Sorry about the hassle.

**Comment by waghanza** [comment]
Is `rc1` ready now @jodosha ?

**Comment by jodosha** [comment]
@waghanza The fix is merged in Hanami, but probably I'll open a new PR here for Hanami 2.0.0 stable.

**Comment by waghanza** [comment]
sure, I'll close this one then @jodosha 

I'll try to update results each weeks

**Pull request closed without merging**
