### PR TITLE
[Javascript] Add tinyhttp

### PR DESCRIPTION
**Pull request by waghanza**
Hi @talentlessguy,

Following https://github.com/talentlessguy/tinyhttp/issues/246, this `PR` adds https://github.com/talentlessguy/tinyhttp in `here`.

Actually, this implementation is very simple, but will change in the future.

Regards,

### CODE REVIEW

**Comment by talentlessguy** [comment]
to make it even more performant u can pass an empty function to `applyExtensions`:

```js
new App({ applyExtensions: (req, res, next) => void next() })
```

**Comment by waghanza** [comment]
what is your recommend for a **production** usage @talentlessguy ? despite, this kind of metrics shown, to have a fair (at least _as-fair-as_ we can), it could be better to reflect what the frameworks can do in **production**

**Comment by talentlessguy** [comment]
@waghanza I think 90% of tinyhttp users don't use that feature so probably no need for custom `applyExtensions` function. Leave it as it is then :D

**Comment by talentlessguy** [comment]
@waghanza for some reason it's not in readme 🤔

**Comment by waghanza** [comment]
in a few days, I need to compute results. I try to do so once a week at least

**Pull request merged**
