### PR TITLE
Add Gotham benchmarks

### PR DESCRIPTION
**Pull request by whitfin**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [x] Please check configuration files
   + [x] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [x] `FRAMEWORKS.yml`, for **frameworks** list
   + [x] `travis.yml`, for CI
+ [x] A `Dockerfile` exists ?
+ [x] All tests passes ?
~~~
export FRAMEWORK=gotham
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~

## Notes

This adds tests for Gotham, and makes sure all Rust images are aligned on the same build process (since Actix was previously using compiler optimizations that the other frameworks weren't). I can't get the tests to pass locally, but I think it's due to the state of my Docker (which I can't change, because I need it for something else). If someone could validate, I'd appreciate it.

### CODE REVIEW

**Comment by waghanza** [comment]
@whitfin I have 
~~~rust
thread 'gotham-worker-1' panicked at 'required type is not present in State container', libcore/option.rs:1000:5
~~~
on `log_user`

**Comment by whitfin** [comment]
@waghanza got it, I'll check it out. Where did you find that error? Is there some place I can look?

**Comment by whitfin** [comment]
@waghanza oh, duh, forgot to actually wire it up. Should be fixed now!

**Comment by waghanza** [comment]
@whitfin tests are `ok`
I have following results on `rust` **frameworks** (CPU x 4 / concurrency 1000 * 5 threads)

+ Requests

| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| rust (1.30) | [nickel](http://nickel-org.github.io) (0.10) | 0.05 ms | 0.04 ms | 0.05 ms | 0.07 ms | 6.37 ms | 64.33 | 
| rust (1.30) | [iron](http://ironframework.io) (0.6) | 0.30 ms | 0.25 ms | 0.48 ms | 1.15 ms | 28.03 ms | 374.33 | 
| rust (nightly) | [rocket](http://rocket.rs) (0.3) | 238.09 ms | 2.62 ms | 476.80 ms | 4824.50 ms | 6594.45 ms | 878214.33 | 
| rust (1.30) | [actix-web](http://actix.rs) (0.7) | 5.26 ms | 4.60 ms | 9.60 ms | 16.74 ms | 99.77 ms | 3498.00 | 
| rust (1.30) | [gotham](http://gotham.rs) (0.3) | 39.21 ms | 6.37 ms | 45.59 ms | 569.80 ms | 860.99 ms | 115115.33 |

+ Latency

| Language (Runtime) | Framework (Middleware) | Requests / s | Throughput |
|---------------------------|---------------------------|----------------:|---------:|
| rust (1.30) | [actix-web](http://actix.rs) (0.7) | 166153.33 | 188.51 MB |
| rust (1.30) | [gotham](http://gotham.rs) (0.3) | 123480.67 | 252.38 MB |
| rust (1.30) | [iron](http://ironframework.io) (0.6) | 103540.67 | 130.68 MB |
| rust (1.30) | [nickel](http://nickel-org.github.io) (0.10) | 97582.67 | 193.97 MB |
| rust (nightly) | [rocket](http://rocket.rs) (0.3) | 25733.33 | 41.41 MB |

**Comment by waghanza** [comment]
This `PR` fix #447

**Comment by waghanza** [comment]
@whitfin I've update results 
https://github.com/the-benchmarker/web-frameworks#full-table

:warning: Still in **development** (all frameworks runs on `containers`)

**Pull request merged**
