### PR TITLE
[PHP] Fix ubiquity

### LINKED ISSUE #3702: Check ubiquity failure (404)

### PR DESCRIPTION
**Pull request by waghanza**
---
Closes #3702

### CODE REVIEW

**Comment by jcheron** [comment]
Hi @waghanza 
I think it's enough to add with composer:
- `ubiquity-attributes` for php 8.0
- `ubiquity-annotations` for php ^7.4

**Comment by waghanza** [comment]
You mean having a `composer` as
```json
{
  "require": {
    "phpmv/ubiquity": "~2.4.0",
    "phpmv/ubiquity-devtools": "*",
    "phpmv/ubiquity-annotations": "*"
  }
}
```

@jcheron ?

**Comment by jcheron** [comment]
For php7.4 
yes

**Comment by waghanza** [comment]
ok. however, I find having `phpmv/ubiquity-devtools` for **production** weird (because of the name) -> just a notice

**Comment by jcheron** [comment]
Logically, it should be:
```json
{
  "require": {
    "phpmv/ubiquity": "~2.4.0"
  },
  "require-dev": {
    "phpmv/ubiquity-devtools": "*",
    "phpmv/ubiquity-annotations": "*"
  }
}

**Comment by waghanza** [comment]
but how do you init cache in production ? do you mind open a `PR` ? I'm sure you have more `php` skills than me 😛

**Comment by jcheron** [comment]
> but how do you init cache in production ? do you mind open a `PR` ? I'm sure you have more `php` skills than me 😛

ok

**Comment by jcheron** [comment]
I'm gonna take a look to see what the problem is...

**Pull request closed without merging**
