### PR TITLE
New release

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

> Seems that those frameworks are CI ok, but KO on stress test , maybe a segfault at a certain streess level. Happy to review PR with debug enabled

+ handy
+ x.vweb

cc @cyrusmsk @enghitalo @medz @koplenov @TheVegeta @onanying

### CODE REVIEW

**Comment by enghitalo** [comment]
What command line do I use in wrk to reproduce the error in x.web? @casper64 @Casper64

**Comment by enghitalo** [comment]
xvweb, probably fixed on #7156

**Comment by medz** [comment]
Is dart also on the failed list?

**Comment by waghanza** [comment]
Nop @medz fry is ok

**Comment by cyrusmsk** [comment]
@waghanza do you know the error for handy?

**Comment by waghanza** [comment]
Nop @cyrusmsk , but maybe we can open a separated PR to debug. When a framework fails, I hide it (since we are still in some kind of beta)

**Comment by waghanza** [comment]
@enghitalo seems that the PR is not solving our issue here

**Pull request merged**
