### PR TITLE
[Java] Update javalin to 3.5

### PR DESCRIPTION
**Pull request by waghanza**
Hi @tipsy,

This `PR` update [javalin](https://javalin.io)

This time I've updated this framework manually.

Is there any way to have an automated process ?

Regard,

### CODE REVIEW

**Comment by tipsy** [comment]
> Is there any way to have an automated process ?

What do you mean?

**Comment by waghanza** [comment]
is there any bots tracking `java` dependency ?

for example, for `ruby` [dependabot](http://dependabot.io) make me a `PR` for each update on a `ruby` dependency

**Comment by waghanza** [comment]
my bad, `javalin` is configured in https://github.com/the-benchmarker/web-frameworks/blob/master/.dependabot/config.yml#L399

@dependabot the bot misses the update to **3.5** ?

**Comment by tipsy** [comment]
I've seen a bunch of PRs for Javalin created by @dependabot in the past (https://github.com/search?q=javalin+dependabot&type=Commits), not sure why it wouldn't pick up this one.

**Comment by waghanza** [comment]
probably the constraint `[3.4,3.5)` in https://github.com/the-benchmarker/web-frameworks/blob/master/java/javalin/pom.xml#L19 is not understandable by @dependabot then

**Pull request merged**
