### PR TITLE
New release

### PR DESCRIPTION
**Pull request by waghanza**
#### Missing

+ [ ] kore
+ [x] act
+ [x] chubbyts-uwebsockets
+ [x] oak-deno
+ [x] spliffy
+ [x] vixeny-bun
+ [ ] turbo
+ [x] dancer2
+ [x] httpz
+ [x] dream

### CODE REVIEW

**Comment by enghitalo** [comment]
There is time yet for https://github.com/the-benchmarker/web-frameworks/pull/7967 ?

**Comment by waghanza** [comment]
When using ` cpanm --installdeps . --with-feature=accelerate` with `dancer2`, I have
```perl
--> Working on Test::Pod
Fetching https://backpan.perl.org/authors/id/E/ET/ETHER/Test-Pod-1.52.tar.gz ... OK
Configuring Test-Pod-1.52 ... OK
Building and testing Test-Pod-1.52 ... OK
Successfully installed Test-Pod-1.52
Building and testing AppConfig-1.71 ... OK
Successfully installed AppConfig-1.71
Building and testing Template-Toolkit-3.102 ... OK
Successfully installed Template-Toolkit-3.102
! Installing the dependencies failed: Module 'Config::Any' is not installed
! Bailing out the installation for Dancer2-0.400001.
! Installing the dependencies failed: Module 'Dancer2' is not installed
! Bailing out the installation for ..
42 distributions installed
```
@SysPete

the **cpanfile** is
```perl
requires 'Dancer2', '>= 0.4, < 0.5';
```

any idea ?

**Comment by waghanza** [comment]
@enghitalo  I've nearly finish to repair some projects here, you can finish #7932 to take update train

**Comment by waghanza** [comment]
@mimiMonads could you check bun implementation for vixeny ?

**Comment by waghanza** [comment]
@aan When I am in the container, I have
```opam@cee8cacd2824:/usr/src/app$ dune exec --root . ./server.exe
bash: dune: command not found
```

the dockerfile I use is 
```dockerfile
FROM ocaml/opam:debian-12-ocaml-5.2

WORKDIR /usr/src/app

USER root
RUN apt-get update -y && apt-get install pkg-config libev-dev libssl-dev libgmp-dev -y
RUN apt-get -qy install curl
USER opam

  COPY 'server.opam' 'server.opam'
  COPY 'server.ml' 'server.ml'
  COPY 'dune' 'dune'
  COPY 'dune-project' 'dune-project'

  RUN opam install --deps-only --yes .



  ENTRYPOINT dune exec --root . ./server.exe

HEALTHCHECK CMD curl --fail http://0.0.0.0:3000 || exit 1
```

**Comment by waghanza** [comment]
@Kayden1412 for `zig`, I have

```
[+] Building 0.8s (5/5) FINISHED                                                                                                                                                                  docker:default
 => [internal] load build definition from .Dockerfile.default                                                                                                                                               0.0s
 => => transferring dockerfile: 448B                                                                                                                                                                        0.0s
 => CANCELED [internal] load metadata for docker.io/library/debian:latest                                                                                                                                   0.8s
 => ERROR [internal] load metadata for docker.io/chainguard/zig:latest                                                                                                                                      0.8s
 => [auth] library/debian:pull token for registry-1.docker.io                                                                                                                                               0.0s
 => [auth] chainguard/zig:pull token for registry-1.docker.io                                                                                                                                               0.0s
------
 > [internal] load metadata for docker.io/chainguard/zig:latest:
------
.Dockerfile.default:1
--------------------
   1 | >>> FROM chainguard/zig:latest AS build
   2 |
   3 |     WORKDIR /app
--------------------
ERROR: failed to solve: chainguard/zig:latest: failed to resolve source metadata for docker.io/chainguard/zig:latest: docker.io/chainguard/zig:latest: not found
```

**Comment by waghanza** [comment]
@dominikzogg for `chubbyts`, I can not use `uws` since its not compatible with node 22

**Comment by dominikzogg** [comment]
@waghanza i have to update that dependency. I am for holiday and will look into it next week.

**Comment by waghanza** [comment]
@greenlaw110 for `act`, I have
```java
/opt/web/runroot@6c4ef42303b6:/opt/web# /opt/web/run
  _    _         _                    _                  _  ___
 |_)  |_  |\ |  /   |_|  |\/|   /\   |_)  |/  __   /\   /    |
 |_)  |_  | \|  \_  | |  |  |  /--\  | \  |\      /--\  \_   |

                            powered by ActFramework r1.9.2-c4fe6

 version: unknown
scan pkg: benchmark.act
base dir: /opt/web
     pid: 19
 profile: prod
    mode: PROD
      OS: Linux
     jdk: OpenJDK 64-Bit Server VM 11

     zen: Beautiful is better than ugly.

                        -  Zen of Python

Exception in thread "main" java.lang.IllegalArgumentException
        at act.asm.ClassReader.<init>(ClassReader.java:170)
        at act.asm.ClassReader.<init>(ClassReader.java:153)
        at act.app.AppClassLoader.scanByteCode(AppClassLoader.java:314)
        at act.app.AppClassLoader.scan(AppClassLoader.java:266)
        at act.app.App.scanAppCodes(App.java:1868)
        at act.app.App.refresh(App.java:783)
        at act.app.AppManager.load(AppManager.java:77)
        at act.app.AppManager$_F$1.visit(AppManager.java:145)
        at act.app.AppManager$_F$1.visit(AppManager.java:141)
        at org.osgl.Lang$Visitor.apply(Lang.java:2462)
        at org.osgl.Lang$Visitor.apply(Lang.java:2452)
        at act.app.AppScanner.scan(AppScanner.java:91)
        at act.app.AppScanner.scan(AppScanner.java:71)
        at act.app.AppManager.loadSingleApp(AppManager.java:55)
        at act.Act.startup(Act.java:338)
        at act.Act.startup(Act.java:1322)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.base/java.lang.reflect.Method.invoke(Unknown Source)
        at org.osgl.Lang.invokeStatic(Lang.java:8150)
        at act.Act.bootstrap(Act.java:1221)
        at act.Act.start(Act.java:703)
        at benchmark.act.AppEntry.main(AppEntry.java:29)
```

**Comment by dominikzogg** [comment]
@waghanza hopefully it works with https://www.npmjs.com/package/@chubbyts/chubbyts-http-uwebsockets-bridge/v/1.2.4

**Pull request merged**
