### PR TITLE
[PHP] Adds BasicPHP nano-framework

### LINKED ISSUE #1775: BasicPHP
+ Language : PHP
+ Repo : https://github.com/ray-ang/basicphp
+ Author : Raymund John Ang
 
I would like to suggest to include BasicPHP framework in the benchmark. It is a fast, unopinionated and minimalist PHP nano-framework, and includes multitier architecture (JSON-RPC, REST-RPC and REST). Thank you.

### PR DESCRIPTION
**Pull request by ray-ang**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [x] A `Dockerfile` exists, or can be built ?
+ [x] I've updated `CI` config file (and **commited** `.travis.yml`)
~~~sh
bin/make ci_config
~~~
+ [x] I've updated `.dependabot` config file  (and **commited** `.dependabot/config.yml`)
~~~sh
bin/make deps_config
~~~
+ [x] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/make config
bin/neph ${FRAMEWORK}
crystal spec
~~~
-----------------
Closes #1775

### CODE REVIEW

**Comment by waghanza** [comment]
@ray-ang Thanks for you contribution, I will send you a `PR` for my recommendations 

Just a question, why naming your `basicphp` a `nano` **framework** ?

**Comment by ray-ang** [comment]
@waghanza, thanks. Full and micro-frameworks usually need composer and the usual third party packages to run. BasicPHP rely on vanilla PHP and built-in functions, no abstractions and conventions from composer packages. Apps created using BasicPHP, since uses PHP, can be embeded in full and microframeworks. That's why the term nano-framework.

**Comment by waghanza** [comment]
@ray-ang Ok. Understood the distinction but we could also avoid talking about a **framework**
it is a simple `pure` php implementation

**Comment by ray-ang** [comment]
@waghanza. Yes, it is a framework implemented in pure PHP. It is a framework that implements front-controlling and MVC. The classes, models, views and controllers folders can be autoloaded in the config.php file to implement MVC and extend functionality through classes.

**Comment by ray-ang** [comment]
@waghanza. I accepted your PR, made changes, and individually committed the file changes from my fork to main the-benchmarker/web-frameworks branch, and not create a new PR. I hope I did the right thing.

**Comment by waghanza** [comment]
I expect this `PR` not to be merge (since using **[WIP]**) but no real problem :stuck_out_tongue: 

Normally using **[WIP]** or **[DNM]** is a king of convention on `github`, as **WIP:** is a feature of `gitlab` in order to say that a `PR` (`MR` on  `gitlab`)  is not ready yet

**Comment by ray-ang** [comment]
Thanks for that one. WIP/DNM - Do Not Merge.

**Comment by waghanza** [comment]
but I have still an issue @see https://travis-ci.com/the-benchmarker/web-frameworks/jobs/235299959
the route `/user/0` return an empty body

**Comment by ray-ang** [comment]
I believe this is an issue with PATH_INFO and Nginx. I submitted a Dockerfile commit to hopefully fix this issue based on Nginx docs at: http://nginx.org/en/docs/http/ngx_http_fastcgi_module.html#fastcgi_split_path_info

**Comment by waghanza** [comment]
I've thought of that, but PATH_INFO is already present

This update add more issues https://travis-ci.com/the-benchmarker/web-frameworks/jobs/235323271

**Comment by ray-ang** [comment]
I reverted back to the Dockerfile you created, and added 'PATH_INFO' and 'REQUEST_URI' compatibility. The default URL_PARSE constant now is 'REQUEST_URI'. I hope this works in Nginx. I tested this in Apache, and no problems with using either 'PATH_INFO' or 'REQUEST_URI'.

**Comment by ray-ang** [comment]
@waghanza . I think there's no problem now - https://travis-ci.com/the-benchmarker/web-frameworks/jobs/235422111

**Pull request merged**
