### PR TITLE
chubbyphp/chubbyphp-framework 4.0 => 4.1

### PR DESCRIPTION
**Pull request by dominikzogg**
php 8 is min version

### CODE REVIEW

**Review by waghanza — COMMENTED** [review]
I suppose 8.0 @dominikzogg ?

`road-runner` is failing but this is not due to chubby

**Comment by dominikzogg** [comment]
@waghanza i changed the target branch, but it seems a master merge into renovate/php-8.x would be needed of a new PR (based on this branch) in the first place

**Comment by waghanza** [comment]
@dominikzogg 8.0 is on **master** and `renovate/php-8.x` is for 8.1, you choose

**Comment by dominikzogg** [comment]
@waghanza then i use master, code runs with 8.0 and 8.1

**Review by waghanza — CHANGES_REQUESTED** [review]
however, `config.yaml` is missing

**Comment by dominikzogg** [comment]
@waghanza thanks that you updated it yourself

**Pull request closed without merging**
