### PR TITLE
[Javascript] Add bun / deno for hono

### PR DESCRIPTION
**Pull request by waghanza**
Hi @bompus,

We can add `bun` and `deno` for `hono` like this.

Regards,

----------------------------

Closes https://github.com/the-benchmarker/web-frameworks/issues/7219

### CODE REVIEW

**Comment by waghanza** [comment]
Maybe I need a hand @yusukebe . I can not understand how to run `hono` on `bun`

**Comment by yusukebe** [comment]
@waghanza 

Hmm. I don't know a good way to make Bun and Deno support multi-core. I tried pm2 before, but it did not work well.

Or we can use Web Worker?

Bun and Deno are faster in single threaded environments, but in multi-core environments, Node.js apps clustered with pm2 are faster.

**Comment by SaltyAom** [comment]
AFAIK, on Bun you can use pm2 to spawn process equal to total thread on the server (which we already did by using `-i max`) and set `reusePort: true` which Bun will handle load-balancing automatically.

Here's from the definition of `Bun.serve`
```ts
    /**
     * If the `SO_REUSEPORT` flag should be set.
     *
     * This allows multiple processes to bind to the same port, which is useful for load balancing.
     *
     * @default false
     */
    reusePort?: boolean;
```

So instead of [maybe](https://hono.dev/getting-started/bun#change-port-number):
```ts
// from
export default app

// to
export default { 
  port: 3000,
  fetch: app.fetch,
  reusePort: true
}
```

Then just use PM2 to run Bun.

**Comment by yusukebe** [comment]
@SaltyAom @littledivy 

Thank you both!

But maybe I'm doing it wrong, but with pm2 only one process responds.

https://github.com/the-benchmarker/web-frameworks/assets/10682/6cbdc23b-4d46-4a66-8e16-639b6ce32a24

Code:

```ts
import { Hono } from 'hono'
import { logger } from 'hono/logger'

const app = new Hono()

app.use(logger())
app.get('/', (c) => c.text(''))

export default {
  port: 3000,
  fetch: app.fetch,
  reusePort: true
}
```

Command:

```
nohup pm2-runtime start "bun app.ts" -i 8
```

**Comment by waghanza** [comment]
> Then just use PM2 to run Bun.

But you need `node` to run `pm2`
```javascript
/usr/bin/env: 'node': No such file or directory
```

@SaltyAom

**Comment by waghanza** [comment]
With `cluster.js`, I do not require `nodejs` since this is a native solution for `bun`.

This solution perform slightly better
+ with `pm2`
```
Running 15s test @ http://127.0.0.1:3000
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   467.53us    1.29ms  58.40ms   97.39%
    Req/Sec    22.37k     6.23k   35.72k    73.41%
  2686326 requests in 15.10s, 192.14MB read
Requests/sec: 177893.60
Transfer/sec:     12.72MB
```
+ with `cluster.js`
```
Running 15s test @ http://127.0.0.1:3000
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   458.26us    1.28ms  58.78ms   97.43%
    Req/Sec    22.66k     6.63k   35.80k    73.38%
  2719641 requests in 15.10s, 194.52MB read
Requests/sec: 180107.27
Transfer/sec:     12.88MB
```

**Comment by waghanza** [comment]
I tried `pup` for `deno`, but
```
pup run --cmd "deno run --unstable-kv --allow-read=. --allow-net app.ts"
```
leads to
```
2024-02-15T20:28:21.938Z [LOG] [core:processes] Process 'task' loaded
Error while writing status to kv store: Deno.openKv is not a function
2024-02-15T20:28:21.940Z [LOG] [core:terminate] Termination requested
2024-02-15T20:28:21.940Z [LOG] [task:block] Process blocked, reason: terminating
Error while writing status to kv store: Deno.openKv is not a function
```

**Pull request merged**
