### PR TITLE
fix(adonis): remove not needed stuff

### PR DESCRIPTION
**Pull request by RomainLanz**
Hey there! 👋🏻 

This PR changes the current benchmark using AdonisJS.
It was doing way more than any other benchmark.

### CODE REVIEW

**Comment by RomainLanz** [comment]
I am unsure why it cannot find the `ace.js` file. It is copied at the root.

**Review by waghanza — APPROVED** [review]

**Review by waghanza — CHANGES_REQUESTED** [review]
missing `console.js` @RomainLanz 

https://github.com/the-benchmarker/web-frameworks/actions/runs/7912950857/job/21599649540?pr=7230#step:7:129

**Comment by waghanza** [comment]
`ace.js` could be found, but requires `console.js`
```javascript
STEP 21/31: RUN node ace.js build

node:internal/process/esm_loader:34
      internalBinding('errors').triggerUncaughtException(
                                ^
Error: Cannot find module '/usr/src/app/bin/console.js' imported from /usr/src/app/ace.js
    at finalizeResolution (/usr/src/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:366:11)
    at moduleResolve (/usr/src/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:801:10)
    at Object.defaultResolve (/usr/src/app/node_modules/ts-node/dist-raw/node-internal-modules-esm-resolve.js:912:11)
    at /usr/src/app/node_modules/ts-node/src/esm.ts:218:35
    at entrypointFallback (/usr/src/app/node_modules/ts-node/src/esm.ts:168:34)
    at /usr/src/app/node_modules/ts-node/src/esm.ts:217:14
    at addShortCircuitFlag (/usr/src/app/node_modules/ts-node/src/esm.ts:409:21)
    at resolve (/usr/src/app/node_modules/ts-node/src/esm.ts:197:12)
    at nextResolve (node:internal/modules/esm/hooks:865:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:303:30)
```

**Comment by thetutlage** [comment]
Its because, we are missing the `bin` directory in the `adonisjs-slim` directory

**Comment by RomainLanz** [comment]
Yup, I have added it back and removed some unneeded files.

**Comment by RomainLanz** [comment]
I am not sure what to put under the `files` of the `config.yaml`. Any help would be appreciated @waghanza

**Comment by waghanza** [comment]
In the `files` key from the config file, you need to put the relative path of each file needed into the container, by default the `js` `ts` and `package.json` are uploaded into the container (if they exist).

Which file do you expect to have on the container?

PS : It supports globbing, `*.ts` and `*/*/*/*.js`

**Comment by waghanza** [comment]
But I'm not sure it is about the file, but about the Japa module not installed (and imho not needed)

https://github.com/the-benchmarker/web-frameworks/actions/runs/8018305452/job/21903951717#step:7:148

**Review by waghanza — APPROVED** [review]

**Pull request merged**
