### PR TITLE
Be more restictive on route /user/0

### PR DESCRIPTION
**Pull request by mfirry**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [ ] Please check configuration files
   + [ ] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [ ] `FRAMEWORKS.yml`, for **frameworks** list
   + [ ] `travis.yml`, for CI
+ [ ] A `Dockerfile` exists ?
+ [ ] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~

### CODE REVIEW

**Comment by waghanza** [comment]
Yeah, thanks.

However, could you remade this `PR` from a **non-master** branch ?

**Comment by mfirry** [comment]
yes. which branch?

**Comment by waghanza** [comment]
Any branch on your fork 😉 so as I can push on it

**Comment by mfirry** [comment]
Why would you need to push on my branch? I don't understand.

**Comment by mfirry** [comment]
You can close this PR, fork my fork and do what you need to do

**Comment by waghanza** [comment]
ok, I'll try to do this :stuck_out_tongue: 

In fact, I want to :
+ homogenize all frameworks implementations here, not only work on `scala`
+ have you as participant not to forget you when releasing

**Pull request closed without merging**
