### PR TITLE
[PHP] Use roadrunner 2.x

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

The last version of `roarunner` is unusable on **alpine**

However, the previous version (**2.4**) works.

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
I managed to the same version for `slim` / `chubbyphp` / `sunrise-router` -> `rr version 2.5.3 (build time: 2021-10-27T13:17:28+0000, go1.17.2)`

However, surprisingly it could works some of the time, and sometime I have the following stacktrace  :

```go
panic: reflect: Call using zero Value argument

goroutine 1 [running]:
reflect.Value.call({0xc00009e500, 0xc00018a778, 0x0}, {0x17222dd, 0x4}, {0xc0007f3320, 0x4, 0x0})
        reflect/value.go:406 +0x19db
reflect.Value.Call({0xc00009e500, 0xc00018a778, 0x19a32a0}, {0xc0007f3320, 0x4, 0x4})
        reflect/value.go:339 +0xc5
github.com/spiral/endure/pkg/container.(*Endure).callInitFn(0xc000128540, {{0x13fdc98, 0x4}, {0x0, 0x0}, {0x19a32a0, 0xc00009e500}, {0xc00009e500, 0xc00018a778, 0x13}, ...}, ...)
        github.com/spiral/endure@v1.0.6/pkg/container/init.go:53 +0x133
github.com/spiral/endure/pkg/container.(*Endure).internalInit(0xc000128540, 0xc0007e7340)
        github.com/spiral/endure@v1.0.6/pkg/container/init.go:26 +0x129
github.com/spiral/endure/pkg/container.(*Endure).Initialize(0xc000128540)
        github.com/spiral/endure@v1.0.6/pkg/container/endure.go:398 +0x910
reflect.Value.call({0xc0000b3f20, 0xc0000b08c8, 0x7f9fbe169108}, {0x17222dd, 0x4}, {0xc00064b3b0, 0x1, 0xc0006abef0})
        reflect/value.go:543 +0x814
reflect.Value.Call({0xc0000b3f20, 0xc0000b08c8, 0x0}, {0xc00064b3b0, 0x1, 0x1})
        reflect/value.go:339 +0xc5
github.com/spiral/endure/pkg/fsm.(*FSMImpl).Transition(0xc00064afd8, 0x0, {0xc00027f0b0, 0x1, 0x5})
        github.com/spiral/endure@v1.0.6/pkg/fsm/fsm.go:180 +0x3b5
github.com/spiral/endure/pkg/container.(*Endure).Init(...)
        github.com/spiral/endure@v1.0.6/pkg/container/endure.go:308
github.com/spiral/roadrunner-binary/v2/internal/cli/serve.NewCommand.func1(0xc000698000, {0x1722801, 0x0, 0x0})
        github.com/spiral/roadrunner-binary/v2/internal/cli/serve/command.go:52 +0x3bc
github.com/spf13/cobra.(*Command).execute(0xc000698000, {0x2584958, 0x0, 0x0})
        github.com/spf13/cobra@v1.2.1/command.go:856 +0x60e
github.com/spf13/cobra.(*Command).ExecuteC(0xc000695680)
        github.com/spf13/cobra@v1.2.1/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.2.1/command.go:902
main.run()
        github.com/spiral/roadrunner-binary/v2/cmd/rr/main.go:22 +0x4a
main.main()
        github.com/spiral/roadrunner-binary/v2/cmd/rr/main.go:16 +0x19
```

**Comment by waghanza** [comment]
Maybe fixed in https://github.com/spiral/endure/pull/105 @wolfy-j @rustatian

**Review by dominikzogg — DISMISSED** [review]

**Comment by waghanza** [comment]
> Maybe fixed in [spiral/endure#105](https://github.com/spiral/endure/pull/105) @wolfy-j @rustatian

This patch has been released in the last version, but still failing @dominikzogg

**Comment by dominikzogg** [comment]
@waghanza dropping this line is probably the issue:

`use Psr\Http\Message\ServerRequestInterface;`

**Pull request merged**
