### PR TITLE
Update results

### PR DESCRIPTION
**Pull request by waghanza**
This `PR` update results

@jwoertink its add `lucky`

###### Failing frameworks

-  archttp
-  kitura
-  jennet
-  cyclone
-  nawa
-  fyrejet-uwebsockets
-  naturaljs-router

### CODE REVIEW

**Comment by waghanza** [comment]
@bloodbare @vangheem @masipcat With `guillotina` **6.4.2**, I have 
```python
[2023-03-18 13:13:30 +0000] [9] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/server.py", line 1, in <module>
    from guillotina import configure
  File "/usr/local/lib/python3.11/site-packages/guillotina/__init__.py", line 2, in <module>
    from guillotina import glogging
  File "/usr/local/lib/python3.11/site-packages/guillotina/glogging.py", line 1, in <module>
    from guillotina import task_vars
  File "/usr/local/lib/python3.11/site-packages/guillotina/task_vars.py", line 2, in <module>
    from guillotina.db.interfaces import ITransaction
  File "/usr/local/lib/python3.11/site-packages/guillotina/db/interfaces.py", line 2, in <module>
    from guillotina.interfaces import ICatalogDataAdapter
  File "/usr/local/lib/python3.11/site-packages/guillotina/interfaces/__init__.py", line 9, in <module>
    from .behaviors import IAsyncBehavior  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/guillotina/interfaces/behaviors.py", line 1, in <module>
    from guillotina import schema
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/__init__.py", line 18, in <module>
    from guillotina.schema._field import ASCII
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/_field.py", line 40, in <module>
    from guillotina.schema.fieldproperty import FieldProperty
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/fieldproperty.py", line 15, in <module>
    from guillotina import event
  File "/usr/local/lib/python3.11/site-packages/guillotina/event.py", line 1, in <module>
    from guillotina.component.event import async_subscribers
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/__init__.py", line 15, in <module>
    from guillotina.component._api import get_adapter
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/_api.py", line 14, in <module>
    from guillotina.component import globalregistry
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/globalregistry.py", line 15, in <module>
    from guillotina.component.interfaces import IComponentLookup
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/interfaces.py", line 19, in <module>
    from zope.interface import implements
ImportError: cannot import name 'implements' from 'zope.interface' (/usr/local/lib/python3.11/site-packages/zope/interface/__init__.py)
[2023-03-18 13:13:30 +0000] [10] [ERROR] Exception in worker process
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/gunicorn/arbiter.py", line 589, in spawn_worker
    worker.init_process()
  File "/usr/local/lib/python3.11/site-packages/uvicorn/workers.py", line 66, in init_process
    super(UvicornWorker, self).init_process()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 134, in init_process
    self.load_wsgi()
  File "/usr/local/lib/python3.11/site-packages/gunicorn/workers/base.py", line 146, in load_wsgi
    self.wsgi = self.app.wsgi()
                ^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/base.py", line 67, in wsgi
    self.callable = self.load()
                    ^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 58, in load
    return self.load_wsgiapp()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/app/wsgiapp.py", line 48, in load_wsgiapp
    return util.import_app(self.app_uri)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/gunicorn/util.py", line 359, in import_app
    mod = importlib.import_module(module)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1149, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 690, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/usr/src/app/server.py", line 1, in <module>
    from guillotina import configure
  File "/usr/local/lib/python3.11/site-packages/guillotina/__init__.py", line 2, in <module>
    from guillotina import glogging
  File "/usr/local/lib/python3.11/site-packages/guillotina/glogging.py", line 1, in <module>
    from guillotina import task_vars
  File "/usr/local/lib/python3.11/site-packages/guillotina/task_vars.py", line 2, in <module>
    from guillotina.db.interfaces import ITransaction
  File "/usr/local/lib/python3.11/site-packages/guillotina/db/interfaces.py", line 2, in <module>
    from guillotina.interfaces import ICatalogDataAdapter
  File "/usr/local/lib/python3.11/site-packages/guillotina/interfaces/__init__.py", line 9, in <module>
    from .behaviors import IAsyncBehavior  # noqa
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/guillotina/interfaces/behaviors.py", line 1, in <module>
    from guillotina import schema
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/__init__.py", line 18, in <module>
    from guillotina.schema._field import ASCII
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/_field.py", line 40, in <module>
    from guillotina.schema.fieldproperty import FieldProperty
  File "/usr/local/lib/python3.11/site-packages/guillotina/schema/fieldproperty.py", line 15, in <module>
    from guillotina import event
  File "/usr/local/lib/python3.11/site-packages/guillotina/event.py", line 1, in <module>
    from guillotina.component.event import async_subscribers
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/__init__.py", line 15, in <module>
    from guillotina.component._api import get_adapter
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/_api.py", line 14, in <module>
    from guillotina.component import globalregistry
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/globalregistry.py", line 15, in <module>
    from guillotina.component.interfaces import IComponentLookup
  File "/usr/local/lib/python3.11/site-packages/guillotina/component/interfaces.py", line 19, in <module>
    from zope.interface import implements
ImportError: cannot import name 'implements' from 'zope.interface' (/usr/local/lib/python3.11/site-packages/zope/interface/__init__.py)
[2023-03-18 13:13:30 +0000] [8] [WARNING] Worker with pid 11 was terminated due to signal 15
[2023-03-18 13:13:30 +0000] [8] [WARNING] Worker with pid 10 was terminated due to signal 15
```
when running with
```
gunicorn \
  --log-level warning \
  --bind 0.0.0.0:3000 \
  --reuse-port \
  --workers $(nproc) \
  --worker-class uvicorn.workers.UvicornWorker \
    server:app
```

**Comment by masipcat** [comment]
@waghanza try pinning the library `zope.interface` to version <6.0

**Comment by waghanza** [comment]
Thanks @masipcat, seems that we need to pin it in https://github.com/plone/guillotina/blob/master/setup.py#LL66C15-L66C24 ❤️

**Comment by masipcat** [comment]
Yeah, but until we fix it in Guillotina we can pin it here: https://github.com/the-benchmarker/web-frameworks/blob/master/python/guillotina/requirements.txt

**Comment by waghanza** [comment]
Yes, the results are updated with this patch (not pushed yet tho)

**Pull request merged**
