### PR TITLE
[java/kotlin] jooby implementation

### LINKED ISSUE #2507: Add jobby
Hi @jknack ,

Would you mind to add (or consent that we add) [jooby](https://github.com/jooby-project/jooby) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

### PR DESCRIPTION
**Pull request by jknack**
- Added the Kotlin version too (kooby)

--------------
Edit : Closes #2507

### CODE REVIEW

**Comment by jknack** [comment]
updated:
- removed gradle wrapper
- set version to 2.8 on config.yaml
- set version to 2.8.+ on build.gradle (was not possible to do that same with kotlin, I got: `Plugin [id: 'org.jetbrains.kotlin.jvm', version: '1.3.+'] was not found in any of the following sources:
`)
- added jooby and kooby to .travis.yaml
- added jooby and kooby to .dependabot/config.yaml

**Comment by jknack** [comment]
- set port to 3000

**Comment by waghanza** [comment]
@jknack do you mind if I write un your `PR` ?

**Comment by jknack** [comment]
No, don't care. Go for it

**Comment by waghanza** [comment]
Do you mind then to invite me @jknack. I've not right to push, since it's a group repository

**Comment by jknack** [comment]
just added you

**Pull request closed without merging**
