### PR TITLE
Next update

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` will update results. 

@SuspiciousLookingOwl CI will run (for all frameworks) when `data.json` is updated (which was not the case previously).

## To update

+ [x] `laravel`
+ [x] `spring`
+ [x] `finatra`
+ [x] `restheart`

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
failing in https://the-benchmarker.semaphoreci.com/jobs/50e68ec3-6ae3-4e65-bada-6c3ad9ff0824#L389

probably related to https://github.com/the-benchmarker/web-frameworks/blob/master/javascript/Dockerfile#L1

/cc @kamilmysliwiec

**Comment by waghanza** [comment]
`blacksheep` fails at https://the-benchmarker.semaphoreci.com/jobs/0f8d3c00-36b0-470a-8b26-8db1227112f6#L418

/cc @RobertoPrevato

**Comment by waghanza** [comment]
`apidaora` fails at https://the-benchmarker.semaphoreci.com/jobs/c92037df-c2a9-4470-a317-749241845444#L653

/cc @dutradda

**Comment by waghanza** [comment]
`guillotina` is failing at https://the-benchmarker.semaphoreci.com/jobs/9dbc53a1-c75f-4208-ae3c-478c35ac3e05#L746

/cc @bloodbare

**Comment by waghanza** [comment]
@whiplash I think I need you for https://the-benchmarker.semaphoreci.com/jobs/337a66a6-6c15-405d-a742-96b62c029370#L348

**Comment by whiplash** [comment]
See #4346

**Comment by waghanza** [comment]
@kelvinst @Sgiath @Ch4s3 @OvermindDL1 could you give me a hand for **elixir** `frameworks` in here ?
see https://the-benchmarker.semaphoreci.com/jobs/2b40bd11-5ccb-4bc7-9e8f-f7afa143bcc5 for `cowboy`

**Comment by OvermindDL1** [comment]
That error implies that the beam was compiled for a newer system version than what it's running in?  How did that happen?!

**Comment by waghanza** [comment]
🤷🏻  

---------

I switch to **debian-slim**

---------

A better solution will be to follow **elixir** `community` usages (use dist that most devs use in **production**), but I am not able to answer this 😛

**Comment by OvermindDL1** [comment]
> A better solution will be to follow elixir community usages (use dist that most devs use in production), but I am not able to answer this stuck_out_tongue

For docker images that is overwhelmingly the official images:  https://hub.docker.com/_/elixir

**Comment by waghanza** [comment]
ok, so I've taken a good decision ❤️

**Pull request merged**
