### PR TITLE
optimize amber

### PR DESCRIPTION
**Pull request by drujensen**
This does several things to provide a better comparison:
- disable logging
- removes all unnecessary middleware
- enables port_reuse
- sets number of processes to 7 to leverage the 8 cores

This addresses issue #483

### CODE REVIEW

**Comment by waghanza** [comment]
I was trying to enable `reuse_port` on https://github.com/the-benchmarker/web-frameworks/pull/284, but seems to take time

I'm glad you did :heart:

**Comment by waghanza** [comment]
@proyb6 the `amber` implementation on **tfb** use `1 CPU (core)` 

@drujensen we can not write a `static` number as `amber` process count. **official** rounds will run on 8 CPU env, but devs could want to run on 1 CPU. I've set process count **dynamic** (in `env`)

**Comment by waghanza** [comment]
|   | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| here | [amber](http://amberframework.org) (0.9) | 36.49 ms | 35.10 ms | 47.14 ms | 76.63 ms | 409.67 ms | 21775.00 |
| master| [amber](http://amberframework.org) (0.9) | 36.11 ms | 30.58 ms | 48.70 ms | 145.97 ms | 774.06 ms | 34394.67 | 

@drujensen For me this is more performant, since **Standard deviation** decrease. But to be sure we have to wait until running on `cloud`

PS : Those data are not calculated from the same environment as on `README`

**Comment by drujensen** [comment]
@proyb6 The TechEmpower benchmarks is using a `run.sh` that all of the crystal projects are using.  I created that before we added the feature to Amber.  We just never went back and changed it to use this built-in feature.

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/amber/run.sh

**Comment by drujensen** [comment]
@waghanza Thanks for merging.  Rust Nickel is bare bones.  Have you considered doing a Crystal Standard library version to match?  Or does this benchmark require a router?

**Comment by proyb6** [comment]
@drujensen Is there an alternative libraries you would prefer to choose HTTP in C instead? As we all can use the standard libraries, we need a universal routers for Crystal web frameworks.

**Comment by drujensen** [comment]
> As we all can use the standard libraries, we need a universal routers for Crystal web frameworks.

@proyb6 right.  Just wondering what this benchmark is trying to achieve. 

> However, when youy say that nickel is barebone, could you give me more details about that ?

@waghanza What I mean is that rust/nickel is using a very simple middleware to handle routing.  Just wondering what the requirements for this benchmark are.

For example, you could do something like this:
```crystal
require "http/server"

server = HTTP::Server.new do |context|
   context.response.print ""
end

server.listen("0.0.0.0", 8080, reuse_port: true)
```
 
I think this will pass this benchmark since there is no criteria for what should be returned from each path.   To leverage the `reuse_port`, you would need to launch multiple processes like this: https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/crystal/run.sh

You could also add some conditional logic based on path/method to provide a different response if that was part of the criteria.  This is the simplest way to perform routing.  You can see an example here:

https://github.com/TechEmpower/FrameworkBenchmarks/blob/master/frameworks/Crystal/crystal/server.cr#L16

TechEmpower asks you if you are a fullstack/micro/platform to make it clear what's included when you perform comparisons between frameworks.

**Comment by waghanza** [comment]
@drujensen  `router.cr` is also very simple, as `orion` ...

The goal here is :
+ To show performance (on a **real** usage)
+ To show how to write (according to each `language` best practices)
+ To show details (ressources comsumption, implementation choice ...)

**Comment by proyb6** [comment]
In additional, adding Parallel.cr will parallelize if you like to add.
```
require "parallel"

pspawn do
   get "/" ...
end
```

**Comment by waghanza** [comment]
@proyb6 seems to specific for me :stuck_out_tongue_closed_eyes: 

I mean parallelism is a `core` task (not a `framework` one), and I'm sure this will be on `crystal` `1.0`

**Comment by drujensen** [comment]
@waghanza yeah, regarding router.cr and orion, both are very simple probably more on par with the nickel example.

Regarding goals, so there is no goal to have an apples-to-apples comparison? The goal is to compare real usage performance?  

Obviously, each will have more or less features that will impact the performance.  Amber out the box tries to do everything for you.  There are 10+ middleware included.  https://github.com/amberframework/amber/tree/master/src/amber/pipes 

I removed them, but maybe we should put them back because in a real usage situation, you would have logging, csrf, error, flash, session, static, and possibly cors if your building an API.  WDYT?

**Comment by waghanza** [comment]
@drujensen Actually, we have 3 rules (endpoints needed).

We want to test frameworks on this basis, to have a fair (most we can) comparison, and then avoid apple-to-orange comparison

**Pull request merged**
