### PR TITLE
Remove binary stripping

### PR DESCRIPTION
**Pull request by Kayden1412**
@waghanza can you try compiling it again with binary stripping removed?

### CODE REVIEW

**Comment by Kayden1412** [comment]
Can you send the error message

**Comment by waghanza** [comment]
+ `zig build`
```
thread 26 panic: reached unreachable code
Panicked during a panic. Aborting.
error: the following build command crashed:
/app/.zig-cache/o/0569e2d413424966c9e4f413dd073d7e/build /usr/bin/zig /app /app/.zig-cache /root/.cache/zig --seed 0x855d6f8d -Z614e92966cd544db
```

**Comment by waghanza** [comment]
yes, I see compilation stage on the console, but it is rewritten each time 

is their a way to create a compilation log ?

**Comment by waghanza** [comment]
Ok, then I can follow this issue, and as I understand this will be fixed on the next release of zig

**Pull request merged**
