### PR TITLE
Introduce falcon

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` introduce [falcon](http://falcon.readthedocs.io), related to #539 

## If you are adding a framework

+ [x] Please check configuration files
   + [x] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [x] `FRAMEWORKS.yml`, for **frameworks** list
   + [x] `travis.yml`, for CI
+ [x] A `Dockerfile` exists ?
+ [x] All tests passes ?
~~~
export FRAMEWORK=falcon
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~

@kgriffs  Can you do a quick review on this code ?

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
On my workstation (8 CPU), I have :

| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| python (3.6) | [japronto](http://github.com/squeaky-pl/japronto) (1.1) | 4.74 ms | 3.98 ms | 9.69 ms | 17.45 ms | 52.66 ms | 3923.00 | 
| python (3.6) | [vibora](http://vibora.io) (0.0) | 6.14 ms | 5.46 ms | 11.46 ms | 18.85 ms | 47.52 ms | 4063.67 | 
| python (3.7) | [falcon](http://falconframework.org) (1.4) | 15.13 ms | 10.80 ms | 30.11 ms | 56.79 ms | 183.95 ms | 11492.33 | 
| python (3.7) | [bottle](http://bottlepy.org) (0.12) | 18.83 ms | 13.10 ms | 39.69 ms | 77.86 ms | 204.35 ms | 15411.00 | 
| python (3.7) | [aiohttp](http://aiohttp.readthedocs.io) (3.4) | 34.02 ms | 31.40 ms | 53.65 ms | 81.33 ms | 188.35 ms | 15105.00 | 
| python (3.7) | [flask](http://flask.pocoo.org) (1.0) | 49.76 ms | 33.84 ms | 97.07 ms | 147.82 ms | 338.68 ms | 30925.67 | 
| python (3.7) | [sanic](http://github.com/huge-success/sanic) (0.8) | 54.76 ms | 52.20 ms | 79.07 ms | 118.62 ms | 238.93 ms | 19924.00 | 
| python (3.7) | [django](http://djangoproject.com) (2.1) | 75.59 ms | 63.18 ms | 138.88 ms | 190.70 ms | 727.01 ms | 39805.67 | 
| python (3.7) | [tornado](http://tornadoweb.org) (5.1) | 103.65 ms | 102.77 ms | 122.29 ms | 164.46 ms | 909.92 ms | 37926.67 | 
| python (3.7) | [quart](http://pgjones.gitlab.io/quart) (0.6) | 111.17 ms | 104.20 ms | 176.96 ms | 257.01 ms | 691.09 ms | 53558.33 |

**Comment by greed2411** [comment]
I just encountered this framework yesterday.  If you want we can even try this framework, https://github.com/kennethreitz/responder

**Comment by waghanza** [comment]
@greed2411 feel free to add `responder` :heart:

**Comment by greed2411** [comment]
@waghanza will create an issue and start working on it right away.

**Pull request merged**
