### PR TITLE
Add chubbyts

### PR DESCRIPTION
**Pull request by dominikzogg**

### CODE REVIEW

**Comment by dominikzogg** [comment]
@waghanza is there anything missing/wrong?

**Comment by waghanza** [comment]
@dominikzogg not sure this kind of framework deserves to be in `javascript` folder, but maybe a `typescript` folder like https://github.com/TechEmpower/FrameworkBenchmarks

let's use this PR to start discuss with `javascript` folks

wdyt @jkyberneees @schamberg97 @dalisoft ?

**Comment by dalisoft** [comment]
@waghanza I agree with @dominikzogg. We can use typescript projects in javascript folder

**Comment by waghanza** [comment]
then maybe `chubby` will be compliant with deno somehow

**Review by waghanza — APPROVED** [review]

**Comment by dominikzogg** [comment]
deno support is not planed, i dislike the concept cause it mixes up runtime and dependency management.

**Comment by dominikzogg** [comment]
@waghanza thanks for merging

**Pull request merged**
