### PR TITLE
upgrade version for axum & warp

### PR DESCRIPTION
**Pull request by krishnaTORQUE**

### CODE REVIEW

**Review by waghanza — APPROVED** [review]
LGTM

Maybe we should have the same compilation options between each `rust` frameworks

**Comment by krishnaTORQUE** [comment]
> LGTM
> 
> Maybe we should have the same compilation options between each `rust` frameworks

Yes correct. Its does make impact on the performance.

**Comment by waghanza** [comment]
I let you make the changes here @krishnaTORQUE 🙏🏻

**Comment by krishnaTORQUE** [comment]
> I let you make the changes here @krishnaTORQUE 🙏🏻

Sure I will 😉

**Comment by waghanza** [comment]
I'll merge this, to update results

Feel free to open an other PR @krishnaTORQUE

**Comment by krishnaTORQUE** [comment]
> I let you make the changes here @krishnaTORQUE 🙏🏻

PR raised https://github.com/the-benchmarker/web-frameworks/pull/6303

**Pull request merged**
