### PR TITLE
Update Foxify

### PR DESCRIPTION
**Pull request by ardalanamini**

### CODE REVIEW

**Comment by waghanza** [comment]
Fix #604

**Comment by waghanza** [comment]
@ardalanamini You are awesome :heart: 

However, could you made updates `PR` , from branches

I can, then modify them :stuck_out_tongue: in case of other modification to do

**Comment by ardalanamini** [comment]
Fixed #604

**Comment by ardalanamini** [comment]
Foxify by default creates clusters according to number of cpu cores
so `.set("workers", 1)` says not to that
this option is useful when using pm2

**Pull request closed without merging**
