### PR TITLE
[Java] Update light4j to 2.0

### PR DESCRIPTION
**Pull request by waghanza**
Hi @stevehu @tsuilouis,

This `PR` update https://github.com/networknt/light-4j to **2.0**

As I notice we have to compile targeted VM, right ?

Regards,

### CODE REVIEW

**Comment by stevehu** [comment]
I thought we had agreed to stay with 1.6.x release as it is using Java 8 which is consistent with other frameworks. What do you think?

**Comment by waghanza** [comment]
Indeed. However `act` could be used with `java` **11** (with last release), so I'm upgrading all `java` **frameworks** in https://github.com/the-benchmarker/web-frameworks/pull/3101 which this `PR` target :heart:

**Comment by stevehu** [comment]
Got it. It is a good move to go with Java 11. Most of our users are using Java 11 these days.

**Comment by waghanza** [comment]
The their is no change needed ? I mean this `PR` is OK ?

**Comment by stevehu** [comment]
Should be OK if the maven command is OK.

**Pull request merged**
