### PR TITLE
Update on 7th of February 2024

### PR DESCRIPTION
**Pull request by waghanza**
Hi @cyrusmsk @koplenov @enghitalo,

All `V` and `D` are failing => compilation issue

it's from `stdlib` in `v`
```v
33.24 ./v1.exe -no-parallel -o v2.exe  cmd/v
34.37 vlib/strconv/f32_str.c.v:35:2: error: value `10000000000` overflows `u32`
34.37    33 |     u32(100000000),
34.37    34 |     u32(1000000000),
34.37    35 |     u32(10000000000),
34.37       |     ~~~~~~~~~~~~~~~~
34.37    36 |     u32(100000000000),
34.37    37 | ]!
34.37 vlib/strconv/f32_str.c.v:36:2: error: value `100000000000` overflows `u32`
34.37    34 |     u32(1000000000),
34.37    35 |     u32(10000000000),
34.37    36 |     u32(100000000000),
34.37       |     ~~~~~~~~~~~~~~~~~
34.37    37 | ]!
34.37    38 |
34.39 make: *** [GNUmakefile:114: all] Error 1
------
.Dockerfile.default:22
--------------------
  20 |       COPY 'main.v' 'main.v'
  21 |     
  22 | >>>   RUN cd /opt/vlang && git fetch --all --tags && git checkout tags/weekly.2024.03 && make && v -version && cd /app
  23 |     
  24 |     RUN v .  -prod -cc clang  -o server
--------------------
```

and for `D`

```d
177.3 Using Linux EPOLL for events
177.7 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/internals/logging.d(13,32): Error: undefined identifier `stdout`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(119,25): Deprecation: returning `cast(msghdr*)&this.m_header` escapes a reference to parameter `this`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(118,20):        perhaps annotate the function with `return`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(924,14): Deprecation: returning `&this.addr_ip4` escapes a reference to parameter `this`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(922,32):        perhaps annotate the function with `return`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(928,14): Deprecation: returning `&this.addr_ip6` escapes a reference to parameter `this`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(926,33):        perhaps annotate the function with `return`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(933,14): Deprecation: returning `&this.addr_un` escapes a reference to parameter `this`
179.6 /root/.dub/packages/libasync-0.9.5/libasync/source/libasync/socket.d(931,32):        perhaps annotate the function with `return`
179.7 ldc2 failed with exit code 1.
```

### CODE REVIEW

**Comment by cyrusmsk** [comment]
For lighttp you need to remove dub.selections file and it should work.
@waghanza

**Comment by enghitalo** [comment]
Thank @waghanza. I will take a look soon

**Comment by waghanza** [comment]
> dub.selections

their is no such file @cyrusmsk

**Comment by cyrusmsk** [comment]
I think it’s better to stick with stable version 0.4 now?

**Comment by cyrusmsk** [comment]
> > dub.selections
> 
> their is no such file @cyrusmsk

Can you check that it was not cached in building machine?
Usual path ~/.dub/packages/
Otherwise we can try to add “dub build -b=release —force”
To force rebuilding of the package.
There is newer version of dependency libasync. Previously I used “master” version in dub.selection - but now it has newer version 9.5 which is working. But master is broken with latest PR)

**Comment by koplenov** [comment]
https://github.com/the-benchmarker/web-frameworks/pull/7198 should fix V

**Pull request merged**
