### PR TITLE
[PHP] Add workerman

### LINKED ISSUE #1926: Add workerman
Hi @walkor,

Would you mind to add (or consent that we add) [workerman](https://github.com/walkor/Workerman) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

### PR DESCRIPTION
**Pull request by walkor**
For https://github.com/the-benchmarker/web-frameworks/issues/1926

Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [ ] A `Dockerfile` exists, or can be built ?
+ [x] I've updated `CI` config file (and **commited** `.travis.yml`)
~~~sh
bin/make ci_config
~~~
+ [x] I've updated `.dependabot` config file  (and **commited** `.dependabot/config.yml`)
~~~sh
bin/make deps_config
~~~
+ [x] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/make config
bin/neph ${FRAMEWORK}
crystal spec
~~~

-------------
edit : Closes #1926

### CODE REVIEW

**Comment by waghanza** [comment]
@walkor I can (since this `PR` from **master**) push directly, so I'll send you a `PR` on it

**Comment by waghanza** [comment]
@walkor could you `rebase` or run 
~~~
shards install
shards build
bin/make ci_config
bin/make deps_config
~~~ 
so as I can merge ?

**Comment by walkor** [comment]
OK. I will do that later.

**Comment by waghanza** [comment]
@walkor Could you `rebase` an other time ? or give me **right** access to you fork (:warning: **master** is protected by default) ?

**Comment by walkor** [comment]
OK , I will rebase an other time.------------------ 原始邮件 ------------------
发件人: "Marwan Rabb&#xE2;a"<notifications@github.com>
发送时间: 2019年10月30日(星期三) 上午6:09
收件人: "the-benchmarker/web-frameworks"<web-frameworks@noreply.github.com>;
抄送: "walkor"<worker-man@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [the-benchmarker/web-frameworks] [PHP] Add workerman (#1941)



@walkor Could you rebase an other time ? or give me right access to you fork (&#xFE0F; master is protected by default) ?
 
&mdash;

**Pull request merged**
