### PR TITLE
[Ruby] Adds syro to the benchmarks

### PR DESCRIPTION
**Pull request by elcuervo**
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [x] A `Dockerfile` exists, or can be built ?
+ [x] I've updated `CI` config file (and **commited** `.travis.yml`)
~~~sh
bin/make ci_config
~~~
+ [x] I've updated `.dependabot` config file  (and **commited** `.dependabot/config.yml`)
~~~sh
bin/make deps_config
~~~
+ [x] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/make config
bin/neph ${FRAMEWORK}
crystal spec
~~~

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks @elcuervo. Hi @soveran, do you consent including`syro` here ?

**Comment by waghanza** [comment]
Hi @elcuervo, I've update results
https://github.com/elcuervo/web-frameworks/tree/add-syro#ranking-top-5

but I will merge only after @soveran consent (or any member with write access)

**Comment by soveran** [comment]
@waghanza Yes, I give my consent to anything done by @elcuervo! Thanks a lot!

**Comment by waghanza** [comment]
@elcuervo ready when you are

**Comment by elcuervo** [comment]
Thank you for your help @waghanza!!
And thank you @soveran for the support and beautiful ruby code!

**Pull request merged**
