### PR TITLE
[Javascript] Use turbo-way of response on nanoexpress

### PR DESCRIPTION
**Pull request by dalisoft**
Update nanoexpress route

### CODE REVIEW

**Comment by waghanza** [comment]
@dalisoft What does `isRaw` make ?

**Comment by dalisoft** [comment]
`isRaw` is for advanced users and will improve performance at cost some polypill features which does not need for basic examples

**Comment by waghanza** [comment]
@dalisoft With the last version (`0.12.11`), I have 
~~~javascript
App.listen requires port and callback
~~~
just after startup

**Comment by dalisoft** [comment]
@waghanza I will check why it happens, but for me _it works good locally_ (this words love most developers 😄 )

**Comment by dalisoft** [comment]
@waghanza Thanks for reporting, it's strange Travis CI doesn't report about this as I am configured everything. I fixed bug in v0.12.12

**Comment by waghanza** [comment]
@dalisoft I have to refactor CI ;-) having a double entry matrix on travis is no very efficient, since entry **#2** (test) do not run if **#1** (lint) fails

**Comment by dalisoft** [comment]
@waghanza your repo is okay, i mean i already configured Travis CI on nanoexpress repo and CI does not reported about issue

**Pull request merged**
