### PR TITLE
[D]: Add DC variable for preGeneratedCommand in deimos-openssl

### PR DESCRIPTION
**Pull request by kubo39**

### CODE REVIEW

**Comment by kubo39** [comment]
seems unrelated to this PR.

```
docker run -p 3000:3000 -td d.vibed > cid.txt
docker inspect `cat cid.txt` | jq -r '.[0].NetworkSettings.IPAddress' > ip.txt
curl --retry 5 --retry-delay 5 --retry-max-time 180 --retry-connrefused http://`cat ip.txt`:3000 -v
* Closing connection -1
curl: (3) URL using bad/illegal format or missing URL
make: *** [.Makefile:5: build] Error 3
Error: Process completed with exit code 2.
```

**Comment by waghanza** [comment]
It is @kubo39. When I run `/usr/src/app/server`, I have the following message
`/usr/src/app/server: error while loading shared libraries: libssl.so.1.1: cannot open shared object file: No such file or directory`

The first stage container is `Ubuntu 18.04.5 LTS \n \l` but the second is `Ubuntu 22.04.2 LTS`.

Is there a up-to-date `d` based `docker` image that I can use ?

PS : I've pushed a patch to make sur `vibe.d` can run

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
I've merged this into **master** so as I can publish update results next week @kubo39, but feel free to update with anything more up-to-date related to docker image in use

**Comment by kubo39** [comment]
Unfortunately, dlang's official docker images are not maintained.

**Pull request merged**
