### PR TITLE
Release on 13th of November 2023

### PR DESCRIPTION
**Pull request by waghanza**
N

### CODE REVIEW

**Comment by koplenov** [comment]
What's wrong with pico, vex, vweb? I couldn't find them in the CI tests

**Comment by waghanza** [comment]
I'll be the case on next update, I have not modified `v` to trigger CI

**Comment by waghanza** [comment]
@mmoreram I have
```php
Symfony\Component\HttpFoundation\HeaderBag::set(): Argument #2 ($values) must be of type array|string|null, int given, called in /usr/src/app/vendor/drift/http-kernel/AsyncHttpKernel.php on line 121
```
for `driftphp`

**Comment by waghanza** [comment]
There is an error while installing `memcached` extension on `debian-slim`


`docker-php-ext-install memcached` leads to 
```php
3.218 checking for libmemcached location... configure: error: memcached support requires libmemcached. Use --with-libmemcached-dir=<DIR> to specify the prefix where libmemcached headers and library are located
``` 

do you know a workaround @natanfelles ?

**Comment by waghanza** [comment]
@lizhichao do you sucees to compile swoole 4.8 on latest docker image ?

**Comment by waghanza** [comment]
@jkyberneees @schamberg97 I have some errors with https://github.com/jkyberneees/low-http-server, seems not compliant ith latest LTS (21)
```javascript
Error: This version of uWS.js supports only Node.js 14, 16 and 18 on (glibc) Linux, macOS and Windows, on Tier 1 platforms (https://github.com/nodejs/node/blob/master/BUILDING.md#platform-list).
```

**Comment by waghanza** [comment]
same for `chubbyts` @dominikzogg  (the uws version)

**Comment by waghanza** [comment]
same for `spliffy` @snowbldr

**Comment by waghanza** [comment]
@Ethosa when using `wrk` I have
```python
root@c5782260f9d8:/usr/src/app# python server.py 
Enable auto translate:       false
Enable httpbeast:            false
Enable httpx:                true
Enable MicroAsyncHttpServer: false
[2023-11-13 at 13:23:18]:INFO Server started at http://0.0.0.0:3000
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/system.nim(568) eventLoop
/home/runner/.nimble/pkgs2/httpx-0.3.7-6e0fc3133fbd20530d53ab2792e93d3151387b10/httpx.nim(478) processEvents
/home/runner/work/happyx/happyx/src/happyx/ssr/handlers.nim(257) handleRequest (Async)
/home/runner/.nimble/pkgs2/nimpy-0.2.0-59c049053128a5cb76f77f9a5589fa3dcf821bee/nimpy.nim(872) getAttr
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/system.nim(98) raisePythonError
[[reraised from:
/home/runner/.nimble/pkgs2/httpx-0.3.7-6e0fc3133fbd20530d53ab2792e93d3151387b10/httpx.nim(575) eventLoop
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/pure/asyncdispatch.nim(1711) poll
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/pure/asyncdispatch.nim(1452) runOnce
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/pure/asyncdispatch.nim(269) processPendingCallbacks
/home/runner/.choosenim/toolchains/nim-2.0.0/lib/pure/asyncfutures.nim(266) :anonymous
/home/runner/.nimble/pkgs2/httpx-0.3.7-6e0fc3133fbd20530d53ab2792e93d3151387b10/httpx.nim(483) :anonymous
/home/runner/.nimble/pkgs2/httpx-0.3.7-6e0fc3133fbd20530d53ab2792e93d3151387b10/httpx.nim(332) onRequestFutureComplete
]]
Error: unhandled exception: <class 'AttributeError'>: 'code' object has no attribute 'str' [Exception]
```

**Comment by waghanza** [comment]
@beetlex-io with `beetlex`  I have 
```csharp
>>13:31:12 [Error  ] [SYSTEM] HTTP open error Method 'get_Name' in type 'BeetleX.FastHttpApi.HttpPacket' from assembly 'BeetleX.FastHttpApi, Version=2.2.22.188, Culture=neutral, PublicKeyToken=null' does not have an implementation.@   at BeetleX.FastHttpApi.HttpApiServer.OnOpen()
   at BeetleX.FastHttpApi.HttpApiServer.<Open>b__158_0()!
```
zhen enabling log to console

cc @panesofglass

**Pull request merged**
