### PR TITLE
[Python] Upgrade containers to 3.8

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` updates container for the next major of our beloved language :heart: 

@1st1 Thanks for your tips in https://github.com/MagicStack/uvloop/issues/277#issuecomment-546556023

:warning: Please do not merge this `PR` until `uvloop` is realease for `python` **3.8**

Available for :
+ [x] aiohttp
+ [x] asgineer
+ [x] blacksheep
+ [x] bocadillo
+ [x] bottle
+ [x] cherrypy
+ [x] clastic
+ [x] cyclone
+ [x] django
+ [x] falcon
+ [x] fastapi
+ [x] flask
+ [x] hug
+ [x] japronto
+ [x] masonite
+ [x] molten
+ [x] nameko
+ [x] quart
+ [x] responder
+ [x] sanic
+ [x] starlette
+ [x] tornado

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
/cc @almarklein @RobertoPrevato @florimondmanca @webknjaz @mahmoud @fiorix @tiangolo @josephmancuso @Bogdanp @mattbennett @pgjones @taoufik07 @tomchristie @bdarnell glad this could work on `python` **3.8**

@squeaky-pl `japronto` is not available for `python` **3.8**. is this on purpose ?

**Comment by waghanza** [comment]
@webknjaz is it `OK` to run `cherrypy` on `gunicorn` ? I mean, the purpose `here` is to be as-close-as possible to a **production** stack

**Comment by webknjaz** [comment]
@waghanza I usually used uwsgi+nginx but gunicorn should work I guess.

**Comment by pgjones** [comment]
`There is no new project development happening at the moment` as per the japronto [README](https://github.com/squeaky-pl/japronto/blob/master/README.md) - so it may not ever support Python 3.8.

**Comment by waghanza** [comment]
@pgjones I've made a `PR` to ask to enable `python ` **3.8** https://github.com/squeaky-pl/japronto/pull/166

If this `PR` is not accepted in a reasonable amount of time, I'll remove `japronto` from `here` (at least this is more an experimental / plumbers project :stuck_out_tongue:

**Pull request merged**
