### PR TITLE
Remove thread compilation option

### PR DESCRIPTION
**Pull request by waghanza**
Hi @bung87 ,

After removing `thread:on`, `scorper` seems to perform better

```json
[
    {
      "level": 512,
      "label": "minimum_latency",
      "value": 3207.6666666666665,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "total_requests_per_s",
      "value": 2774.6666666666665,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "duration_ms",
      "value": 10017968.666666666,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "percentile_75",
      "value": 2143.3333333333335,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "percentile_99",
      "value": 77236.66666666667,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "socket_connection_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "average_latency",
      "value": 6393,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "socket_read_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "total_requests",
      "value": 49628.333333333336,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "total_bytes_received",
      "value": 6380200,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "socket_write_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "total_requests",
      "value": 69350,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "percentile_99",
      "value": 2745.6666666666665,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "request_timeouts",
      "value": 44,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "total_bytes_received",
      "value": 3840785.3333333335,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "socket_connection_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "percentile_90",
      "value": 2156,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "percentile_90",
      "value": 6241.333333333333,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "maximum_latency",
      "value": 152819.66666666666,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "standard_deviation",
      "value": 5515,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "percentile_50",
      "value": 20389.333333333332,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "total_bytes_received",
      "value": 4565806.666666667,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "maximum_latency",
      "value": 23599.666666666668,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "total_requests",
      "value": 41747.666666666664,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "socket_connection_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "percentile_99.999",
      "value": 329640,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "percentile_99",
      "value": 25870.333333333332,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "socket_read_errors",
      "value": 21.333333333333332,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "percentile_50",
      "value": 5901.666666666667,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "percentile_75",
      "value": 6011.333333333333,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "standard_deviation",
      "value": 439,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "percentile_99.999",
      "value": 149897,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "average_latency",
      "value": 18724.333333333332,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "percentile_99.999",
      "value": 23125.333333333332,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "http_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "socket_write_errors",
      "value": 12722.666666666666,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "duration_ms",
      "value": 5015545.333333333,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "total_requests_per_s",
      "value": 3304.3333333333335,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "percentile_75",
      "value": 20660.333333333332,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "total_requests_per_s",
      "value": 4609,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "minimum_latency",
      "value": 1758.6666666666667,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "average_latency",
      "value": 2155,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "minimum_latency",
      "value": -3.0744573456182574e+18,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "request_timeouts",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "http_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "socket_write_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "percentile_90",
      "value": 20786.666666666668,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "maximum_latency",
      "value": 330924.6666666667,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "duration_ms",
      "value": 5015183,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "socket_read_errors",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 512,
      "label": "standard_deviation",
      "value": 16095.333333333334,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "percentile_50",
      "value": 2129,
      "framework_id": 2
    },
    {
      "level": 64,
      "label": "request_timeouts",
      "value": 0,
      "framework_id": 2
    },
    {
      "level": 256,
      "label": "http_errors",
      "value": 0,
      "framework_id": 2
    }
  ]
```

### CODE REVIEW

**Comment by bung87** [comment]
sorry, I forget nim v2 enable threads by default, should change on -> off.

**Comment by bung87** [comment]
never mind, remove it, it is controlled by framework.

**Review by bung87 — APPROVED** [review]

**Comment by waghanza** [comment]
@mattaylor @olliNiinivaara @ire4ever1190 Is this ok to remove threads compilation option ?

**Comment by ire4ever1190** [comment]
Yup fine with me :+1: 
Enabled by default now so no need for the config

**Pull request merged**
