### PR TITLE
Results update

### LINKED ISSUE #4378: Missing nim / scorper in results

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` will update results.

Regards,

-------
Closes #4378, #4384, #4405, #4437

### CODE REVIEW

**Comment by waghanza** [comment]
@dom96 @mattaylor for both `httpbeast` and `whip`. I have a `Address family not supported by protocol [OSError]` on **alpine** (perhaps **alpine** is not the right distro for `nim`, I have no insights to choose).

Compilation options are the same for both frameworks 

```dockerfile
FROM nimlang/nim:1.4.8-alpine

WORKDIR /usr/src/app

COPY . ./



ENV PATH $PATH:/root/.nimble/bin

RUN nimble install -y

RUN nim c  \
    --excessiveStackTrace:off \
    -d:release \
    --passC:-flto \
    --passL:-flto \
    server.nim

FROM alpine

COPY --from=0 /usr/src/app/server /usr/src/app/server

CMD /usr/src/app/server
```

**Comment by waghanza** [comment]
@greenlaw110 When running `act` I have
```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.esotericsoftware.reflectasm.AccessClassLoader (file:/opt/web/lib/reflectasm-1.11.9.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.esotericsoftware.reflectasm.AccessClassLoader
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
```

**Comment by waghanza** [comment]
@dom96 @mattaylor I'll skip `httpbeast` and `whip` for this update

**Comment by dom96** [comment]
@waghanza that's weird. Did httpbeast work fine before? Maybe it's the new version that has a regression, can you try 0.2.2?

**Comment by waghanza** [comment]
We are still using 0.2.x 😛  If we solve this issue this week end, I can update `httpbeast`, I just prefer not to block a lot of frameworks due to 2 of them ❤️

**Comment by waghanza** [comment]
@dom96 it is indeed a regression 0.3. Using `requires "httpbeast >= 0.2 & < 0.3"` fix the issue

**Comment by mattaylor** [comment]
I can help look at this in the morning.

**Comment by jeremyevans** [comment]
The Ruby issue is unrelated to any of the frameworks, it's an issue with reaching the rubygems repository during bundle install.  Only causes I can think of for that are a temporary issue with rubygems itself, or the docker instance not being able to reach rubygems due to a network issue.

**Comment by dom96** [comment]
If you'll be using Debian can you switch back to httpbeast 0.3.0?

**Comment by waghanza** [comment]
> If you'll be using Debian can you switch back to httpbeast 0.3.0?

I'll test this today :-)

**Comment by dom96** [comment]
> PSS : The best for this project, imho, is to stick to want mostly used (in term of distro), do you have any insight for me @dom96 ? (I mean what is mostly used in nim community)

I think it should be whatever is most popular among all devs. Debian-based seems like would be most popular. I personally use Ubuntu the most (and in all my CIs too IIRC).

Definitely weird we're seeing problems on Alpine though, I'm guessing it's because of musl, would be nice to figure out what the change that caused the issue is.

**Comment by waghanza** [comment]
@dom96 seems that the error was on my side (https://www.avahi.org disable `dns` on **containers** due to security / selinux)

My solution is to use https://podman.io

**Comment by dom96** [comment]
Debian + 0.3.0 doesn't work?

**Comment by waghanza** [comment]
> Debian + 0.3.0 doesn't work?

Nop. Same issue. I have opened a gh issue to track this subject

**Pull request merged**
