### PR TITLE
[F#] Update falco

### LINKED ISSUE #3030: [F#] Update falco to 1.2

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` updates https://github.com/pimbrouwers/Falco to **1.2**

@pimbrouwers May I add you to `CODEOWNER` in order to ping you on https://github.com/pimbrouwers/Falco update `here` ?

Regards,

--------
Closes #3030

### CODE REVIEW

**Comment by waghanza** [comment]
I have warnings on `dotnet restore`
```
/usr/src/app/web.fsproj : warning NU1605: Detected package downgrade: FSharp.Core from 4.7.1 to 4.7.0. Reference the package directly from the project to select a different version. 
/usr/src/app/web.fsproj : warning NU1605:  web -> Falco 1.2.0 -> FSharp.Core (>= 4.7.1) 
/usr/src/app/web.fsproj : warning NU1605:  web -> FSharp.Core (>= 4.7.0)
```

**Comment by pimbrouwers** [comment]
@panesofglass is absolutely correct. I made a mistake when I incremented the package number. I blame being an overworked and tired new dad!

I will remedy this right now!

**Comment by waghanza** [comment]
> I blame being an overworked and tired new dad!
Congrats ... but what mistake you will do later (it's worse after :stuck_out_tongue_closed_eyes:)

**Comment by pimbrouwers** [comment]
> > I blame being an overworked and tired new dad!
> 
> Congrats ... but what mistake you will do later (it's worse after 😝)

Oh boy... knowing me, it won't be good .... haha!

**Comment by panesofglass** [comment]
I'm about to send a PR. You know me, can't shake it until I fix it. :)

**Comment by panesofglass** [comment]
@waghanza @pimbrouwers https://github.com/waghanza/http-benchmark/pull/139

**Comment by pimbrouwers** [comment]
I just submitted a PR to your repo Ryan. Looks like I just missed you!

**Comment by waghanza** [comment]
@panesofglass You made a typo (Wrong http verb for one route). btw, I'll update results tomorrow

**Comment by panesofglass** [comment]
Oops! Thank you for fixing it!

**Comment by pimbrouwers** [comment]
@panesofglass - do we need to merge my PR? Or is it useless now.

**Pull request merged**
