### PR TITLE
Add awesome_bot for dead links detection

### PR DESCRIPTION
**Pull request by limonte**
There are many dead links in the README:

```
Issues :-(
> Links 
  01. [L098] 404 https://gofiber.github.io/fiber  
  02. [L114]  https://razecr.com SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  03. [L120]  https://actframework.org Failed to open TCP connection to actframework.org:443 (Connection refused - connect(2) for "actframework.org" port 443) 
  04. [L134]  https://https://ninenines.eu/docs/en/cowboy/2.7/guide/streams/ Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known) 
  05. [L134]  https://https://ninenines.eu/docs/en/cowboy/2.7/guide/ Failed to open TCP connection to https:443 (getaddrinfo: Name or service not known) 
  06. [L162]  https://kitura.io Failed to open TCP connection to kitura.io:443 (Connection timed out - connect(2) for "kitura.io" port 443) 
  07. [L170]  https://hug.rest SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  08. [L171]  https://starlette.io Failed to open TCP connection to starlette.io:443 (getaddrinfo: Name or service not known) 
  09. [L182]  https://restify.com SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  10. [L184]  https://cuba.is SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) 
  11. [L185]  https://python-responder.org Failed to open TCP connection to python-responder.org:443 (Connection refused - connect(2) for "python-responder.org" port 443) 
  12. [L194]  https://ironframework.io SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  13. [L198]  https://flask.pocoo.org SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  14. [L207]  https://sinatrarb.com SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  15. [L208]  https://ruby-grape.org SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  16. [L209]  https://tornadoweb.org SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  17. [L219]  https://perldancer.org SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate) 
  18. [L220]  https://slimframework.com SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
  19. [L227]  https://cyclone.io SSL_connect returned=1 errno=0 state=error: certificate verify failed (unspecified certificate verification error) 
```

### CODE REVIEW

**Comment by limonte** [comment]
Hm, GitHub is saying "No workflows have been created", I guess it'll pick up this workflow once it's merged into master. Not sure.

**Comment by waghanza** [comment]
@limonte  Thanks for opening this `PR`. Glad you are interested in this project :heart: .

As I can understand, `awesome_bot` could prevent from deadlinks. 

I'm creating a feature to check links on each `PR`, so no need of that.

**Comment by limonte** [comment]
> @limonte Thanks for opening this `PR`. Glad you are interested in this project heart .
> 
> As I can understand, `awesome_bot` could prevent from deadlinks.

Not sure if "prevent" is the correct word here, let's say indicate or validate, docs are here: https://github.com/dkhamsing/awesome_bot

> I'm creating a feature to check links on each `PR`, so no need of that.

Feel free to remove the `pull_request:` line if you think it's unnecessary.

**Comment by waghanza** [comment]
In fact, I'll add to specs suite a check to ensure URLs is not dead.

In dead, links referenced here could be unvalid after a while, but thanks to travis cron feature, that will check if links are still valids.

BTW, I appreciate you help.

**Pull request closed without merging**
