### PR TITLE
[F#] WebSharper

### PR DESCRIPTION
**Pull request by panesofglass**
@Jand42, @granicz, and @Tarmil, I've separated this out. Feel free to submit your own or let me know when the netcoreapp3.1 issue is resolved, and I'll update this PR.

@waghanza this builds on #2874

### CODE REVIEW

**Comment by panesofglass** [comment]
@granicz to reproduce,

git clone https://GitHub.com/panesofglass/web-frameworks
cd web-frameworks
git checkout fsharp/websharper
cd fsharp/websharper
docker build -t fsharp.websharper -f ../Dockerfile .

**Comment by panesofglass** [comment]
@Jand42, @granicz, or @Tarmil, what is the encoding of `Content.Text`? The tests had the correct string value, but I suspect there was an encoding issue. @waghanza, what's the expected encoding? UTF-8?

**Comment by waghanza** [comment]
@panesofglass I've rebased so as to clean differences (show only files belonging to this `PR`). We will see what `CI` says

**Comment by waghanza** [comment]
I have a **Segmentation fault (core dumped)**

**Comment by waghanza** [comment]
@panesofglass The encoding is valid (`UTF-8`). However, when getting from `/user/0` I have two chars 
+ a blank one
+ 0

 I expected the result to be exactly 0

**Comment by Jand42** [comment]
@panesofglass Thanks for the test, I am testing updating the compiler to netcoreapp3.1, some more small fixes currently building for the Docker/Unix.

But I just realized that in this test scenario, there is no client-side functionality, so the WebSharper.FSharp package (compiler tools) is not needed. Removing that, the project builds on standard F# compiler tools and only use WebSharper's runtime, so updating to ANC3.1 would cause no issues.

**Comment by waghanza** [comment]
Indeed it works without **WebSharper.FSharp**

However, I have a warning @Jand42 while publishing `dotnet publish -c release -o out`

~~~fsharp
/usr/src/app/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 1 in table 'itycons' of assembly 'WebSharper.Core.JavaScript, Version=4.6.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [/usr/src/app/web.fsproj]
/usr/src/app/unknown(1,1): warning FS3186: An error occurred while reading the F# metadata node at position 0 in table 'ivals' of assembly 'WebSharper.Core.JavaScript, Version=4.6.0.0, Culture=neutral, PublicKeyToken=dcd983dec8f76a71'. The node had no matching declaration. Please report this warning. You may need to recompile the F# assembly you are using. [/usr/src/app/web.fsproj]
~~~

**Comment by Jand42** [comment]
@waghanza Thanks, that warning is benign, see https://github.com/dotnet/fsharp/issues/592
I still don't know the exact cause of it (made an attempt to find it previosly) but something in `WebSharper.Core.JavaScript.dll` does trigger it, so `WebSharper.FSharp` adds it to NoWarn to not be bothering. A `<NoWarn>$(NoWarn);3186</NoWarn>` in project file should hide it.

**Comment by waghanza** [comment]
@Jand42 Thanks for explanation, however, it is a warning ... I think rather let the community handle it instead of hiding it ;-)

However, what is more  important is https://github.com/the-benchmarker/web-frameworks/pull/2888#issuecomment-640223340, if we can solve this in next hours, I would update results.

**Comment by panesofglass** [comment]
@Jand42 any ideas on this one? I can't see anything the `Content.Text`. Maybe in how it retrieves the parameter from the route?

**Comment by waghanza** [comment]
@panesofglass I always have extra chars

- ['﻿']
- ['﻿', '0']
- ['﻿']

**Comment by panesofglass** [comment]
My last change seems to have a paused build for some reason.

**Comment by waghanza** [comment]
@panesofglass Probably me. I have to pause builds some times, `travis` could not handle a so huge project with this configuration (that's why is witch to https://the-benchmarker.semaphoreci.com/projects/web-frameworks)

**Pull request merged**
