### PR TITLE
Use release mode, not use log/recovery middleware

### PR DESCRIPTION
**Pull request by thinkerou**

### CODE REVIEW

**Comment by waghanza** [comment]
|        | Framework (Middleware)    |         Average |  50% percentile |  90% percentile |  99% percentile | 99.9% percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
|   here                      | gin                       | 12.65 ms | 10.99 ms | 20.16 ms | 39.79 ms | 221.53 ms | 7841.00 | 
| master                        | gin                       | 52.95 ms | 29.85 ms | 144.86 ms | 236.48 ms | 526.27 ms | 60143.00 |

**Comment by waghanza** [comment]
@thinkerou Thanks for you contribution

If I may ask you a question ... how can I specify version to use (instead of using **master** in `golang`) ?

**Comment by thinkerou** [comment]
@waghanza `go get -u github.com/gin-gonic/gin@1.3`, right?

**Comment by thinkerou** [comment]
@waghanza I am sorry, I said `go get -u github.com/gin-gonic/gin@1.3` is wrong, it should be `govendor fetch github.com/gin-gonic/gin@1.3`, so it will install `govendor` firstly.
If you don't install `govendor`, you should use `go get gopkg.in/gin-gonic/gin.v1`, so am other go web framework. when I have time I am willing commit one pr for go.

**Comment by waghanza** [comment]
@thinkerou sure, I'd be happy to learn / add this :heart:

**Comment by appleboy** [comment]
@thinkerou Don't use `gopkg.in` service any more :)

**Comment by thinkerou** [comment]
@appleboy OK, thanks!

**Pull request merged**
