### PR TITLE
Better Agoo settings

### PR DESCRIPTION
**Pull request by ohler55**
These changes along with some changes in Agoo itself should improve Agoo performance. Comments were also added to the app to make it clear why the setting were selected.

-------------------
Before submitting your PR, please review the following checklist :

## If you are adding a framework

+ [x] Please check configuration files
   + [x] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [x] `FRAMEWORKS.yml`, for **frameworks** list
   + [x] `travis.yml`, for CI
+ [x] A `Dockerfile` exists ?
+ [x] All tests passes ?
~~~
export FRAMEWORK=<MY_FRAMEWORK>
shards install
shards build --release
bin/neph ${FRAMEWORK}
crystal spec
~~~

### CODE REVIEW

**Comment by ohler55** [comment]
Sure, have to wait a few hours though. I’ll branch off my fork.

**Comment by waghanza** [comment]
If I can edit your code (push), it will enhance collaboration

**Comment by ohler55** [comment]
When I created the PR I set the option to allow edits by the reviewer. Sorry, only phone access right now.

**Comment by waghanza** [comment]
No problem, take time you need :heart:

**Comment by ohler55** [comment]
I assume I should close this PR and create a new one. Correct?

**Comment by waghanza** [comment]
It's the easiest way

**Comment by ohler55** [comment]
Reopening from a branch instead.

**Pull request closed without merging**
