### PR TITLE
[PHP] Add fastsitephp

### LINKED ISSUE #2680: Add fastsitephp
Hi @ConradSollitt,

Would you mind to add (or consent that we add) [fastsitephp](https://github.com/fastsitephp/fastsitephp) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

### PR DESCRIPTION
**Pull request by waghanza**
Hi @ConradSollitt,

Following #2680, this is an attemt to add `fastsitephp` in here.

The purpose is to have **production-grade** implementation, then please feel free to review thinking this should be deployable as-is (safe, readable ...).

Regards,

PS : All `php` **frameworks** here a tracked by `renovatebot` to ensure to have an up-to-date version. May I ask for you review on each update ?

------------
Closes #2680

### CODE REVIEW

**Comment by ConradSollitt** [comment]
Looks great, there was one thing I forgot to add until I saw you wrote the **production-grade** comment:

Lines 41 to 43:
_Safely Escape the user input since it's returned to the client. After this everything is safe and production ready._
~~~php
$app->get('/user/:id', function($id) use ($app) {
    return $app->escape($id);
});
~~~

Also please add this grammar fix. Now that I re-read my original comment, it wasn't clear:
Lines 8 to 9:
~~~php
// This allows classes to be dynamically loaded and is included when
// dependencies are installed through the PHP Package Manager Composer.
~~~

Additionally the latest version is `1.2.2` and not `1.2.0` as specified in the `composer.json` file.

I will review on each new version, I'll add it to publishing notes for the project.

**Comment by waghanza** [comment]
> Additionally the latest version is 1.2.2 and not 1.2.0 as specified in the composer.json file.

Using `1.2.0` will take the last **1.2.x** (I prefer using this to decrease maintenance stuff :heart)

**Comment by ConradSollitt** [comment]
Makes sense for the `1.2.0` as it's easier to maintain. Related updated to `1.2.2` don't affect anything for the performance test.

I just submitted a pull request on your branch as the comment ended up duplicated and to add the PHP HTML escaping code.

**Comment by ConradSollitt** [comment]
The Travis CI build failed, looks like from these items:

`FRAMEWORK=php.yii`
https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/335383968

`FRAMEWORK=php.hamlet`
https://travis-ci.com/github/the-benchmarker/web-frameworks/jobs/335383967

**Comment by waghanza** [comment]
It seems like those build are false positive, I mean failures are due to external (network issues ...), that's why I use https://the-benchmarker.semaphoreci.com/ for the next version (more reliable, quicker ...)

**Comment by ConradSollitt** [comment]
Thanks for all your help @waghanza and @appleboy 

I'm looking forward to see the results next time benchmarks are run!

**Comment by appleboy** [comment]
@waghanza When to update new benchmark data?

**Comment by ConradSollitt** [comment]
@waghanza @appleboy 

I see the benchmarks ran and results look great! FastSitePHP ranked #138 which doesn't sound fast but it was actually the fastest PHP Framework using the standard nginx setup. There are other faster PHP frameworks of course but they all use Swoole or other custom services which require server restart on file changes.

I haven't published many articles or posts on FastSitePHP yet but plan on doing so in the near future and will reference this repository when I do.

Thanks for all your help!

**Comment by waghanza** [comment]
@ConradSollitt Sorry for the delay, has see any notification.

I understand (and know why) results shows that `fastsitephp` is not as fast as expected. Please track #3118 to see results as expected.

In fact, actually results are collected from local **containers** (`docker`). The above `PR` make results collected from `cloud` instances, the results will then be more what you expect (I hope).

The idea to use **docker** was to let contribution be easy. Short story, the above `PR` let this facility, but has a more complex `config.yaml`. It will be compatible with `cloud-init`, and why not `pod` (**kubernetes**) definition in a far future

Regards :heart:

**Comment by ConradSollitt** [comment]
@waghanza 

Thanks for the detailed comment! Actually the results are still pretty good. I see a lot of very high performance PHP frameworks now but everything above `fastsitephp` is using either a coroutine or asynchronous server environment. I think I'll have to look into those more later but personally if I write asynchronous server code I would prefer using node with express or another node framework. 

PHP is great in the fact that you can use it on nginx or apache, update a single file and not require a server or service restart but it is much slower to other options out there. Still though it can be fast enough for most sites - I just wouldn't want to run a large gaming server with it though.

**Pull request merged**
