### PR TITLE
First 2024 release

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

+ [x] scorper
+ [x] one
+ [x] happyx

### CODE REVIEW

**Comment by waghanza** [comment]
@bung87 `scorper` is failing. Do not understand why ? Can you open a PR with all debug activated ? I'll simply hide scorper for this round

**Comment by waghanza** [comment]
@lizhichao I've removed one, it does not compile on last debian due to swoole 4.x usage

Feel free to ping me if you upgrade one to latest swoole

**Comment by bung87** [comment]
where I can see the error, I run locally without problem.

**Comment by waghanza** [comment]
Maybe it's a docker issue. Can it be run with debug mode ? I'm sure there is an error at some concurrency level

**Comment by bung87** [comment]
just remove `-d:release` from nim docker file.

**Pull request merged**
