### PR TITLE
[Python] Disable logging

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` disable logging on all `python` frameworks.

Logging is disabled for :

- [x] aiohttp
- [x] apidaora
- [x] asgineer
- [x] blacksheep
- [x] bottle
- [x] cherrypy
- [x] clastic
- [ ] cyclone
- [x] django
- [x] emmett
- [x] falcon
- [x] fastapi
- [x] flask
- [x] hug
- [ ] klein
- [x] masonite
- [x] molten
- [ ] nameko
- [x] pyramid
- [x] quart
- [x] responder
- [x] sanic
- [x] starlette
- [x] tonberry
- [x] tornado

@benoitc Does having a `logconfig_dict = {'handlers': { 'console': { 'class': 'logging.NullHandler', }, 'error_console': { 'class': 'logging.NullHandler', }, } }` in  `gunicorn` configuration fully disable logging ? 

/cc @pgjones @ahopkins @tiangolo @Ayehavgunne

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@wsanchez @fiorix How can I disable logging with `klein` and `cyclone` ? perhaps, it is disable by default

**Comment by waghanza** [comment]
@mattbennett how can I disable logging in `nameko` ?

**Comment by waghanza** [comment]
@ahopkins `logging.disable()` is not enough to disable all loggers ?
https://docs.python.org/3/library/logging.html#logging.disable

**Comment by ahopkins** [comment]
It should be

**Comment by waghanza** [comment]
@ahopkins ok. I'll do it. It will clean source code :stuck_out_tongue:  (for ``sanic` :heart:)

**Pull request closed without merging**
