### PR TITLE
Introduce variants

### PR DESCRIPTION
**Pull request by jkyberneees**
Using `low` HTTP server (friendly Node.js wrapper around uWebSocket.js) 
Big performance gain!

### CODE REVIEW

**Comment by waghanza** [comment]
@jkyberneees yeah :tada: this seems awesome

However, comparing this with a pure node framework is unfair. Is there any `uWebSocket` integration for any other framework ?

/cc @aichholzer

**Comment by jkyberneees** [comment]
Hi @waghanza, thanks.
You are right, this might be a radical approach in Node.js, as we are not using the default HTTP server implementation. However, it is still Node and JS ;)

I would kindly ask you to consider it, because low level alternative solutions like uWebSockets.js or turbo-http will be more frequent for Node.js in the future.

Regards

**Comment by waghanza** [comment]
@jkyberneees sure. I am thinking about that. Let me clarify my thought.
As **tfb** has `platform` @see https://www.techempower.com/benchmarks/#section=motivation&hw=ph&test=fortune, I think we need `variant`.
The stachs world is changing :
+ in `php`, there is `swoole` challenging the someking standard `php-fpm`
+ in `python`, there is the `async` like frameworks
+ in `node`, the is `uWebSocket` (or `deno`)

I'm think of 2 modes (to display results) :
+ standard -> using the _what is considered as standard_ 
+ expert -> a way to display result with others `platforms`

As those evolutions could take times (because I'm the only `core` dev `here`), but all `PR` will be kept open

**Comment by waghanza** [comment]
@jkyberneees I've create a little trick to add variant
The process is to add a `Dockerfile`-**variantname** and a subfolder (just for organisation) for the source code

**Comment by waghanza** [comment]
@jkyberneees I take the permission of adding more use case on that, I mean adding a more _global_ behaviour on this project. The purpose is to add
+ `swoole` for existing **php**
+ `falcon` for existing **ruby**
+ `uWebSocket` / `turbo` for **node**

of course this is a long term run, but I think I can change my roadmap (what I have in mind) -> production level will be later

Thanks for your inspiration :tada: :heart:

**Comment by jkyberneees** [comment]
Feel free to play with it. 👍

**Comment by waghanza** [comment]
/cc @nicolas-grekas @robopuff @Jurigag
@stdex I think I'll also add [roadrunner](https://roadrunner.dev)

**Comment by jkyberneees** [comment]
Hi @waghanza is there any update on this MR? Thanks

**Comment by waghanza** [comment]
@jkyberneees No, not for now. I'm working on https://github.com/the-benchmarker/web-frameworks/pull/1578 before to in order to facilitate this one

Moreover, I need to find a way to display engine in (`uWebSocket` or `node`), but I'm on it

Regards,

**Comment by jesusvilla** [comment]
> @jkyberneees yeah  this seems awesome
> 
> However, comparing this with a pure node framework is unfair. Is there any `uWebSocket` integration for any other framework ?
> 
> /cc @aichholzer

Hi. 
Yes there are frames working with uWebSocket and they are first in the node ranking: [Sifrr-server](https://sifrr.github.io/sifrr/#/./packages/server/sifrr-server/) and [Nanoexpress](https://www.npmjs.com/package/nanoexpress) (the project no longer exists).

**Comment by waghanza** [comment]
The purpose is to implement some **variants** `here`. This is a list of **variants** to implements :
+ `javascript`
   + [x] [node](https://nodejs.org) -> default
   + [ ] [uwebsocket](https://github.com/uNetworking/uWebSockets) -> if available
   + [ ] [turbo](https://github.com/mafintosh/turbo-http) -> if availble
+ `ruby`
   + [x] [puma](https://puma.io) -> the default
   + [ ] [falcon](https://github.com/socketry/falcon)
   + [ ] [iodine](https://github.com/boazsegev/iodine)
+ `python`
   + [x] [gunicorn](https://gunicorn.org) -> the default
   + [ ] [uwsgi](https://uwsgi-docs.readthedocs.io) -> for **wsgi** only
   + [ ] [chausette](https://chaussette.readthedocs.io)  -> for **wsgi** only
   + [ ] [bjoern](https://github.com/jonashaag/bjoern) -> for **wsgi** only
   + [ ] [hypercorn](https://pgjones.gitlab.io/hypercorn) -> for **asgi** only
   + [ ] [daphne](https://github.com/django/daphne) -> for **wsgi** only
   + [ ] [uwsgi](https://uwsgi-docs.readthedocs.io) -> for **wsgi** only

**Comment by Fenny** [comment]
Hey @waghanza ,

I just want to give you a heads up to make sure you `compile` your own uWebSockets binaries.

The author seems to have a [history track](https://medium.com/@rockstudillo/beware-of-uwebsockets-js-b51c92cac83f), and delivers `pre-compiled` binaries that could introduce trojan horses, viruses or malware in the worst case scenarios.

**Comment by waghanza** [comment]
@Fenny Simple answer -> no 

I'm aware of what you point, but I'm not working on this `PR` yet.

If you have an idea of how to do this then, I'll be :heart:

**Comment by jkyberneees** [comment]
Hi @waghanza, is there any update on this topic?
Regards

**Comment by waghanza** [comment]
HI @jkyberneees,

Sorry for the delay. 

I'll work on this next week. 

I'll update our roadmap.

**Pull request closed without merging**
