### PR TITLE
Introduce Onyx::REST

### LINKED ISSUE #418: Add atom (when it will be ready)
+ Language : crystal
+ Repo : https://github.com/atomframework/atom
+ Author : @vladfaust

### PR DESCRIPTION
**Pull request by vladfaust**
Repository URL: https://github.com/onyxframework/rest

Previously it was called "atom", but "onyx" is a better name, because Onyx is black. :smile: 
Tell me what to do next, please (i.e. add info to the README?).

I also use forking approach, it's quite simple.

Closes #418 

## New framework checklist

+ [x] Please check configuration files
   + [x] `neph.yml`, for [neph](http://tbrand.github.io/neph) job processing
   + [x] `FRAMEWORKS.yml`, for **frameworks** list
   + [x] `travis.yml`, for CI
+ [x] A `Dockerfile` exists ?
+ [x] All tests passes ?

### CODE REVIEW

**Comment by vladfaust** [comment]
I have a functionality of appending `"\n"` to text responses. Apparently, the spec fails. I'd skip `"\n"`, but in Crystal `context.response.respond_with_error` prints newline, so I assume it's default behavior for a web framework :thinking: 

Should I not append `"\n"` to the responses or should the spec be changed to ignore it?

**Comment by waghanza** [comment]
yep, I had the same issue with https://github.com/the-benchmarker/web-frameworks/blob/master/crystal/orion/server.cr#L10

so I use `print` because by default it `put` (so have more bytes to send over the network)

**Comment by waghanza** [comment]
@vladfaust sure, I understand, but this could be confusing (in our use case), at least if we have only one implementation with `onyx` **components**
for example, we have `zend-expressive` and `zend-framework`-> 2 distincts implementations with `zend` **components**

**Comment by vladfaust** [comment]
*Early bird gets the worm*

**Comment by vladfaust** [comment]
Thanks for the update, @waghanza. However, something's wrong with the build badge :thinking:

**Comment by waghanza** [comment]
@vladfaust I've updated results https://github.com/vladfaust/which_is_the_fastest/tree/add-onyx-rest

**Comment by vladfaust** [comment]
@waghanza it doesn't look good, please check your copy-paste buffer :smile: 

image

**Comment by waghanza** [comment]
Oh .... will be updated in about 3 hours

**Comment by waghanza** [comment]
Oh .... will be updated in about 3 hours

**Comment by vladfaust** [comment]
@waghanza 🏓

**Comment by vladfaust** [comment]
@waghanza just wanted to thank you, this repo is great 👍

**Pull request merged**
