### PR TITLE
:arrow_up: Upgrade RESTHeart to v8.0.0-beta

### PR DESCRIPTION
**Pull request by ujibang**
Upgrade RESTHeart

### CODE REVIEW

**Comment by ujibang** [comment]
> When restheart 8.x will be out of beta ?

Beta is feature complete and fully tested. We'd like to add to our perfornace tests your fantastic benchmark.

Then we will release 8.0.

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
I forget to warn you @ujibang but results where updated last Tuesday, and will be update again on Monday

**Comment by waghanza** [comment]
But it is displayed that we use java 11, but we use 21. I'll open an issue

**Comment by ujibang** [comment]
Restheart actually requires java 21

**Comment by ujibang** [comment]
We will release v8 next week. I'll send a new PR asap. Thanks.

**Pull request merged**
