### PR TITLE
Introduce fastapi

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` addresses #950 

@tiangolo How can I produce `text/plain` instead of `application/json` ?

Regards,

### CODE REVIEW

**Comment by waghanza** [comment]
@tiangolo found it :stuck_out_tongue:

**Comment by tiangolo** [comment]
Great! :smile:

**Comment by waghanza** [comment]
@tomchristie When using a `starlette` **Response**, `status_code` is `200` by default, even for `POST` method.

Should not `status_code` depends on HTTP method in use ? 201 for `POST`,  204 for `PUT` ...

**Comment by tiangolo** [comment]
`201` is specifically for "Created" responses.

But not all `POST` operations necessarily terminate on a resource "created".

`200` in `PUT` or `POST`:

> The resource describing the result of the action is transmitted in the message body.

Taken from: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status#Successful_responses

**Comment by waghanza** [comment]
indeed this code are not very standard

I always find this odd having a  `200` for any `POST` requests

**Comment by tiangolo** [comment]
Yep, and now with GraphQL that everything is on `POST` :joy:

BTW, thanks for the invitation to the org! :tada:

**Pull request merged**
