### PR TITLE
[WIP] Implement SO_REUSEPORT

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` implements **SO_REUSEPORT**.

+ java
   + [x] act
+ nim
   + [ ] jester @dom96
+ c
   + [ ] kore @jorisvink
   + [ ] agoo-c @ohler55
+ rust
   + [ ] nickel @nickel-org
   + [ ] iron @iron
   + [ ] rocket @SergioBenitez
   + [ ] actix-web @actix
   + [ ] gotham @gotham-rs
+ ruby
   + [x] sinatra
   + [x] rack-routing
   + [x] hanami
   + [x] agoo
   + [x] roda
   + [x] flame
   + [x] rails
+ objc
   + [ ] criollo @thecatalinstan
+ node
   + [x] foxify
   + [x] turbo_polka
   + [x] fastify
   + [x] hapi
   + [x] muneem
   + [x] restify
   + [x] polka
   + [x] rayo
   + [x] koa
   + [x] restana
   + [x] express
+ scala
   + [ ] akkahttp @akka
   + [ ] http4s
+ cpp
   + [x] evhtp
+ go
   + [ ] muxie
   + [ ] iris
   + [ ] gorilla-mux
   + [ ] gin
   + [ ] beego
   + [ ] echo
   + [ ] chi
   + [ ] fasthttprouter
   + [ ] gf
+ csharp
   + [ ] aspnetcore
+ elixir
   + [x] plug
   + [x] phoenix
+ swift
   + [ ] perfect
   + [ ] kitura
   + [ ] vapor
+ php
   + [ ] zend-framework
   + [ ] zend-expressive
   + [ ] slim
   + [ ] symfony
   + [ ] laravel
   + [ ] lumen
+ crystal
   + [x] onyx
   + [x] spider-gazelle
   + [ ] raze
   + [ ] amber
   + [x] kemal
   + [x] router.cr
   + [x] orion
   + [x] lucky
+ python
   + [x] japronto
   + [x] flask
   + [x] falcon
   + [x] responder
   + [x] cyclone
   + [x] starlette
   + [x] django
   + [x] sanic
   + [x] bottle
   + [x] tornado
   + [x] aiohttp
   + [x] vibora
   + [x] quart
   + [ ] quart

@OvermindDL1 This feature **COULD** be enabled on each framework https://github.com/tbrand/which_is_the_fastest/issues/69

Regards,

PS : Only `kemal` as in **WIP**

https://github.com/kemalcr/kemal/issues/459

### CODE REVIEW

**Comment by OvermindDL1** [comment]
Yep!  This is the first step in many frameworks production setup instructions (which surprises me why it's not done here yet).  Not all frameworks do it as some do it 'for' you (like Go's, Rust's, C++'s, etc... frameworks), but the ones that don't are supposed to be done manually, so this absolutely needs to be done as it will just straight-out fix many tests.  :-)

**Comment by waghanza** [comment]
@OvermindDL1 I have to check ;-) I have manually implemented it in https://github.com/spider-gazelle/action-controller/pull/3

**Comment by waghanza** [comment]
We have to list each frameworks that requires this

**Comment by waghanza** [comment]
The list is a bit long, but is the **simplest** way I found to avoid forgetting one **framework**
- [ ] act
- [ ] actix-web
- [ ] akkahttp
- [ ] all
- [ ] amber
- [ ] aspnetcore
- [ ] clean
- [ ] cpp
- [ ] criollo
- [ ] crystal
- [ ] csharp
- [ ] django
- [ ] echo
- [ ] elixir
- [ ] evhtp
- [ ] express
- [ ] fasthttprouter
- [ ] fastify
- [ ] flame
- [ ] flask
- [ ] gin
- [ ] go
- [ ] gorilla-mux
- [ ] hanami
- [ ] iris
- [ ] iron
- [ ] japronto
- [ ] java
- [ ] jester
- [x] kemal
- [ ] kitura
- [ ] koa
- [ ] laravel
- [ ] lucky
- [ ] mofuw
- [ ] nickel
- [ ] nim
- [ ] node
- [ ] objc
- [ ] perfect
- [ ] phoenix
- [ ] php
- [ ] plug
- [ ] polka
- [ ] python
- [ ] rack-routing
- [ ] rails
- [ ] rayo
- [ ] raze
- [ ] restify
- [ ] rocket
- [ ] roda
- [ ] router.cr
- [ ] ruby
- [ ] rust
- [ ] sanic
- [ ] scala
- [ ] sinatra
- [x] spider-gazelle
- [ ] swift
- [ ] symfony
- [ ] tornado
- [ ] vapor

**Comment by waghanza** [comment]
@OvermindDL1 all `node` **frameworks** use `SO_REUSEADDR`, https://nodejs.org/docs/latest-v8.x/api/net.html

**Comment by 2vg** [comment]
mofuw is already using SO_REUSEPORT.

**Comment by waghanza** [comment]
as I understand, `SO_REUSEPORT` and `SO_REUSEADDR` have no diff, for **our** `use case`
https://stackoverflow.com/questions/14388706/socket-options-so-reuseaddr-and-so-reuseport-how-do-they-differ-do-they-mean-t

**Pull request closed without merging**
