### PR TITLE
Use a cloud provider

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` replace #2411. It allow to use a `cloud provider`. 

Since `built-in` _tools_ has been rewritten (part of), usage is now :
+ Use `docker` / `docker-machine` => rake config
+ Use `PROVIDER=digitalocean` to build `droplets`

However, by default we use **docker**.

#### Languages

+ [ ] C
+ [ ] C++
+ [ ] C#
+ [ ] Clojure
+ [ ] Crystal
+ [ ] Dart
+ [ ] Elixir
+ [ ] F#
+ [ ] Go
+ [ ] Haskell
+ [ ] Java
+ [ ] Javascript
+ [ ] Julia
+ [ ] Kotlin
+ [ ] Nim
+ [ ] Perl
+ [ ] PHP
+ [ ] Pony
+ [ ] Python
+ [ ] Rust
+ [ ] Ruby
+ [ ] Scala
+ [ ] Swift

### CODE REVIEW

**Comment by waghanza** [comment]
@0xTim I've successfully use `swift` on `linux`. I compile all frameworks `here` using **docker** image (based on `ubuntu` I think) and run on `fedora`

I have a **warning** : `lib64/libcurl.so.4: no version information available` when I start the app. What does it mean ?

**Comment by waghanza** [comment]
@OvermindDL1 I've found that it is discouraged to compile `elixir` on a compute with different specs from which the code will run (it could the lead to **NIF** issue).

Could not we use a build machine (different from target) for `elixir` / `erlang` ?

**Comment by waghanza** [comment]
@jkyberneees @jeremyevans @pgjones @ahopkins @tiangolo @jodosha @taoufik07 @tomchristie The results for `python`, `ruby` and `javascript` are up-to-date on https://github.com/the-benchmarker/web-frameworks/tree/cloudify#results. This `PR` collect metrics from a `8` **CPU** /   `16` G of RAM
https://www.digitalocean.com/docs/droplets/resources/choose-plan/#:~:text=Dedicated%20CPU,their%20virtual%20resources%2C%20like%20vCPU.

**Comment by jwoertink** [comment]
Awesome. Just to make sure I understand what this is saying... Orion is clocking in at `106,287` requests per second on average for 64 requests?

**Comment by waghanza** [comment]
Exactly @jwoertink, and `lucky` at `80 709`

**Pull request closed without merging**
