### PR TITLE
[PHP] Update for simps

### PR DESCRIPTION
**Pull request by sy-records**
@waghanza Please review this.

You can close #2439 , thanks.

### CODE REVIEW

**Comment by waghanza** [comment]
@sy-records I have to do more checking, I have a `crystal` error
~~~crystal
Unhandled exception: Unexpected end of http response (Exception)
  from /usr/share/crystal/src/http/client.cr:589:5 in 'exec_internal'
  from /usr/share/crystal/src/http/client.cr:576:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:698:5 in 'exec'
  from /usr/share/crystal/src/http/client.cr:730:7 in 'exec'
  from /usr/share/crystal/src/http/client.cr:402:3 in 'get'
  from spec/benchmark_spec.cr:13:7 in '->'
  from /usr/share/crystal/src/spec/context.cr:255:3 in 'describe'
  from /usr/share/crystal/src/spec/methods.cr:18:5 in 'describe'
  from spec/benchmark_spec.cr:10:1 in '__crystal_main'
  from /usr/share/crystal/src/crystal/main.cr:106:5 in 'main_user_code'
  from /usr/share/crystal/src/crystal/main.cr:92:7 in 'main'
  from /usr/share/crystal/src/crystal/main.cr:115:3 in 'main'
  from __libc_start_main
  from _start
  from ???
~~~
like for the previous `PR`

**Comment by waghanza** [comment]
@sy-records seems to be OK with you last commit :+1:

**Comment by sy-records** [comment]
I just tested it is no problem, I modified `IndexController.php`

https://github.com/the-benchmarker/web-frameworks/pull/2444/files#diff-4f28c722d29db6956533e2db6a8c4e06

**Comment by sy-records** [comment]
@waghanza Can you update the results list ?

**Pull request merged**
