### PR TITLE
Add a web server setting in main.go

### PR DESCRIPTION
**Pull request by johng-cn**
@waghanza 
Just add a setting for web server to disable static file service(which is enabled by default), to increase the performance of router.

BTW, the `GF` respository was also updated, but no updating the release number, is there any cache for this docker building?

### CODE REVIEW

**Comment by waghanza** [comment]
> is there any cache for this docker building?
none, even on CI ;-)

@johng-cn I'm working on a `cloud` **version** to reduce the **noise** created by `docker`
https://github.com/waghanza/http-benchmark/tree/cloudify

If you want to collaborate it will be a :heart:

**Comment by johng-cn** [comment]
@waghanza 

> I'm working on a cloud version to reduce the noise created by docker
https://github.com/waghanza/http-benchmark/tree/cloudify
If you want to collaborate it will be a ❤️

It looks like an another nice work. I don't know how to do it, but I like it and will keep on watching your progress. 👍

**Comment by waghanza** [comment]
@johng-cn I do not know either :stuck_out_tongue: 

What will be helpful to me is to know how to compile `go` inside a `docker` (based on **ubuntu 18.10**) and retrieve the binary file

**Comment by waghanza** [comment]
@johng-cn could you rebase your branch **master** (or move commits to an other branch, so as I can do it) ?

**Comment by johng-cn** [comment]
@waghanza OK, I'll deal with it later.

**Comment by johng-cn** [comment]
@waghanza done!

**Pull request merged**
