### PR TITLE
Update maven

### PR DESCRIPTION
**Pull request by waghanza**
Hi @greenlaw110,

This `PR` updates `maven` to  `3.6`, still on `jdk` **8**

Is `act` fully compliant with this version ?

Regards,

### CODE REVIEW

**Comment by greenlaw110** [comment]
@waghanza JDK 8 is all goo and I don't think there will be a problem with maven 3.6.

**Comment by waghanza** [comment]
@greenlaw110 absolutely and using **latest** will use `jdk 11`
https://github.com/carlossg/docker-maven/issues/93

I'll upgrade this on `act` new release :stuck_out_tongue_closed_eyes:

**Comment by greenlaw110** [comment]
@waghanza act doesn't work with Java 11 at the moment. And I don't have a concrete plan on when 2.0 (aims to Java 11) will be out ...

**Comment by waghanza** [comment]
@greenlaw110 I'll keep in sync, then :tada:

**Pull request merged**
