### PR TITLE
Athena Upgrade

### PR DESCRIPTION
**Pull request by Blacksmoke16**
* Upgrade Athena to `0.13.x`
* Bump Dockerfile to use Crystal `0.36.1`
* Add new generated files to .gitignore
* Add `jq` to requirements section in README

### CODE REVIEW

**Comment by Blacksmoke16** [comment]
IDK why CI is failing.  I'm deff returning an empty string now.

**Comment by waghanza** [comment]
seems to returns `""` not an empty string

https://github.com/the-benchmarker/web-frameworks/pull/3926/checks?check_run_id=1846883774#step:7:15

**Comment by Blacksmoke16** [comment]
@waghanza I was returning `nil` before and CI still was failing.  Something doesn't seem right here.

**Comment by waghanza** [comment]
Indeed `Nil` has the right behavior. Seems weird for me to have a block that returns a nullable object when speaking of HTTP, btw

**Comment by Blacksmoke16** [comment]
@waghanza In Athena having an explicit `Nil` return type maps to a `204 No Content` response.

**Pull request merged**
