### PR TITLE
Clojure.luminus

### LINKED ISSUE #1391: Introduce luminus
+ Language : clojure
+ Repo : https://github.com/luminus-framework/luminus-template
+ Author : @yogthos

### PR DESCRIPTION
**Pull request by whiplash**
Closes #1391 #2645

### CODE REVIEW

**Comment by waghanza** [comment]
Could you take a quick look @yogthos, and give us your feedback ?

We want to have a **production-grade** `luminus` app :heart:

**Comment by yogthos** [comment]
Hi,

Just looked over the commit, and the app looks reasonable to me. The default template is tuned to be production ready out of the box. When the app is built using `lein uberjar`, it will produce a standalone runnable jar that can be used for benchmarking.

**Comment by whiplash** [comment]
Hi @yogthos and thanks. Just one question. I wanted to take out the layout part, since it's not really needed here. What do you say? Also `nrepl` isn't needed, is it?

**Comment by yogthos** [comment]
Some files could be trimmed, but they shouldn't affect runtime performance. If the benchmark gets expanded later, these might be useful for additional functionality.

**Comment by whiplash** [comment]
Thanks.

**Pull request merged**
