### PR TITLE
update results

### PR DESCRIPTION
**Pull request by waghanza**
Welcome @jaguililla, this `PR` will a `hexagon` on https://web-frameworks-benchmark.netlify.app/result

We have still failing frameworks :
- `baize-wsgi` @abersheeran 
- `nawa` @jatofg
- `naturaljs-router` @jesusvilla

### CODE REVIEW

**Comment by abersheeran** [comment]
I don't know why baize-wsgi still failing, the code can work in my server 🤔

**Comment by waghanza** [comment]
Nop.

Btw, I'll explore this this weed end

**Comment by jesusvilla** [comment]
@waghanza naturaljs-router works now

**Comment by waghanza** [comment]
will be updated soon

**Pull request merged**
