### PR TITLE
Update results

### PR DESCRIPTION
**Pull request by waghanza**
###### Failing frameworks

- [x] vibed
- [ ] archttp
- [ ] kitura
- [ ] jennet
- [ ] cyclone
- [x] finatra
- [ ] nawa
- [ ] fyrejet-uwebsockets
- [ ] naturaljs-router

### CODE REVIEW

**Comment by waghanza** [comment]
With a `dub.sdl`
```d
name "server"
license "MIT"
versions "VibeNoSSL"
dependency "vibe-d:web" version="~>0.9.4"
dependency "vibe-d:tls" version="~>0.9.5"
subConfiguration "vibe-d:tls" "notls"
```
I have still `Invalid variable: DC` @kubo39

**Comment by rajkumardusad** [comment]
Screenshot_2023-03-26-21-03-06-48_40deb401b9ffe8e1df2f1cc5ba480b12

I think this framework is taking too much time, is it ok or something is wrong?

**Comment by waghanza** [comment]
You are right @rajkumardusad, `camping` is timeouting, see https://github.com/camping/camping/issues/134. 

Probably, we shall remove it, and restore when v3 is out

**Comment by waghanza** [comment]
@zoujiaqing seems that `archttp` stops at high concurrency. could you check this point ?

**Comment by rajkumardusad** [comment]
> You are right @rajkumardusad, `camping` is timeouting, see [camping/camping#134](https://github.com/camping/camping/issues/134).
> 
> Probably, we shall remove it, and restore when v3 is out

Screenshot_2023-03-26-21-54-33-48_40deb401b9ffe8e1df2f1cc5ba480b12

I think we should skip this framework, its taking too much time.

**Comment by waghanza** [comment]
You are right @rajkumardusad. I'll restore it when a newer version will be out

**Review by rajkumardusad — APPROVED** [review]

**Comment by waghanza** [comment]
This `PR` also update `sanic` @ahopkins

**Comment by zoujiaqing** [comment]
> @zoujiaqing seems that `archttp` stops at high concurrency. could you check this point ?

have some error messages?
I need more information.

Thank you ;)

**Comment by waghanza** [comment]
At some concurrency, `archhttp` stop. Maybe we should add some logs in an other PR @zoujiaqing

**Pull request merged**
