### PR TITLE
[C++] Add nawa

### LINKED ISSUE #3634: Add nawa
Hi @jatofg,

Would you mind to add (or consent that we add) [nawa](https://github.com/jatofg/nawa) in `here` ?

This project compare performance based on 3 routes :

+ `GET` `/`, **SHOULD** return a successful status code and an empty string
+ `GET` `/user/:id`, **SHOULD** return a successful status code and the id
+ `POST` `/user`, **SHOULD** return a successful status code and an empty string

Regards,

### PR DESCRIPTION
**Pull request by waghanza**
Hi @jatofg,

This `PR` adds `nawa` in here.

ℹ️ I have some warnings
```
CMake Warning (dev) at build/_deps/cppnetlib-src/CMakeLists.txt:8 (project):
  Policy CMP0048 is not set: project() command manages VERSION variables.
  Run "cmake --help-policy CMP0048" for policy details.  Use the cmake_policy
  command to set the policy and suppress this warning.

  The following variable(s) would be set to empty:

    PROJECT_VERSION
    PROJECT_VERSION_MAJOR
    PROJECT_VERSION_MINOR
This warning is for project developers.  Use -Wno-dev to suppress it.
```

when using `cmake -DCMAKE_BUILD_TYPE=release ..`

I will post more info when CI passes

-----
May I notify you on each update that affects `nawa` here ?

-----
Closes #3634 
Closes #3645

### CODE REVIEW

**Comment by jatofg** [comment]
Hi, this is a warning from a dependency. Just ignore it. If you dislike it, you can change the cmake command to 
`cmake -DCMAKE_BUILD_TYPE=release -Wno-dev ..`

You can notify me of updates, of course

**Comment by waghanza** [comment]
compilation failed @jatofg 

see https://the-benchmarker.semaphoreci.com/jobs/c1c8d0be-1b3c-4a1c-8ceb-d89d3ee75f48

**Comment by jatofg** [comment]
Strange, I haven't encountered this problem before. Seems to be an issue with the specific g++ compiler. I've committed a fix to nawa, which should solve the problem. Could you please try to increase the nawa version to v0.6.1 (by changing the `git clone --branch v0.6.0 https://github.com/jatofg/nawa` line in the download section to `git clone --branch v0.6.1 https://github.com/jatofg/nawa`)?

**Comment by waghanza** [comment]
Thanks @jatofg. By curiosity (and since it could be easier to integrate), have you considered using any package manager, like https://conan.io/ ?

**Comment by jatofg** [comment]
Yes, I'm planning to support a package manager. It's on my list, but not a number 1 priority yet

**Pull request merged**
