### PR TITLE
Intoduce kami

### PR DESCRIPTION
**Pull request by waghanza**
Hi @guregu,

This `PR` addresses #663

I've added `kami` in this benchmark.

Could you check our implementation ?

Results found (docker on 4 x CPU / 8gb)

| Language (Runtime) | Framework (Middleware) | Average | 50th percentile | 90th percentile | 99th percentile | 99.9th percentile | Standard deviation |
|---------------------------|---------------------------|----------------:|----------------:|----------------:|----------------:|----------------:|----------------:|
| go (1.11) | [fasthttprouter](http://godoc.org/github.com/buaazp/fasthttprouter) (0.1) | 5.55 ms | 5.05 ms | 8.53 ms | 14.78 ms | 142.99 ms | 2863.00 | 
| go (1.11) | [chi](http://github.com/go-chi/chi) (4.0) | 13.00 ms | 9.39 ms | 21.24 ms | 118.09 ms | 427.88 ms | 21244.67 | 
| go (1.11) | [muxie](http://godoc.org/github.com/kataras/muxie) (1.0) | 11.41 ms | 9.59 ms | 15.76 ms | 73.15 ms | 335.53 ms | 14806.33 | 
| go (1.11) | [iris](http://iris-go.com) (11.1) | 12.04 ms | 9.93 ms | 16.93 ms | 68.31 ms | 523.91 ms | 19680.00 | 
| go (1.11) | [gin](http://gin-gonic.github.io/gin) (1.3) | 12.55 ms | 10.19 ms | 18.48 ms | 83.77 ms | 388.75 ms | 16719.67 | 
| go (1.11) | [echo](http://echo.labstack.com) (4.0) | 14.16 ms | 10.32 ms | 21.00 ms | 129.89 ms | 482.05 ms | 24880.33 | 
| go (1.11) | [kami](http://github.com/guregu/kami) (2.2) | 15.06 ms | 10.73 ms | 24.93 ms | 139.06 ms | 403.63 ms | 24584.00 | 
| go (1.11) | [beego](http://beego.me) (1.11) | 13.87 ms | 10.80 ms | 22.94 ms | 106.79 ms | 357.95 ms | 19435.00 | 
| go (1.11) | [gorilla-mux](http://www.gorillatoolkit.org/pkg/mux) (1.7) | 16.00 ms | 11.04 ms | 30.21 ms | 132.70 ms | 380.82 ms | 24787.33 | 
| go (1.11) | [gf](http://goframe.org) (1.5) | 16.04 ms | 13.33 ms | 22.05 ms | 106.91 ms | 433.62 ms | 18551.00 |

### CODE REVIEW

**Comment by guregu** [comment]
Hello, looks good to me. Thanks for adding it!

**Comment by waghanza** [comment]
@guregu I'm not sure of `go.mod`

**Comment by guregu** [comment]
@waghanza Since the package predates modules, I think what you had before was correct. I tried it myself and got this:
```
module main

require (
        github.com/dimfeld/httptreemux v5.0.1+incompatible // indirect
        github.com/guregu/kami v2.2.1+incompatible
        github.com/zenazn/goji v0.9.0 // indirect
        golang.org/x/net v0.0.0-20190227022144-312bce6e941f // indirect
)
```

**Comment by waghanza** [comment]
@guregu As I understand what you're saying, I need to fix version of 
+ kami
+ httptreemux
+ goji
+ x/net

**Comment by guregu** [comment]
@waghanza Yes, I think so. Basically just revert d47865faf6fb0f88ae23e1303c14dc4da7f37924. 
I'm not a modules expert unfortunately. I think it would work either way but it's better to specify everything.

**Comment by waghanza** [comment]
For me specifying everything is redundant. The version of `kami` has to been set by this implementation, but if we have to put `goji` version here, I think we are locking to version (for me the `goji` version has to be set by `kami`)

@johngcn @kataras  What do you think ?

**Comment by kataras** [comment]
Looking at the results, I think something went wrong when running benchmarks, beego can't be faster from gorilla mux, muxie and iris can't be slower from chi it is impossible if you look their codebase.

**Comment by waghanza** [comment]
@kataras Sure, the results are not (yet) representative here (I'm on it on #632)

However, the question here is how to deal with dependency in `go`, @guregu suggest https://github.com/the-benchmarker/web-frameworks/pull/988#issuecomment-467777091 but I find it to heavy, and I suggest having https://github.com/waghanza/http-benchmark/blob/add_kami/go/kami/go.mod

As a `gopher`, I might have some interesting feedback :heart:

**Comment by johngcn** [comment]
@waghanza I think you should need no worry about its dependences, but the author should. Anyhow, the `go.mod` must be used in `go` project, let the author take care of it.

**Comment by guregu** [comment]
Sorry I'm not used to the new GitHub review system. Anyway, feel free to merge IMO.

**Comment by waghanza** [comment]
Don't be sorry for a lack of skills, we are here to learn :heart:

**Comment by waghanza** [comment]
@guregu We have a `bot` that take care of dependencies here, @dependabot[bot].

Do you mind me to require your approval on each `kami` **version update** ?

**Comment by guregu** [comment]
Cool, and sure you can ping me for updates.

**Pull request merged**
