### PR TITLE
[Scala] Upgrade to 2.13

### LINKED ISSUE #2558: Wrong version for akka
Hi,

`akka` is displayed as **10.1** on results.

However, the version used is any of **10.0.x**

Regards,

### PR DESCRIPTION
**Pull request by waghanza**
Hi @mfirry,

Thanks for your work in #2559. I have taken it to create this `PR`, it could be considered as the parent on.

We have to :
+ [x] Upgrade `scala` to `2.13`
+ [x] Update `akka`
+ [x] Update `http4s`

Could you upgrade `http4s`, as you know, I could not do it myself :heart: 

Regards,

------------------------
Closes #2558 #2557

### CODE REVIEW

**Comment by mfirry** [comment]
Ok. Should I make a PR on `waghanza/http-benchmark/tree/scala/v2.13`?

**Comment by waghanza** [comment]
Nop. I add your work in this :heart:

**Comment by mfirry** [comment]
Let me know if you need me. Bye.

**Comment by mfirry** [comment]
Hi, how can I talk to you privately? (email at my github nickname @ hotmail . com) or skype mfirrinc (i'll delete this comment in 20 minutes)

**Pull request merged**
