### PR TITLE
update router.cr for improved performance

### PR DESCRIPTION
**Pull request by stakach**
See: https://github.com/tbrand/router.cr/pull/29

### CODE REVIEW

**Comment by proyb6** [comment]
version.cr also need update from 0.2.5.

**Comment by waghanza** [comment]
@proyb6 I don't understand

**Comment by proyb6** [comment]
> @proyb6 I don't understand

@waghanza Sorry, I was referring to this need to be update as well as ```shards install``` notified ```0.2.5 at 0.2.6```
https://github.com/tbrand/router.cr/blob/master/src/router/version.cr#L2

**Comment by tbrand** [comment]
Oh that's my bad. I'll fix it.

**Comment by tbrand** [comment]
It's fixed on 0.2.7.

**Pull request merged**
