### PR TITLE
Optimize compilation

### PR DESCRIPTION
**Pull request by monocoder**
Local testing - opt: speed option has the effect of improving running speed.

### CODE REVIEW

**Comment by waghanza** [comment]
Is it only for happyx ? Suitable for production?

**Comment by monocoder** [comment]
This is the basic command line switch for nim compilation, which should not only be applicable to HappyX.
[https://nim-lang.org/1.2.0/nimc.html#compiler-usage](url)

**Comment by waghanza** [comment]
If it is suitable for production could you apply it for all nim frameworks, please ?

**Comment by monocoder** [comment]
OK，[#7350 ](https://github.com/the-benchmarker/web-frameworks/pull/7350)

**Review by waghanza — APPROVED** [review]

**Pull request merged**
