### PR TITLE
[Ruby] Add pakyow

### LINKED ISSUE #1004: Introduce pakyow
+ Language : ruby
+ Repo : https://github.com/pakyow/pakyow
+ Author : @bryanp

### PR DESCRIPTION
**Pull request by waghanza**
Hi @bryanp,

This `PR` adds https://github.com/pakyow/pakyow.

However, when I start it with `bundle exec pakyow boot -e production`, this seems not to have any server listening to port `3000`

----------------------
Closes #1004

### CODE REVIEW

**Comment by bryanp** [comment]
@waghanza Pakyow won't boot in production without a configured secret. Add this to `config/environment.rb`:

```ruby
Pakyow.configure :production do
  config.secrets = ["sekret"]
end
```

**Comment by waghanza** [comment]
Thanks @bryanp. Could you quick review this implementation ?

Also, may I add you as `CODEOWNER` to ping you on each `pakyow` modification`here` ?

**Comment by bryanp** [comment]
@waghanza Looks good! And yes, feel free to add me as `CODEOWNER`.

**Comment by waghanza** [comment]
@bryanp Results updated => https://github.com/the-benchmarker/web-frameworks#results :tada:

**Comment by bryanp** [comment]
Thanks! I'll plan to update this when `v1.1` is released.

**Pull request merged**
