### PR TITLE
slim-roadrunner and slim-swoole

### PR DESCRIPTION
**Pull request by dominikzogg**
@waghanza it seems @l0gicgate is the project lead of slim, so i've added him as code owner

### CODE REVIEW

**Comment by l0gicgate** [comment]
@dominikzogg thank you for this, I’ve been so busy with work I haven’t had a ton of spare time to get this done. I really appreciate it.

**Comment by dominikzogg** [comment]
@l0gicgate you're welcome

**Comment by waghanza** [comment]
@dominikzogg @l0gicgate I've updated results in https://github.com/the-benchmarker/web-frameworks#results

**Comment by dominikzogg** [comment]
@waghanza thank you

**Pull request merged**
