### PR TITLE
[D] Fix socket read error

### LINKED ISSUE #6609: [D] Frameworks issues
Hi @waghanza 

I've tried to run servers handy and serverino locally with the command:
`wrk -H 'Connection: keep-alive' -d 5s -c 512 --timeout 8 -t 8 http://127.0.0.1:3000`

They showed some values of requests, and still servers continue to work without any errors.
But I didn't use Dockers. Just run servers and wrk locally.
Can you get the error logs from your run or give any recommendations to test them locally?

### PR DESCRIPTION
**Pull request by waghanza**
Hi @cyrusmsk,

I open this PR in order to solve #6609

-----
Closes #6609

### CODE REVIEW

**Comment by cyrusmsk** [comment]
Did it solved also handy server issues?

**Comment by waghanza** [comment]
Nop, I opened this PR in order to find a solution, but I didn't find yet

**Comment by waghanza** [comment]
@cyrusmsk I managed to run also on CI and I have the same kind of results
https://github.com/the-benchmarker/web-frameworks/actions/runs/5866851930/job/15906476528?pr=6623#step:10:119

This is however an ubuntu 22.04 not like my dist (fedora 38).

Not sure to understand how you can have different results using docker layer.

**Comment by waghanza** [comment]
May you have a clue @zoujiaqing

I have the issue for `handy`, `serverino` and `vibe.d` only. The other are OK

- https://github.com/the-benchmarker/web-frameworks/actions/runs/5866851930/job/15906475910?pr=6623#step:10:119
- https://github.com/the-benchmarker/web-frameworks/actions/runs/5866851930/job/15906476068?pr=6623#step:10:119
- https://github.com/the-benchmarker/web-frameworks/actions/runs/5866851930/job/15906476371?pr=6623#step:10:119

**Comment by cyrusmsk** [comment]
> Not sure to understand how you can have different results using docker layer.
@waghanza I'm running docker on M1 Mac.
This is what I got for handy:
wrk -H 'Connection: keep-alive' -d 5s -c 64 --timeout 8 -t 8 http://127.0.0.1:3000
Running 5s test @ http://127.0.0.1:3000
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    21.98ms   67.59ms 428.76ms   93.65%
    Req/Sec     1.25k   411.63     1.65k    87.50%
  16393 requests in 5.04s, 1.24MB read
  Socket errors: connect 0, read 16393, write 0, timeout 0
Requests/sec:   3254.27
Transfer/sec:    251.06KB

For serverino almost the same result:
 wrk -H 'Connection: keep-alive' -d 5s -c 64 --timeout 8 -t 8 http://127.0.0.1:3000
Running 5s test @ http://127.0.0.1:3000
  8 threads and 64 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    25.50ms   77.43ms 473.15ms   93.27%
    Req/Sec     1.20k   463.77     1.63k    82.35%
  16389 requests in 5.03s, 0.00B read
  Socket errors: connect 0, read 16389, write 0, timeout 0
Requests/sec:   3255.35
Transfer/sec:       0.00B

**Comment by waghanza** [comment]
So all requests has a socket read error like me.

**Comment by cyrusmsk** [comment]
> So all requests has a socket read error like me.

Yes. But author of handy used Apache JMeter and the server for his projects and he said there were no any errors or problems. So he doesn’t know why wrk thinks there is read errors.
So maybe we could then just exclude those frameworks from the list.

**Comment by waghanza** [comment]
For the moment they are hidden (I don't mind doing it manually), but I'm very curious about the reason(s) behind. Let's keep them for now, at least before I automate the results publication

**Comment by waghanza** [comment]
Probably, Apache communications are made differently. For example keeping an opened socket

**Comment by waghanza** [comment]
It could be interesting though to replicate the handy author configuration (having an Apache in front of handy) inside a docker and see what is going on.

Maybe handy handle well Unix socket communication but not http based communication @cyrusmsk

**Comment by cyrusmsk** [comment]
Maybe we can ping @tchaloupka if he has any similar issues in his benchmark. He used serverino and wrk as well.

Hi Tomáš. Have you faced with any socket errors in your run with wrk?

**Comment by cyrusmsk** [comment]
> It could be interesting though to replicate the handy author configuration (having an Apache in front of handy) inside a docker and see what is going on.
> 
> Maybe handy handle well Unix socket communication but not http based communication @cyrusmsk

sounds too advanced for me :)
I've prepared a Dockerfile update to switch on LTO (send it soon). But I'm not sure how to deal with low-level errors of sockets.

**Comment by waghanza** [comment]
cc @zoujiaqing

**Comment by andrewlalis** [comment]
@waghanza yes, I use nginx as a reverse proxy for handy-http so that I get HTTP 2 and other benefits, but I suspect that there's an implementation detail in `wrk` that's causing it to report socket read errors where there are none. I've ran tests with Apache JMeter and it does not report errors when load-testing handy-http, and various browsers have no problem interacting with it.

**Comment by waghanza** [comment]
@trikko should the server close connection with keep alive header ?

**Comment by trikko** [comment]
> @trikko should the server close connection with keep alive header ?

From RFC:

«Servers will usually have some time-out value beyond which they will no longer maintain an inactive connection. Proxy servers might make this a higher value since it is likely that the client will be making more connections through the same server. The use of persistent connections places no requirements on the length (or existence) of this time-out for either the client or the server.

When a client or server wishes to time-out it SHOULD issue a graceful close on the transport connection. Clients and servers SHOULD both constantly watch for the other side of the transport close, and respond to it as appropriate. If a client or server does not detect the other side's close promptly it could cause unnecessary resource drain on the network.»

**Comment by adamdruppe** [comment]
a server closing the connection gracefully returns 0 to that read function but wrk only reports as an error if it is -1.

But yeah, i don't remember exactly what I did to change this in mine but it seems to work ok now.

**Comment by trikko** [comment]
shutdown() vs close() ?

**Comment by waghanza** [comment]
or both

https://dlang.org/library/std/socket/socket.close.html

**Comment by waghanza** [comment]
or both
https://dlang.org/library/std/socket/socket.close.html

**Comment by trikko** [comment]
Yes but I think you *should* wait for shutdown message to be received. But, as said, too bad if they didn't already received it: I close connection anyway. It doesn't really change anything in this practical case.

**Comment by trikko** [comment]
Finally I have access to my laptop. Something strange is related to ```-H 'Connection: keep-alive'```. 
Without that, wrk does not report any error.

Http 1.1 has keep-alive by default, so that header is not required. Still trying to understand if it's a client-side or server-side problem. (and without that header it gives better results!)

**Comment by trikko** [comment]
Sorry I deleted the last comment by mistake.
Today I have access to my laptop. I'm doing some tests. I see you use ```-H "connection:keep-alive"``` but http 1.1 use keep-alive by default.

Removing that argument from command line, it works fine. No errors are reported and serverino has better performance.

I'm trying to understand if it is a server-side or a client-side problem.

**Comment by trikko** [comment]
Hmm I wonder if it is a bug in wrk.  Using ```-H "Connection:keep-alive"``` works fine.

Probably they don't check for spaces after ":"? 
Their header parser is a quite complex state machine :)
https://github.com/wg/wrk/blob/a211dd5a7050b1f9e8a9870b95513060e72ac4a0/src/http_parser.c#L1414

**Comment by cyrusmsk** [comment]
@trikko  When I tried -H "Connection:keep-alive" I've got segfaults.. Can you share whole wrk command please?
I've used this one
`wrk -H 'Connection:keep-alive' -d 5s -c 64 --timeout 8 -t 8 http://127.0.0.1:3000`

On Docker it was just some logs: https://paste.myst.rs/9um95tts

When I tried to run locally (macOS) I've got also extra rows:

★ [051763] [l] 2023-08-17 15:53 [connectionhandler.d:0315] Socket error on read. Resource temporarily unavailable
core.exception.ArrayIndexError@../../../../../.dub/packages/serverino-0.4.5/serverino/source/serverino/daemon.d(437): index [119] is out of bounds for array of length 119
----------------
??:? onArrayIndexError [0x104d8e36f]
??:? _d_arraybounds_index [0x104d8e8ff]
../../../../../.dub/packages/serverino-0.4.5/serverino/source/serverino/daemon.d:437 void serverino.daemon.Daemon.wake!(app).wake(std.typecons.Typedef!(serverino.config.DaemonConfig*, null, null).Typedef) [0x104ba74fb]
../../../../../.dub/packages/serverino-0.4.5/serverino/source/serverino/main.d:175 int serverino.main.wakeServerino!(app).wakeServerino(ref serverino.config.ServerinoConfig) [0x104ba3997]
../../../../../.dub/packages/serverino-0.4.5/serverino/source/serverino/main.d:147 int app.__mixin8.__mixin2.mainServerinoLoop(immutable(char)[][]) [0x104ba3813]
../../../../../.dub/packages/serverino-0.4.5/serverino/source/serverino/main.d:109 _Dmain [0x104ba39db]
■ [051766] [l] 2023-08-17 15:53 [worker.d:0241] Killing worker. [REASON: socket closed?]

**Comment by trikko** [comment]
Oh, yes. That's a regression i fixed some days ago. Just update to last
serverino.

**Comment by waghanza** [comment]
Same for me @trikko 
https://github.com/the-benchmarker/web-frameworks/actions/runs/5891481803/job/15978641101?pr=6623#step:10:125

**Comment by cyrusmsk** [comment]
For me 0.4.6 also hasn't solved the issue with socket read error(

**Comment by trikko** [comment]
Also removing the header at all?

**Comment by cyrusmsk** [comment]
> Also removing the whole connection header?

Yes. I’ve tried all with space and without space and without this -H option at all

**Comment by trikko** [comment]
On linux:
```andrea /tmp/serv > wrk -H 'connection: keep-alive' -d 5s -c 512 --timeout 8 -t 4 http://127.0.0.1:3000
Running 5s test @ http://127.0.0.1:3000
  4 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    45.89ms  264.41ms   3.36s    97.32%
    Req/Sec     8.78k     1.25k   11.57k    66.00%
  174673 requests in 5.05s, 20.16MB read
  Socket errors: connect 0, read 174670, write 0, timeout 0
Requests/sec:  34597.58
Transfer/sec:      3.99MB
andrea /tmp/serv > wrk -H 'connection:keep-alive' -d 5s -c 512 --timeout 8 -t 4 http://127.0.0.1:3000
Running 5s test @ http://127.0.0.1:3000
  4 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency   159.11ms  683.46ms   5.01s    94.42%
    Req/Sec    19.46k     7.52k   29.90k    39.61%
  298293 requests in 5.06s, 34.42MB read
Requests/sec:  58951.33
Transfer/sec:      6.80MB
```

Just to be sure, add this to your serverino config:

```
.setHttpTimeout(10.seconds)
.enableKeepAlive(180.seconds);
```

**Comment by cyrusmsk** [comment]
@waghanza I've tested different tool instead of wrk (https://github.com/codesenberg/bombardier)
And it seems it doesn't have issues for serverino.

Did you test proposed changes on linux btw? Because on macOS even with 'connection:keep-alive' wrk is still showing soccer read errors.

**Comment by waghanza** [comment]
Yes, both macros and Linux remain in error.

Will give another try will timeout set on the servernio side.

**Comment by waghanza** [comment]
Maybe using https://github.com/lnx-search/rewrk could be a workaround

**Comment by waghanza** [comment]
Wdyt about this issue @OvermindDL1 @Ethosa @tbrand @jeremyevans @ahopkins @krishnaTORQUE @ioquatix ?

**Comment by ioquatix** [comment]
Try my fork of wrk it fixed some bugs.

**Comment by waghanza** [comment]
Mmh, seems interesting https://github.com/wg/wrk/compare/master...ioquatix:wrk:master

**Comment by krishnaTORQUE** [comment]
@waghanza  Definitely there are some bugs in header that I can see.
Also from `ubuntu-latest` >> `ubuntu-22` make sense to me.

**Comment by trikko** [comment]
rewrk sounds like another app anyway, not a fork.

**Comment by waghanza** [comment]
I think we should disable http pipelining. As I know, this feature is enabled by some browsers by default. But what you check here is like an API, not a website so http pipelining could be inaccurate here

**Comment by waghanza** [comment]
Related to https://github.com/the-benchmarker/web-frameworks/issues/5329

**Comment by trikko** [comment]
Which browsers? I don't think it is enabled by anyone. Curl completly removed pipeline support in 2019:

https://daniel.haxx.se/blog/2019/04/06/curl-says-bye-bye-to-pipelining/

**Comment by ioquatix** [comment]
FWIW, I did not observe `wrk` doing pipelining, but maybe I did not look close enough.

**Comment by trikko** [comment]
If only wrk could give better error reports...

**Comment by adamdruppe** [comment]
I wonder what was so hard about the http pipelining. I guess I never tested it specifically so maybe I did it wrong too, but it seems like it would be trivial to implement since the tcp stream just works that way anyway.

**Comment by trikko** [comment]
It is implemented indeed in Serverino (almost, there's a bug fixed here locally). It adds extra work: for example you need to keep a queue of requests (or simply a buffer) since you must not run them in parallel.

**Comment by waghanza** [comment]
> > FWIW, I did not observe `wrk` doing pipelining, but maybe I did not look close enough.
> 
> We use header in https://github.com/the-benchmarker/web-frameworks/blob/master/.tasks/collect.rake#L70
> 
> PS : I confess that the codebase is not very clean, I should clean it before considering this project stable
> 
> @waghanza did you mean to edit my comment with your reply? :)

Sorry @ioquatix. I badly used GitHub Mobile app

**Comment by waghanza** [comment]
I think I am confused about pipelining, and keep-live. I'll test @ioquatix fork this Saturday, to display results on Monday (if accurate for all languages)

**Comment by trikko** [comment]
In the meanwhile I've released a new version of serverino.

Please notice that wrk use http/1.1 and ```keep-alive``` is enable by default.
It sounds like ```-H "connection: keep-alive"``` tricks wrk because of that space!

You should remove that header or use ```-H "connection:keep-alive"``` (but it is implicit)

**Comment by ahopkins** [comment]
Sorry I'm late to the conversation. What specifically do you want me to weigh in upon? The explicit nature of `keep-alive` seems desired, even if enabled by default.

**Comment by cyrusmsk** [comment]
@waghanza just to pay your attention in this PR, that handy version bumped to 7.10.4, serverino to 0.4.7 and cgi to 11.0.1

**Pull request closed without merging**
