### PR TITLE
New release

### PR DESCRIPTION
**Pull request by waghanza**
#### Missing frameworks

+ [x] kore => pinged for help in https://discord.com/channels/955018653504516137/1060984904306917539 cc @OvermindDL1 @ohler55 
+ [x] act => https://github.com/actframework/actframework/issues/1433
+ [ ] spliffy
+ [ ] vixeny-bun
+ [ ] turbo
+ [ ] symfony
+ [ ] httpz

### CODE REVIEW

**Comment by waghanza** [comment]
@dominikzog With
```json
{
  "dependencies": {
    "@chubbyts/chubbyts-framework": "~1.9.0",
    "@chubbyts/chubbyts-framework-router-path-to-regexp": "*",
    "@chubbyts/chubbyts-http": "*",
    "@chubbyts/chubbyts-uwebsockets-http-bridge": "*",
    "@types/node": "22"
  }
}
```, I've checked that **@chubbyts/chubbyts-uwebsockets-http-bridge** is installed in `1.2.1` (not the latest), is their a way to say that we want to have the latest stable release of a package in `npm` ?

cc @dalisoft @mario-huang @KostyaTretyak

**Comment by KostyaTretyak** [comment]
- `"@chubbyts/chubbyts-uwebsockets-http-bridge": "*"` - any version
- `"@chubbyts/chubbyts-uwebsockets-http-bridge": "^1.2.1"` - this is equal to `>= 1.2.1 < 2`
- `"@chubbyts/chubbyts-uwebsockets-http-bridge": "~1.2.1"` - this is equal to `>= 1.2.1 < 1.3`
- `"@chubbyts/chubbyts-uwebsockets-http-bridge": "1.2.1"` - accept only `v1.2.1`

**Comment by waghanza** [comment]
Thanks @KostyaTretyak. That's what I understand throw the doc. However, with
```json
{
  "dependencies": {
    "@chubbyts/chubbyts-framework": "~1.9.0",
    "@chubbyts/chubbyts-framework-router-path-to-regexp": "*",
    "@chubbyts/chubbyts-http": "*",
    "@chubbyts/chubbyts-uwebsockets-http-bridge": "*",
    "@types/node": "22"
  }
}
```
and of course `npm install`, I can see 
```
root@65a9a7a2bd38:/usr/src/app# npm list
app@ /usr/src/app
+-- @chubbyts/chubbyts-framework-router-path-to-regexp@1.4.1
+-- @chubbyts/chubbyts-framework@1.9.4
+-- @chubbyts/chubbyts-http@1.2.1
+-- @chubbyts/chubbyts-uwebsockets-http-bridge@1.2.1
`-- @types/node@22.10.2
```
and I can see that the latest version of https://www.npmjs.com/package/@chubbyts/chubbyts-http-uwebsockets-bridge is not used

**Comment by waghanza** [comment]
@kubo39 @cyrusmsk @trikko I've update **D** since LDC2 1.40 has been released https://github.com/ldc-developers/ldc/releases/tag/v1.40.0

**Comment by waghanza** [comment]
I think I've found @dominikzogg. The package used was deprecated in favor of `@chubbyts/chubbyts-http-uwebsockets-bridge`

**Comment by dominikzogg** [comment]
@waghanza looks like i renamed it without thinking about the benchmark. Thanks for catching it.

**Pull request merged**
