### PR TITLE
Disable logging

### LINKED ISSUE #2622: Homogenize logging feature
Hi,

Some framework are made to disable logging. 

To ensure fairness (at least maximum we can do), we need to have a **production-level** logging level.

For example, `lucky` is configured to handle `info` logs.

Regards,

### PR DESCRIPTION
**Pull request by waghanza**
Hi,

This `PR` disable all **logging** features in `here`

As @Blacksmoke16 points out, the purpose of this project is to compare **frameworks**.

Having `logging` enable will mess-up the result, and will lead to a wrong comparison.

+ [ ] C
+ [ ] C++
+ [x] C#
+ [ ] Clojure
+ [x] Crystal => #3051 
+ [ ] Dart
+ [ ] Elixir
+ [x] F#
+ [ ] Go
+ [ ] Haskell
+ [x] Java => #3054 
+ [ ] Javascript
+ [ ] Julia
+ [ ] Kotlin
+ [ ] Perl
+ [ ] PHP
+ [x] Python => #3161
+ [ ] Pony
+ [ ] Ruby
+ [ ] Rust
+ [ ] Nim
+ [x] Scala => #3519
+ [ ] Swift
+ [ ] V
   
------
Closes #2622

### CODE REVIEW

**Comment by waghanza** [comment]
@pimbrouwers @panesofglass @jchannon would you mind checking if logging is disabled for `C#` / `F#` ?

**Comment by pimbrouwers** [comment]
It definitely is in the Falco sample.

**Comment by panesofglass** [comment]
I already disabled it for all the others so that the comparison would be fair.

**Comment by waghanza** [comment]
I think we have to merge this ... before it's get too old

I hope that errors will be spotted later by this awesome community ❤️

**Pull request merged**
