### PR TITLE
PHP/Antidot: Run with xdebug mode off and allow using cached config

### PR DESCRIPTION
**Pull request by kpicaza**
Hi @waghanza I want to try running the same command with XDEBUG_MODE=off environment variable, I'm obtaining much better response times locally.

Also I added cache directory, to allow the framework creating the cached config file.

Thanks again for the great work you are doing :raised_hands::raised_hands::raised_hands:

### CODE REVIEW

**Review by waghanza — CHANGES_REQUESTED** [review]
I prefer to add a bootstrap command
```yaml
bootstrap: 
  - mkdir var/cache
```
inside `framework` node in config

**Comment by waghanza** [comment]
I ue a config file
```yml
language:
  engines:
    reactphp:
      command: bin/console serve

framework:
  website: antidotfw.io
  github: antidot-framework/antidot-framework
  version: 2.0

  environment:
    XDEBUG_MODE: off

  bootstrap:
    - mkdir var/cache -p

  files:
    - "**/*.php"
    - composer.json
    - bin/console
    - "**/*.prod.yaml"

  engines:
    - reactphp
```

but seems that hat the rps does not change

**Comment by kpicaza** [comment]
Maybe Xdebug is already disabled:

When xdebug is enabled 
```
λ kpicaza [antidot] → bin/console serve 
```
```
λ kpicaza [~] → wrk -t8 -c512 -d15s http://127.0.0.1:3000/
Running 15s test @ http://127.0.0.1:3000/
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    23.90ms   11.04ms 349.00ms   97.69%
    Req/Sec     2.77k   241.66     3.54k    89.66%
  330992 requests in 15.08s, 38.19MB read
Requests/sec:  21949.57
Transfer/sec:      2.53MB
```

With xdebug disabled
```
λ kpicaza [antidot] →  XDEBUG_MODE=off bin/console serve 
```
```
λ kpicaza [~] → wrk -t8 -c512 -d15s http://127.0.0.1:3000/
Running 15s test @ http://127.0.0.1:3000/
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    13.98ms   23.77ms 252.35ms   95.53%
    Req/Sec     6.50k     1.03k   14.90k    86.07%
  775798 requests in 15.08s, 89.52MB read
Requests/sec:  51437.51
Transfer/sec:      5.94MB
```

My machine has 8 cores and 32G/RAM. Thank for testing it.

**Comment by waghanza** [comment]
Not big change on my side

###### Before (without)

```
$> wrk -t8 -c512 -d15s http://172.17.0.2:3000
Running 15s test @ http://172.17.0.2:3000
  8 threads and 512 connections
	  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    18.06ms   16.14ms 219.50ms   96.94%
    Req/Sec     3.93k   554.78     8.55k    91.97%
  470148 requests in 15.10s, 54.25MB read
Requests/sec:  31138.88
Transfer/sec:      3.59MB
```


###### After (with)

```
$> wrk -t8 -c512 -d15s http://172.17.0.2:3000
Running 15s test @ http://172.17.0.2:3000
  8 threads and 512 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency    17.80ms   15.08ms 217.74ms   97.12%
    Req/Sec     3.94k   513.11     9.87k    91.89%
  471739 requests in 15.09s, 54.44MB read
Requests/sec:  31254.95
Transfer/sec:      3.61MB
```

The dockerfile is
```dockerfile
FROM php:8.2-fpm-alpine3.16

RUN apk add git zlib-dev libzip-dev build-base autoconf nginx openrc curl-dev icu-dev oniguruma-dev linux-headers  libevent-dev

WORKDIR /usr/src/app

RUN docker-php-ext-install zip opcache



  RUN docker-php-ext-install intl
  RUN docker-php-ext-install sockets
  RUN docker-php-ext-install pcntl

  RUN mkdir -p /usr/src/php/ext/event
  RUN curl -fsSL https://pecl.php.net/get/event | tar xvz -C "/usr/src/php/ext/event" --strip 1
  RUN docker-php-ext-install event

ENV EVENT_EXT_FILE /usr/local/etc/php/conf.d/docker-php-ext-event.ini
RUN if [[ -f "${EVENT_EXT_FILE}" ]] ; then \
  rm -fr /usr/local/etc/php/conf.d/docker-php-ext-sockets.ini ; \
  sed -e '1i extension=sockets' /usr/local/etc/php/conf.d/docker-php-ext-event.ini > /tmp/file ; \
  mv /tmp/file /usr/local/etc/php/conf.d/docker-php-ext-event.ini ; fi


  COPY 'config/config.php' 'config/config.php'
  COPY 'config/container.php' 'config/container.php'
  COPY 'config/services/dependencies.prod.php' 'config/services/dependencies.prod.php'
  COPY 'public/index.php' 'public/index.php'
  COPY 'router/middleware.php' 'router/middleware.php'
  COPY 'router/routes.php' 'router/routes.php'
  COPY 'src/Handler/Home.php' 'src/Handler/Home.php'
  COPY 'src/Handler/User.php' 'src/Handler/User.php'
  COPY 'src/Handler/UserId.php' 'src/Handler/UserId.php'
  COPY 'composer.json' 'composer.json'
  COPY 'bin/console' 'bin/console'

    RUN curl -sSL https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
    RUN composer install --no-dev --prefer-dist --classmap-authoritative
    RUN composer dumpautoload -o
    RUN mkdir var/cache -p

  CMD XDEBUG_MODE=off bin/console serve
```

**Comment by kpicaza** [comment]
Xdebug is not installed ;-D

Using given dockerfile:
```
→ docker run -i -t antidot /bin/sh                                                                                                                                                                                                                             [f99cb869]
/usr/src/app # php -v
PHP 8.2.5 (cli) (built: Apr 14 2023 18:04:14) (NTS)
Copyright (c) The PHP Group
Zend Engine v4.2.5, Copyright (c) Zend Technologies
    with Zend OPcache v8.2.5, Copyright (c), by Zend Technologies
```

Feel free to close this PR. And thanks again for your help :raised_hands:

**Pull request closed without merging**
