### PR TITLE
added cyclone3

### PR DESCRIPTION
**Pull request by greed2411**
solves #290 

I'm not sure about the Dockerfile, because of the git line, it worked manually for me. So I have to trouble you @waghanza again for help. Thanks.

### CODE REVIEW

**Comment by waghanza** [comment]
@greed2411  I have change testing process, to ensure `cyclone` is **working** you can execute
~~~sh
export FRAMEWORK=cyclone
bin/neph ${FRAMEWORK}
crystal spec
~~~
this feature is still in **WIP**, I'll add some docs later

**Comment by greed2411** [comment]
any luck? @waghanza

**Comment by waghanza** [comment]
@greed2411  so impatient ... it take time, but I'm on it :stuck_out_tongue_closed_eyes:

**Comment by waghanza** [comment]
and `python3` will be in **cyclone** next _release_ :tada:
https://github.com/fiorix/cyclone/pull/173

I'll merge this as an **experimental** framework

**Comment by waghanza** [comment]
@greed2411 was the source repository removed ? I can see `unknown repository` just below this `PR` title

**Comment by greed2411** [comment]
Oh my god. Please forgive me. I recently made a fork because my as actual one went haywire and I had to do it from scratch again. Should I make one again? Your commits all would be lost. I'm so sorry 😥😭

**Comment by waghanza** [comment]
@greed2411  :stuck_out_tongue_closed_eyes: no problem, here to help

I hope you won't do the same mistake again

**Comment by waghanza** [comment]
@greed2411 Your changed are stored in https://github.com/the-benchmarker/web-frameworks/pull/339/files, but can be merged

I close this `PR`, feel free to open a new one :heart:

**Pull request closed without merging**
