### PR TITLE
hanami-api

### PR DESCRIPTION
**Pull request by jodosha**
Hello, this PR adds the newest addition to the Hanami family: `hanami-api`.
It's a minimal, extremely fast, lightweight Ruby framework for HTTP APIs.

Thanks for considering to add it to the benchmark. 💚

### CODE REVIEW

**Comment by waghanza** [comment]
Awesome, always a pleasure to add new frameworks

**Comment by jodosha** [comment]
@waghanza Same of #2285 : CI is failing for unrelated reasons to this PR. 🤷‍♂

**Comment by waghanza** [comment]
Yep, I can merge this, but I prefer to add result (I'm computing them right now)

**Comment by waghanza** [comment]
@jodosha I'm on this `PR`, but will take a will I think

I can provide results, but `plezi`, `phoon` and `raze` are not working (impact whole results)

/cc @boazsegev @ducdetronquito @samueleaton

**Comment by boazsegev** [comment]
Thank you @waghanza for CC-ing me.

Could you point out what errors you get with Plezi (I assume you're testing on a Linux / BSD machine)?

I looked at the CI and Plezi shows as "passed"...

I know we're using Docker, but could testing conflict be possible on either the framework machine or the testing machine? Could there be issues lingering from previous tests, such as running out of addresses/ports and such?

This might occur if the tests run too close to each other (for example, the TCP/IP stack often keeps closed socket addresses as "reserved" for out 2 minutes after closure (due to possible "echos" on the net)...?

Kindly,
   Bo.

**Comment by ducdetronquito** [comment]
Hi @waghanza !

Unfortunately, I am not able to reproduce the [segfault](https://github.com/the-benchmarker/web-frameworks/issues/2193#issuecomment-577653090) you warn me about !

As I don't have time to work on phoon in the upcoming weeks and I don't want to impact others, do you agree to remove phoon from the benchmark ?

Thanks in advance, and have a nice day :)

**Comment by waghanza** [comment]
@jodosha I've updated results (btw, I've temporarily removed `plezi`)

**Comment by boazsegev** [comment]
@waghanza ,

I don't mind. You can remove it. In effect, I don't know if anyone really uses Plezi anymore. All its best features migrated into the `iodine` server API (Plezi is now closer to being a wrapper around `iodine`).

**Comment by jodosha** [comment]
@waghanza Thank you very much for taking care of this. 💯

**Pull request merged**
