### PR TITLE
Update `happyx` web framework for `nim`, `javascript` and `python`

### PR DESCRIPTION
**Pull request by Ethosa**
1. change folders naming because https://github.com/the-benchmarker/website/issues/52
2. update versions
3. change python library to actual

### CODE REVIEW

**Review by waghanza — APPROVED** [review]

**Comment by Ethosa** [comment]
Python library is crashed, I'll fix it later

**Comment by Ethosa** [comment]
@waghanza all checks was passed 👀

**Comment by Ethosa** [comment]
Can we change base from `master` to `update`? #7581

**Comment by waghanza** [comment]
> Can we change base from `master` to `update`? #7581 

I prefer not to :-)

However, I'll rebase update from master, so results for next round will take those changes into account

**Review by waghanza — APPROVED** [review]

**Comment by waghanza** [comment]
I have the same issue

```
Traceback (most recent call last):
  File "/usr/src/app/server.py", line 1, in <module>
    from happyxpy import Server
  File "/usr/local/lib/python3.12/site-packages/happyxpy/__init__.py", line 4, in <module>
    from .server import Server, happyx
  File "/usr/local/lib/python3.12/site-packages/happyxpy/server.py", line 7, in <module>
    import happyxpy.happyx as happyx
ImportError: /usr/local/lib/python3.12/site-packages/happyxpy/happyx.so: cannot open shared object file: No such file or directory
````

**Comment by Ethosa** [comment]
strange issue because package contains happyx.so https://pypi.org/project/happyxpy/#files

**Comment by waghanza** [comment]
> strange issue because package contains happyx.so https://pypi.org/project/happyxpy/#files

indeed, but this module is complied for amd64, not arm64

You can specify architecture with github actions

**Comment by Ethosa** [comment]
> indeed, but this module is complied for amd64, not arm64
Oh, I see! Thanks!

**Pull request merged**
