### PR TITLE
Update

### PR DESCRIPTION
**Pull request by waghanza**
###### jennet

As `ice` I could not find `libexecinfo` on the last alpine.

Any clue @Theodus ?

###### ambiorix

I can not start `ambiorix`, I have

```r
Error in library(ambiorix) : there is no package called ‘ambiorix’
Calls: source -> withVisible -> eval -> eval -> library
Execution halted
```

cc @JohnCoene

###### comet

I can start `comet`, I have

```php
Fatal error: Type of Comet\Factory\CometPsr17Factory::$responseFactoryClass must be string (as in class Slim\Factory\Psr17\Psr17Factory) in /usr/src/app/vendor/gotzmann/comet/src/Factory/CometPsr17Factory.php on line 6
```

cc @gotzmann 

###### ice

I can not setup `ice` on **alpine**
```
 apk info --who-owns execinfo.h
ERROR: execinfo.h: Could not find owner package
```

How can I do so @mruz ?

###### nawa

Not sure why but at some point the server does not respond

cc @jatofg

### CODE REVIEW

**Comment by JohnCoene** [comment]
I do apologise for the late response.
ambiorix has been archived from CRAN the command `install.packages` no longer works.

It now must be installed from GitHub using the remotes package.

```r
# R console
install.packages("remotes")
remotes::install_github("devOpifex/ambiorix")
```

Not sure how to fix via PR.

**Comment by waghanza** [comment]
@JohnCoene is there any reasons behind `ambiorix` been archived ?

**Comment by mruz** [comment]
Yes, `libexecinfo` has been removed in the latest alpine version, you can stick with the previous `8.1-fpm-alpine3.16`:
https://github.com/the-benchmarker/web-frameworks/blob/4fdaa8beed47b1257142bbffe3a296ac5627621d/php/Dockerfile#L1

I will have a look if any other package provides `execinfo.h`.

**Comment by JohnCoene** [comment]
> @JohnCoene is there any reasons behind `ambiorix` been archived ?

The CRAN repository is very costly to maintain in terms of time, my packages are no longer submitted to the repository. 

No issue with Ambiorix, it is still fully functioning.

**Comment by JohnCoene** [comment]
Thanks @waghanza, if you do not I will not be offended if ambiorix is removed. Apologies for the trouble

**Comment by waghanza** [comment]
- archttp
- comet
- nawa
- jennet

are still failing

I have used `alpine:3.16` @mruz since `ice` could not be built on **latest** `alpine` due to https://github.com/alpinelinux/aports/commit/50795a14dee639ce2dcc836e2b2baca9bad4a1b1

`ambiorix` is updated @JohnCoene

**Pull request merged**
