### PR TITLE
scala: upgrade of base image

### PR DESCRIPTION
**Pull request by whiplash**
------
Closes #5009

### CODE REVIEW

**Comment by waghanza** [comment]
You think 3.1 is not ready ?

**Review by waghanza — CHANGES_REQUESTED** [review]
We do not need to change `scalaVersion` in sbt files ?

**Comment by whiplash** [comment]
no no, this is `sbt` version. not `scala`

**Comment by whiplash** [comment]
> You think 3.1 is not ready ?

Unfortunately Scala 3 migration is still an open point for many libraries/frameworks.

**Comment by waghanza** [comment]
> > You think 3.1 is not ready ?
> 
> Unfortunately Scala 3 migration is still an open point for many libraries/frameworks.

Yeah, I saw, only `http4s` is ready as far as I understand

> We do not need to change scalaVersion in sbt files ?

This image does not update scala from 2.13.6 to 2.18.8 ?

**Comment by whiplash** [comment]
You are right: 2.13.8 is the latest and I think all frameworks are already using it.

**Review by waghanza — APPROVED** [review]
scala version is already 👍🏻 
https://github.com/the-benchmarker/web-frameworks/blob/0c358cc58f39d76d09351dd56529e42ea6d6b427/scala/http4s/build.sbt#L4

**Pull request merged**
