### PR TITLE
Adding scala/http4s

### PR DESCRIPTION
**Pull request by mfirry**

### CODE REVIEW

**Comment by waghanza** [comment]
Thanks @mfirry 

I see you are adding stuffs, you are not in a hurry :stuck_out_tongue: ut_tongue:

Please add `[WIP]` prefix, if this `PR` is not complete

**Comment by waghanza** [comment]
@mfirry Could you give me the right to write on **master** on your _fork_ ? (github protected branch feature does not allow me to push)

PS : It to fix / test your `PR`

**Comment by mfirry** [comment]
Sure.

**Comment by waghanza** [comment]
@mfirry I'm still trying to progress with github ...

I have pushed a new branch **add_http4s** on `your` repo.

Could yo re-create this `PR` from there ?

**Comment by mfirry** [comment]
Done. Unfortunately I had to create a new PR

**Pull request closed without merging**
