### PR TITLE
add bottle

### PR DESCRIPTION
**Pull request by greed2411**
Solves #299 

@waghanza gunicorn support exists for bottle but i tried to run it on my machine, it said it couldn't find `bottle` so I gave my best. This is the [article](http://blog.yprez.com/running-a-bottle-app-with-gunicorn.html) I tried to follow but failed to execute it properly. Thanks.

### CODE REVIEW

**Comment by waghanza** [comment]
@greed2411 sure, I'll update your `PR`

**Comment by greed2411** [comment]
Yes @waghanza what else is required? 
I wanted to give two separate pull requests for bottle and cyclone. So that it looks simple and clean.

**Comment by waghanza** [comment]
@greed2411 not sure why this `PR` was closed

**Comment by greed2411** [comment]
Alright.

**Pull request closed without merging**
